import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {calculateWater,adaptWaterBalance} from '../motor_web.ts';
const file=new URL('../ejemplo_entrada.json',import.meta.url),fresh=()=>JSON.parse(readFileSync(file,'utf8'));
const run=(v=fresh())=>calculateWater(v.balance_termico,v.configuracion_agua);
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<=1e-9*Math.max(1,Math.abs(b)),`${a} != ${b}`);
test('all nine steps and signed provenance remain serializable',()=>{const r=run();assert.equal(r.apto,true);assert.equal(r.pasos.length,9);for(const s of r.pasos){assert.equal(s.estado,'ok');assert.ok(r.resultado[s.clave].trace.ecuacion);}assert.equal(r.input.procedencia.base_carga,'local');assert.match(r.diagnostico.warnings.join(' '),/SINTÉTIC/);assert.doesNotThrow(()=>JSON.stringify(r));});
test('inputs are immutable on repeated calculation',()=>{const v=fresh(),before=JSON.stringify(v),a=run(v),b=run(v);assert.equal(JSON.stringify(v),before);assert.deepEqual(a,b);});
test('missing FCU does not hide loads or fabricate selection',()=>{const v=fresh();v.configuracion_agua.catalogo_fcu=[];const r=run(v);assert.equal(r.pasos[0].estado,'ok');assert.equal(r.pasos[1].estado,'ok');assert.equal(r.pasos[2].estado,'error');assert.equal(r.pasos[3].estado,'bloqueado');assert.equal(r.apto,false);});
test('network missing allows thermal flows but blocks pipe/pump stages',()=>{const v=fresh();v.configuracion_agua.layout.secciones=[];const r=run(v);assert.equal(r.pasos[1].estado,'ok');assert.equal(r.pasos[4].estado,'error');assert.equal(r.pasos[5].estado,'bloqueado');});
test('equipment base is explicit and provenance cannot be silently removed',()=>{const v=fresh();v.balance_termico.base_carga='equipo';assert.equal(run(v).input.procedencia.base_carga,'equipo');delete v.balance_termico.espacios[0].procedencia.trace_ids;assert.throws(()=>run(v),/trazabilidad/);});
test('strict units and factor 500 with one overcooling factor',()=>{const v=fresh(),r=run(v);near(r.resultado.cargas_del_sistema.Q_refrig_btuh,10500);near(r.resultado.caudales_por_zona.gpm_por_zona.A,2);v.balance_termico.espacios[0].verano.unidad='kW';v.balance_termico.espacios[0].verano.total/=3412.141633127942;v.balance_termico.espacios[0].verano.sensible/=3412.141633127942;for(const h of v.balance_termico.espacios[0].verano.perfil){h.total/=3412.141633127942;h.sensible/=3412.141633127942;}near(run(v).resultado.caudales_por_zona.gpm_por_zona.A,2);});
test('tank pressures are not accepted as dimensionless coefficients',()=>{const v=fresh();v.configuracion_agua.tanque.P_a=30;const r=run(v);assert.equal(r.pasos[6].estado,'error');assert.equal(r.pasos[7].estado,'ok');assert.equal(r.apto,false);});
test('incomplete return path does not report a usable pump',()=>{const v=fresh();v.configuracion_agua.layout.circuitos[0].secciones=['ida'];const r=run(v);assert.equal(r.pasos[5].estado,'error');assert.equal(r.pasos[6].estado,'ok');});
test('copper cannot borrow steel ID and support tables',()=>{const v=fresh();v.configuracion_agua.material='copper';assert.equal(run(v).apto,false);assert.match(run(v).diagnostico.errores.join(' '),/Cobre/);});
test('nominal FCU conditions must match thermal air state',()=>{const v=fresh();v.balance_termico.espacios[0].procedencia.condiciones_aire={verano:{temperatura_C:25,bulbo_humedo_C:18},invierno:{temperatura_C:21}};assert.equal(run(v).pasos[2].estado,'error');});
test('negative thermal loads, invalid RH, repeated hours and overlarge sensible are rejected',()=>{for(const mutate of [(v:any)=>v.balance_termico.espacios[0].verano.total=-1,(v:any)=>v.balance_termico.espacios[0].verano.sensible=99999,(v:any)=>v.balance_termico.espacios[0].verano.perfil[1].hora=9,(v:any)=>v.balance_termico.espacios[0].procedencia.condiciones_aire={verano:{rh_pct:101}}]){const v=fresh();mutate(v);let rejected=false;try{rejected=!run(v).apto;}catch{rejected=true;}assert.ok(rejected);}});
test('profiles determine plant coincident peak and terminal branches retain nominal flow',()=>{const v=fresh(),b=structuredClone(v.balance_termico.espacios[0]);b.id='B';b.verano.perfil[0].total=10000;b.verano.perfil[1].total=8000;v.balance_termico.espacios.push(b);v.configuracion_agua.exposiciones.B='E';v.configuracion_agua.layout.orden_exposiciones=['N','E'];v.configuracion_agua.layout.diversidad='chart6';for(const dir of ['ida','retorno'])v.configuracion_agua.layout.secciones.push({...structuredClone(v.configuracion_agua.layout.secciones.find((s:any)=>s.id===dir)),id:dir+'-B',espacios_servidos:['B']});v.configuracion_agua.layout.circuitos.push({...structuredClone(v.configuracion_agua.layout.circuitos[0]),id:'B-route',espacio_id:'B',secciones:['ida-B','retorno-B']});const r=run(v);assert.equal(r.apto,true);near(r.resultado.cargas_del_sistema.Q_bloque_btuh,18000);assert.equal(r.resultado.diversidad.exposiciones.at(-1).F_div,1);for(const s of r.resultado.dimensionamiento.secciones)near(s.gpm_frio,2.4);});
test('glycerol/glycol and extrapolated erosion domains cannot use factor500',()=>{const v=fresh();v.configuracion_agua.condiciones_diseno.fluido='glycol';assert.equal(run(v).apto,false);v.configuracion_agua.condiciones_diseno.fluido='water';v.configuracion_agua.condiciones_diseno.horas_operacion_anual=9000;assert.equal(run(v).apto,false);});
test('dangerous imported properties rejected before app state',()=>{const v=fresh();v.configuracion_agua.tuberias=JSON.parse('{"__proto__":{"x":1}}');assert.throws(()=>adaptWaterBalance(v.balance_termico,v.configuracion_agua),/no permitida/);});
test('nonfinite values cannot disappear in JSON cloning or become valid results',()=>{for(const x of [NaN,Infinity,-Infinity]){const v=fresh();v.configuracion_agua.condiciones_diseno.rugosidad_ft=x;assert.throws(()=>run(v),/NaN|Infinity/);}});
test('Python CLI and browser outputs agree across operating cases',{skip:!process.env.WATER_PYTHON},()=>{
 const folder=mkdtempSync(join(tmpdir(),'thermabot-water-parity-'));try{
  for(const mode of ['base','no-heating','heating-governs','manual-friction','copper','parallel-chart6']){
   const v=fresh(),cfg=v.configuracion_agua;
   if(mode==='no-heating')v.balance_termico.espacios[0].invierno.total=0;
   if(mode==='heating-governs'){v.balance_termico.espacios[0].invierno.total=18000;cfg.catalogo_fcu[0].Q_calef_nom_btuh=20000;cfg.catalogo_fcu[0].GPM_calef_nom=3;}
   if(mode==='manual-friction')for(const s of cfg.layout.secciones){s.nps='1';s.referencia_nps='1';s.referencia_gpm=2.4;s.referencia_calef_gpm=1.5;s.friction_rate_verificado=1.7;s.friction_rate_calef_verificado=.9;s.fuente_friccion='Verified fixture';}
   if(mode==='copper'){cfg.material='copper';cfg.tuberias={'CU-1':{id_in:1.049,od_in:1.1,wt_agua_lb_ft:.374,spacing_ft:8,fuente:'Documented fixture',leq_fittings_ft:{}}};}
   if(mode==='parallel-chart6'){const b=structuredClone(v.balance_termico.espacios[0]);b.id='B';b.verano.perfil.reverse();v.balance_termico.espacios.push(b);cfg.exposiciones.B='E';cfg.layout.diversidad='chart6';cfg.layout.orden_exposiciones=['N','E'];for(const dir of ['ida','retorno'])cfg.layout.secciones.push({...structuredClone(cfg.layout.secciones.find((s:any)=>s.id===dir)),id:dir+'-B',espacios_servidos:['B']});cfg.layout.circuitos.push({...structuredClone(cfg.layout.circuitos[0]),id:'circuit-B',espacio_id:'B',secciones:['ida-B','retorno-B']});}
   const input=join(folder,mode+'.json'),output=join(folder,mode+'-out.json');writeFileSync(input,JSON.stringify(v));const processResult=spawnSync(process.env.WATER_PYTHON!,[new URL('../carrier_water.py',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1'),'--input',input,'--json-output',output,'--no-color'],{encoding:'utf8',timeout:10000});assert.equal(processResult.status,0,processResult.stderr+' '+processResult.stdout);const py=JSON.parse(readFileSync(output,'utf8')),web=run(v);assert.equal(web.apto,py.apto,mode);
   const visit=(a:any,b:any)=>{if(typeof b==='number'){near(a,b);return;}if(Array.isArray(b)){assert.equal(a.length,b.length);b.forEach((x:any,i:number)=>visit(a[i],x));return;}if(b&&typeof b==='object'){for(const [k,x]of Object.entries(b)){if(['trace','fuente','condiciones','nota','apto','checks','errores'].includes(k))continue;visit(a[k],x);}return;}assert.equal(a,b);};
   for(const key of ['cargas_del_sistema','caudales_por_zona','diversidad','dimensionamiento','bomba','tanque_de_expansion','soportes'])visit(web.resultado[key],py.resultado[key]);
  }
 }finally{rmSync(folder,{recursive:true,force:true});}
});
