import test from 'node:test';
import assert from 'node:assert/strict';
import {demoInput} from '../src/engine/demo.ts';
import {datum} from '../src/engine/core.ts';
import {calculate} from '../src/engine/index.ts';
import {prepareEnvelope,migrateEnvelope} from '../src/engine/geometria_edificio.ts';
import {demoRoom,createRoom,calculateBuilding,rectangularizeRoom} from '../src/engine/edificio.ts';
const near=(a:number,b:number,t=1e-7)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);
test('migración conserva resultados v2 y no descuenta ventanas dos veces',()=>{const source=demoInput(),raw=structuredClone(source),migrated=migrateEnvelope(source),old=calculate(source),next=calculate(migrated);assert.deepEqual(source,raw);near(migrated.surfaces[0].grossArea!.value,28);near(next.input.surfaces[0].area.value,22);for(let h=0;h<24;h++)near(old.hours[h].total,next.hours[h].total);});
test('ventanas descuentan sólo su cerramiento; reubicarlas hereda la nueva orientación',()=>{const r=demoRoom(),second=structuredClone(r.windows[0]);second.id='east-glass';second.name='Vidrio este';second.parentId='east';second.area=datum(4,'m²');r.windows.push(second);const p=prepareEnvelope(r).input;near(p.surfaces.find(s=>s.id==='east')!.area.value,18.4);near(p.surfaces[0].area.value,22);assert.equal(p.windows[1].azimuth.value,-90);r.windows[1].parentId='west';const moved=prepareEnvelope(r).input;near(moved.surfaces.find(s=>s.id==='east')!.area.value,22.4);near(moved.surfaces.find(s=>s.id==='west')!.area.value,18.4);assert.equal(moved.windows[1].azimuth.value,90);});
test('áreas manuales fijas y cerramientos vinculados a dimensiones recalculados',()=>{const r=demoRoom(),extra=structuredClone(r.surfaces[1]);extra.id='extra';extra.areaMode='manual';extra.grossArea=datum(7,'m²');r.surfaces.push(extra);r.geometry.length=datum(12,'m');const p=prepareEnvelope(r).input;near(p.surfaces[0].area.value,12*2.8-6);near(p.surfaces.find(s=>s.id==='roof')!.grossArea!.value,96);near(p.surfaces.find(s=>s.id==='extra')!.area.value,7);});
test('rechaza ventanas excesivas, cerramientos ausentes e IDs duplicados',()=>{const r=demoRoom();r.windows[0].area.value=29;assert.throws(()=>calculate(r),/superan el área/);r.windows[0].area.value=6;r.windows[0].parentId='missing';assert.throws(()=>calculate(r),/no existe/);r.windows[0].parentId='north';r.windows[0].id='north';assert.throws(()=>calculate(r),/duplicado/);});
test('orientación cambia radiación y deja traza de orientación heredada',()=>{const north=demoRoom(),west=structuredClone(north);west.surfaces[0].azimuth=datum(90,'°');const a=calculate(north),b=calculate(west);assert.equal(b.input.windows[0].azimuth.value,90);assert.ok(b.trace.some(t=>t.id==='window-north-orientation'));assert.notDeepEqual(a.trace.find(t=>t.id==='window-north-beam-gain')!.result,b.trace.find(t=>t.id==='window-north-beam-gain')!.result);});
test('recinto rectangular: una pared de referencia define orientaciones y áreas de las cuatro',()=>{
 const r=demoRoom();r.geometry.length=datum(5,'m');r.geometry.width=datum(4,'m');r.geometry.height=datum(2.8,'m');r.windows=[];
 const west=r.surfaces.find(s=>s.id==='west')!,roof=r.surfaces.find(s=>s.id==='roof')!;r.surfaces=[west,roof];
 const out=rectangularizeRoom(r,'west',180),walls=out.surfaces.filter(s=>s.kind==='wall');
 assert.equal(walls.length,4);assert.equal(out.surfaces.filter(s=>s.kind==='roof').length,1);
 assert.deepEqual(walls.map(s=>s.azimuth.value).sort((a,b)=>a-b),[-90,0,90,180]);
 assert.deepEqual(new Set(walls.map(s=>s.name)),new Set(['Muro Norte','Muro Este','Muro Sur','Muro Oeste']));
 const north=walls.find(s=>s.name==='Muro Norte')!,south=walls.find(s=>s.name==='Muro Sur')!,east=walls.find(s=>s.name==='Muro Este')!,newWest=walls.find(s=>s.name==='Muro Oeste')!;
 near(north.grossArea!.value,11.2);near(south.grossArea!.value,11.2);near(east.grossArea!.value,14);near(newWest.grossArea!.value,14);near(out.surfaces.find(s=>s.kind==='roof')!.grossArea!.value,20);
 assert.equal(walls.filter(s=>s.id!==west.id).every(s=>s.u.provenance==='heredado'),true);
 assert.doesNotThrow(()=>calculate(out));
});
test('recinto rectangular reorienta muros existentes sin perder ventanas ni propiedades editadas',()=>{
 const r=demoRoom(),winId=r.windows[0].id,northId=r.surfaces.find(s=>s.id==='north')!.id;
 r.surfaces.find(s=>s.id==='east')!.u=datum(9,'kcal/(h·m²·°C)','ingresado','Ensayo');
 const out=rectangularizeRoom(r,northId,-90);
 assert.equal(out.windows.find(w=>w.id===winId)!.parentId,northId);
 assert.equal(out.windows.find(w=>w.id===winId)!.azimuth.value,-90);
 assert.equal(out.surfaces.find(s=>s.id==='east')!.u.value,9);
 assert.equal(out.surfaces.find(s=>s.id===northId)!.name,'Muro Este');
});
test('recinto rectangular no pisa geometrías con más de cuatro muros',()=>{
 const r=demoRoom(),extra=structuredClone(r.surfaces.find(s=>s.kind==='wall')!);extra.id='extra-wall';extra.name='Muro extra';r.surfaces.push(extra);
 assert.throws(()=>rectangularizeRoom(r,r.surfaces[0].id,180),/más de cuatro muros/);
});
test('ambiente nuevo independiente, sin ventanas ni cargas heredadas por accidente',()=>{const original=demoRoom(),snapshot=structuredClone(original),r=createRoom(original,'office','Oficina',6,4,3);assert.deepEqual(original,snapshot);assert.equal(r.windows.length,0);assert.equal(r.internals.people.count.value,0);assert.equal(r.outdoorFlow.value,0);assert.equal(r.surfaces.length,5);near(r.surfaces[4].grossArea!.value,24);assert.equal(r.surfaces[0].u.provenance,'heredado');r.surfaces[0].u.value=2;near(original.surfaces[0].u.value,1.2);assert.doesNotThrow(()=>calculate(r));assert.throws(()=>createRoom(original,'bad','Error',0,4,3));});
test('sin ventanas o cerramientos no hay índices fijos ni cargas fantasma',()=>{const r=demoRoom();r.windows=[];const a=calculate(r);near(a.input.surfaces[0].area.value,28);r.surfaces=[];const b=calculate(r);assert.equal(b.hours[12].components['solar-vidrios'],undefined);assert.equal(b.hours[12].components.envolvente,undefined);assert.ok(b.hours[12].total<a.hours[12].total);});
test('edificio suma horas simultáneas, no máximos individuales en horarios distintos',()=>{const a=demoRoom();a.id='a';a.surfaces=[];a.windows=[];a.outdoorFlow=datum(0,'m³/h');a.infiltrationACH=datum(0,'ACH');a.internals.people.count=datum(1,'1');a.internals.people.sensible=datum(100,'W');a.internals.people.latent=datum(10,'W');a.internals.lights.installedPower=datum(0,'W');a.internals.equipment.inputPower=datum(0,'W');a.internals.people.schedule=Array.from({length:24},(_,h)=>datum(h===9?1:0,'1'));const b=structuredClone(a);b.id='b';b.room='Sala B';b.internals.people.schedule=Array.from({length:24},(_,h)=>datum(h===15?1:0,'1'));const r=calculateBuilding({schemaVersion:1,projectId:a.projectId,name:'Ensayo',rooms:[a,b]});near(r.peak.total,110);near(r.results.reduce((v,z)=>v+z.peak.total,0),220);assert.equal(r.trace.find(t=>t.id==='building-peak')!.result,110);near(r.area,160);near(r.volume,448);assert.equal(r.hours.length,24);});
test('edificio rechaza climas distintos, mezcla de proyectos e IDs repetidos',()=>{const a=demoRoom(),b=createRoom(a,'b','B',4,4,3),building={schemaVersion:1 as const,projectId:a.projectId,name:'Edificio',rooms:[a,b]};b.climate.location.day=22;assert.throws(()=>calculateBuilding(building),/mismo clima/);b.climate.location.day=21;b.projectId='other';assert.throws(()=>calculateBuilding(building),/otro proyecto/);b.projectId=a.projectId;b.id=a.id;assert.throws(()=>calculateBuilding(building),/duplicado/);});
