import test from 'node:test';
import assert from 'node:assert/strict';
import {datum} from '../src/engine/core.ts';
import {demoRoom,createRoom,calculateBuilding} from '../src/engine/edificio.ts';
import {resolvePartitions} from '../src/engine/particiones.ts';
import {calculate} from '../src/engine/index.ts';
import type {BuildingInput,SharedPartition} from '../src/engine/types.ts';
const near=(a:number,b:number,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);
function fixture():BuildingInput {
 const a=demoRoom();a.id='a';a.room='Sala fría';a.requestedMode='instantaneo';a.climate.indoorTemperature=datum(24,'°C');
 const b=createRoom(a,'b','Sala cálida',6,4,2.8);b.climate.indoorTemperature=datum(28,'°C');
 const p:SharedPartition={id:'ab',projectId:a.projectId,name:'Tabique ensayo',roomAId:a.id,roomBId:b.id,surfaceAId:'east',surfaceBId:b.surfaces[3].id,area:datum(10,'m²','ingresado','Geometría de ensayo'),u:datum(1.5,'W/(m²·K)','ingresado','Valor de ensayo analítico'),model:'estacionario'};
 return {schemaVersion:1,projectId:a.projectId,name:'Ensayo analítico',rooms:[a,b],partitions:[p]};
}
test('U·A·ΔT: +60/-60 W, sensible y conservación exacta por hora',()=>{const input=fixture(),snapshot=structuredClone(input),result=calculateBuilding(input);assert.deepEqual(input,snapshot);for(let h=0;h<24;h++){near(result.results[0].hours[h].components.particiones.sensible,60);near(result.results[1].hours[h].components.particiones.sensible,-60);near(result.results[0].hours[h].components.particiones.latent,0);near(result.hours[h].total,result.results.reduce((v,r)=>v+r.hours[h].total,0));}assert.deepEqual(result.trace.find(t=>t.id==='partition-ab-conservation')!.result,Array(24).fill(0));const t=result.results[0].trace.find(t=>t.id==='partition-ab')!;assert.equal(t.variables.U.source,'Valor de ensayo analítico');assert.equal(t.variables.Tadj.value,28);assert.equal(t.unit,'W');});
test('área compartida deja de recibir sol-aire en ambas caras, sin mutar área original',()=>{const building=fixture(),r=calculateBuilding(building);const a=r.results[0],b=r.results[1];near(a.trace.find(t=>t.id==='east-exterior-area')!.result as number,12.4);near(b.trace.find(t=>t.id===building.partitions![0].surfaceBId+'-exterior-area')!.result as number,1.2);near(a.input.surfaces.find(s=>s.id==='east')!.area.value,22.4);const control=structuredClone(building);control.partitions=[];control.rooms[0].surfaces.find(s=>s.id==='east')!.grossArea=datum(12.4,'m²');control.rooms[0].surfaces.find(s=>s.id==='east')!.areaMode='manual';control.rooms[1].surfaces[3].grossArea=datum(1.2,'m²');control.rooms[1].surfaces[3].areaMode='manual';const reference=calculateBuilding(control);for(let h=0;h<24;h++){near(a.hours[h].total,reference.results[0].hours[h].total+60);near(b.hours[h].total,reference.results[1].hours[h].total-60);near(r.hours[h].total,reference.hours[h].total);}});
test('misma temperatura da cero; invertir diferencia cambia el signo y nunca recorta créditos negativos',()=>{const b=fixture();b.rooms[1].climate.indoorTemperature=datum(24,'°C');const same=calculateBuilding(b);near(same.results[0].hours[0].components.particiones.sensible,0);b.rooms[1].climate.indoorTemperature=datum(20,'°C');const reverse=calculateBuilding(b);near(reverse.results[0].hours[12].components.particiones.sensible,-60);near(reverse.results[1].hours[12].components.particiones.sensible,60);});
test('área compartida excesiva tras descontar vidrios, cero, NaN y unidades incompatibles se rechazan',()=>{const b=fixture();b.partitions![0].surfaceAId='north';b.partitions![0].area=datum(23,'m²');assert.throws(()=>calculateBuilding(b),/supera el área opaca/);b.partitions![0].area=datum(0,'m²');assert.throws(()=>calculateBuilding(b),/> 0/);b.partitions![0].area.value=NaN;assert.throws(()=>calculateBuilding(b),/NaN/);b.partitions![0].area=datum(5,'m²');b.partitions![0].u=datum(1,'W');assert.throws(()=>calculateBuilding(b),/incompatible/);b.partitions![0].u=datum(1,'W/(m²·K)','ingresado','');assert.throws(()=>calculateBuilding(b),/Falta procedencia/);});
test('rechaza autorreferencia, IDs repetidos, relaciones duplicadas/inexistentes y otro proyecto',()=>{for(const mutate of [(b:BuildingInput)=>b.partitions![0].roomBId='a',(b:BuildingInput)=>b.partitions!.push(structuredClone(b.partitions![0])),(b:BuildingInput)=>{const p=structuredClone(b.partitions![0]);p.id='second';b.partitions!.push(p);},(b:BuildingInput)=>b.partitions![0].roomBId='missing',(b:BuildingInput)=>b.partitions![0].surfaceAId='missing',(b:BuildingInput)=>b.partitions![0].projectId='otro']){const b=fixture();mutate(b);assert.throws(()=>calculateBuilding(b));}});
test('múltiples vecinos comparten un muro sin exceder su área disponible',()=>{const b=fixture(),c=createRoom(b.rooms[0],'c','Sala C',6,4,2.8);c.climate.indoorTemperature=datum(26,'°C');b.rooms.push(c);const p=structuredClone(b.partitions![0]);p.id='ac';p.roomBId='c';p.surfaceBId=c.surfaces[3].id;p.area=datum(10,'m²');b.partitions!.push(p);const r=calculateBuilding(b);near(r.results[0].hours[0].components.particiones.sensible,90);near(r.results[0].trace.find(t=>t.id==='east-exterior-area')!.result as number,2.4);p.area=datum(13,'m²');assert.throws(()=>calculateBuilding(b),/supera el área opaca/);});
test('partición no transfiere humedad ni altera latente; la temperatura adyacente se actualiza',()=>{const b=fixture(),result=calculateBuilding(b),links=resolvePartitions(b);const independent=calculate(b.rooms[0]);for(let h=0;h<24;h++)near(result.results[0].hours[h].latent,independent.hours[h].latent);b.rooms[1].climate.indoorTemperature=datum(30,'°C');near(calculate(b.rooms[0],resolvePartitions(b).get('a')!).hours[0].components.particiones.sensible,90);near(links.get('a')![0].adjacentTemperature.value,28);assert.ok(result.results[0].warnings.some(w=>w.code==='PARTITION_STEADY_STATE'));});
test('JSON edificio conserva vínculos; importación repetida no descuenta superficies dos veces',()=>{const original=fixture(),json=JSON.parse(JSON.stringify(original)),r=calculateBuilding(json),again=calculateBuilding({...json,rooms:r.results.map(r=>r.input)});for(let h=0;h<24;h++)near(r.hours[h].total,again.hours[h].total);assert.deepEqual(json.partitions,original.partitions);});
test('cara completamente interior sin ganancia exterior y techos no soportados se rechazan',()=>{const b=fixture();b.rooms[1].surfaces[3].grossArea=datum(10,'m²');b.rooms[1].surfaces[3].areaMode='manual';const r=calculateBuilding(b);near(r.results[1].trace.find(t=>t.id===b.partitions![0].surfaceBId+'-exterior-area')!.result as number,0);assert.ok(!r.results[1].trace.some(t=>t.id===b.partitions![0].surfaceBId+'-gain'));b.partitions![0].surfaceAId='roof';assert.throws(()=>calculateBuilding(b),/muros verticales/);});
test('RTS exterior con tablas declaradas informa modelo mixto para particiones estacionarias',()=>{const b=fixture(),values=Array(24).fill(0);values[0]=1;const f={values,source:'Fixture analítico explícito, no biblioteca técnica',construction:'Ensayo',version:'test-1',provenance:'supuesto' as const};for(const r of b.rooms){r.requestedMode='RTS';r.fallback='error';r.factors={cts:structuredClone(f),rts:structuredClone(f),solarRts:structuredClone(f)};}const result=calculateBuilding(b);assert.equal(result.results[0].mode,'mixto');assert.equal(result.results[1].mode,'mixto');near(result.results[0].hours[12].components.particiones.sensible,60);assert.ok(result.results[0].warnings.some(w=>w.code==='PARTITION_STEADY_STATE'));});
