/* Focused management views, using the existing tracker and cloud storage. */
window.TBProjectFlow=function(ctx){
  'use strict';
  const {API,tracker,meta,activity,dialog,toast,esc,tag,date,bind,tasksHtml,documentsHtml,feed,actor}=ctx;
  const $=id=>document.getElementById(id),core=TBProjectFlowCore;
  const statusLabel=s=>({Activo:'En curso','Esperando tercero':'Esperando respuesta',Urgente:'Urgente','En revisión':'En revisión'})[s]||s||'Sin estado';
  const option=(value,label,current)=>'<option value="'+esc(value)+'" '+(value===current?'selected':'')+'>'+esc(label)+'</option>';
  const statuses=current=>['Activo','En revisión','Esperando tercero','Bloqueado','Urgente','Finalizado','Suspendido'].map(s=>option(s,statusLabel(s),current)).join('');
  const stages=current=>[...new Set([current,'Idea','Relevamiento','Anteproyecto','Ingeniería','Pliego','Cotización','Contratación','Adjudicado','Obra','Puesta en marcha','Validación','Cerrado'].filter(Boolean))].map(s=>option(s,s,current)).join('');
  const stamp=s=>s?new Date(s).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Sin actualización registrada';
  const day=s=>s?s.split('-').reverse().join('/'):'Sin fecha';
  const nextDay=p=>p.nextDueDate===undefined?p.targetDate||'':p.nextDueDate;
  const pending=p=>{const list=TBSuiteCore.tasks(tracker(),date(),{}).filter(t=>t.projectId===p.id&&t.status!=='Cumplido');return {total:list.length,overdue:list.filter(t=>t.overdue).length};};
  const wait=p=>p.waitingFor||p.blocker||'Respuesta pendiente de identificar';
  let tab='Resumen',filter='Activos',query='',previewId=null,previewTab='Resumen',previewClosed=false;
  function attention(p){const t=pending(p);if(!TBSuiteCore.active(p))return tag('Archivado','neutral');if(p.status==='Bloqueado')return tag('Bloqueado','risk');if(t.overdue)return tag(t.overdue+' vencidas','risk');if(p.status==='Esperando tercero')return tag('Esperando respuesta','wait');return tag(t.total?t.total+' pendientes':'Sin pendientes','neutral');}

  function table(rows){return '<div class="technical-table management-table"><table><thead><tr><th>Proyecto / establecimiento</th><th>Estado / etapa</th><th>Próxima acción</th><th>Seguimiento</th><th>Último movimiento</th></tr></thead><tbody>'+rows.map(p=>'<tr data-preview-row="'+esc(p.id)+'" class="'+(p.id===previewId?'selected-project-row':'')+'"><td><button class="text-action" data-preview-project="'+esc(p.id)+'">'+esc(p.name)+'</button><small>'+esc([p.establishment,p.sector].filter(Boolean).join(' · '))+'</small></td><td>'+tag(statusLabel(p.status),p.status==='Bloqueado'?'risk':p.status==='Esperando tercero'?'wait':'neutral')+'<small>'+esc(p.stage||'Sin etapa')+'</small></td><td class="next-action-cell">'+esc(p.nextAction||'Definir próximo paso')+'</td><td>'+esc(day(nextDay(p)))+'<small>'+attention(p)+'</small></td><td class="last-move-cell">'+esc((p.followUpLog||[]).at(-1)?.note||p.lastMove||'Sin novedad registrada')+'<small>'+esc(stamp(p.updatedAt))+'</small></td></tr>').join('')+'</tbody></table>'+(!rows.length?'<div class="suite-empty">No hay proyectos en esta selección.</div>':'')+'<div class="table-foot">'+rows.length+' proyectos · seleccioná una fila para ver el detalle</div></div>';}
  function portfolio(){
    const data=tracker(),m=ctx.metrics(),rows=data.projects.filter(p=>{const match=[p.name,p.establishment,p.sector,p.nextAction,p.waitingFor].join(' ').toLowerCase().includes(query.toLowerCase());return match&&(filter==='Todos'||filter==='Activos'&&TBSuiteCore.active(p)||filter==='Esperando respuesta'&&p.status==='Esperando tercero'||filter==='Con vencimientos'&&pending(p).overdue||filter==='Finalizados'&&p.status==='Finalizado');});
    if(!rows.some(p=>p.id===previewId))previewId=previewClosed?null:rows[0]?.id||null;
    const selected=data.projects.find(p=>p.id===previewId),tasks=ctx.allTasks().filter(t=>t.status!=='Cumplido');
    const cards=[['Proyectos activos',m.active,'En seguimiento','Activos'],['Pendientes',m.pending,'Tareas e hitos','Tareas'],['Vencidos',m.overdue,'Requieren seguimiento','Con vencimientos'],['Esperando respuesta',m.waiting,'Dependencias de terceros','Esperando respuesta']].map(([label,value,note,key])=>'<button class="card suite-stat unified-metric '+(filter===key?'metric-selected':'')+'" data-project-filter="'+key+'" aria-pressed="'+(filter===key)+'" title="'+(key==='Tareas'?'Abrir tareas pendientes':'Filtrar '+label.toLowerCase())+'"><span>'+label+'</span><strong>'+value+'</strong><small>'+note+'</small></button>').join('');
    const queue='<section class="card unified-queue"><div class="suite-head"><h3>Primero para hoy</h3><div class="actions"><button id="unifiedNewTask">+ Tarea</button><button id="unifiedAllTasks" class="text-action">Ver pendientes →</button></div></div>'+tasks.slice(0,3).map(t=>'<div class="ops-item"><div><button class="text-action" data-edit-task="'+esc(t.id)+'" data-task-project="'+esc(t.projectId)+'">'+esc(t.title)+'</button><small>'+esc(t.project)+' · '+esc(t.owner||'Sin responsable')+'</small></div>'+tag(t.overdue?'Vencida':t.dueDate?day(t.dueDate):t.status,t.overdue?'risk':'neutral')+'</div>').join('')+(!tasks.length?'<div class="suite-empty">Sin tareas pendientes registradas.</div>':'')+'</section>';
    $('projectPortfolio').innerHTML=(window.TBDesignPreview?'<div class="preview-banner">Versión de prueba · datos de demostración · nube desactivada</div>':'')+'<div class="suite-head"><div><div class="suite-label">GESTIÓN / PROYECTOS</div><h2>Tu cartera, en un solo lugar.</h2><p>Qué sigue, qué está detenido y cuándo volver a actuar.</p></div><button id="flowNewProject" class="primary">+ Proyecto</button></div><div class="suite-grid unified-metrics">'+cards+'</div><div class="unified-project-layout '+(selected?'with-panel':'')+'"><div class="unified-project-main"><section class="card unified-project-list"><div class="suite-head"><h3>Proyectos en seguimiento</h3><small>'+rows.length+' proyectos</small></div><div class="suite-toolbar"><label class="grow">Buscar<input id="flowSearch" placeholder="Proyecto, establecimiento o próxima acción" value="'+esc(query)+'"></label><label>Mostrar<select id="flowFilter">'+['Activos','Esperando respuesta','Con vencimientos','Finalizados','Todos'].map(s=>option(s,s,filter)).join('')+'</select></label></div>'+table(rows)+'</section>'+queue+'</div>'+(selected?'<aside class="card unified-project-panel" aria-label="Proyecto seleccionado">'+preview(selected)+'</aside>':'')+'</div>';
    const refresh=()=>{portfolio();bind();};
    $('flowNewProject').onclick=()=>edit();$('flowFilter').onchange=e=>{filter=e.target.value;previewClosed=false;refresh();};$('flowSearch').oninput=e=>{query=e.target.value;const pos=e.target.selectionStart;refresh();$('flowSearch').focus();$('flowSearch').setSelectionRange(pos,pos);};
    document.querySelectorAll('[data-project-filter]').forEach(b=>b.onclick=()=>{if(b.dataset.projectFilter==='Tareas'){ctx.openPending();return;}filter=filter===b.dataset.projectFilter?'Todos':b.dataset.projectFilter;previewClosed=false;refresh();});
    document.querySelectorAll('[data-preview-row]').forEach(row=>row.onclick=e=>{if(e.target.closest('button'))return;previewId=row.dataset.previewRow;previewClosed=false;previewTab='Resumen';refresh();});
    document.querySelectorAll('[data-preview-project]').forEach(b=>b.onclick=()=>{previewId=b.dataset.previewProject;previewClosed=false;previewTab='Resumen';refresh();});
    document.querySelectorAll('[data-preview-tab]').forEach(b=>b.onclick=()=>{previewTab=b.dataset.previewTab;refresh();});
    $('closeProjectPreview')?.addEventListener('click',()=>{previewId=null;previewClosed=true;refresh();});
    $('unifiedNewTask').onclick=()=>API.editMilestone();$('unifiedAllTasks').onclick=()=>ctx.openPending();
  }
  function preview(p){
    const latest=(p.followUpLog||[]).at(-1),records=(p.followUpLog||[]).slice().reverse();let content='';
    if(previewTab==='Resumen')content='<section class="preview-section"><div class="suite-label">PRÓXIMA ACCIÓN</div><h3>'+esc(p.nextAction||'Definir próximo paso')+'</h3><p>Seguimiento: '+esc(day(nextDay(p)))+'</p></section><section class="preview-section"><div class="suite-label">ESPERAS / BLOQUEOS</div><p>'+esc(p.status==='Esperando tercero'?wait(p):p.blocker||'Sin bloqueos registrados')+'</p></section><section class="preview-section"><div class="suite-label">ÚLTIMA NOVEDAD</div><p>'+esc(latest?.note||p.lastMove||'Sin novedad registrada')+'</p><small>'+esc(stamp(latest?.at||p.updatedAt))+'</small></section>';
    if(previewTab==='Historial')content=records.slice(0,4).map(r=>'<section class="preview-section"><small>'+esc(stamp(r.at))+' · '+esc(r.actor)+'</small><p>'+esc(r.note||'Datos del seguimiento actualizados')+'</p></section>').join('')||'<p>Las modificaciones anteriores están en el seguimiento completo.</p>';
    if(previewTab==='Documentos')content=tracker().documents.filter(d=>d.projectId===p.id).map(d=>'<button class="preview-document" data-preview-doc="'+esc(d.id)+'"><strong>'+esc(d.title)+'</strong><small>'+esc(d.revision||'Sin revisión')+' · '+esc(d.status||'Borrador')+'</small></button>').join('')||'<p>Sin documentos vinculados.</p>';
    return '<div class="suite-head"><div class="suite-label">PROYECTO SELECCIONADO</div><button id="closeProjectPreview" aria-label="Cerrar panel del proyecto">×</button></div><h2>'+esc(p.name)+'</h2><p>'+esc([p.establishment,p.sector].filter(Boolean).join(' · '))+'</p>'+tag(statusLabel(p.status),p.status==='Esperando tercero'?'wait':p.status==='Bloqueado'?'risk':'neutral')+'<nav class="preview-tabs" aria-label="Vista rápida del proyecto">'+['Resumen','Historial','Documentos'].map(t=>'<button data-preview-tab="'+t+'" aria-pressed="'+(previewTab===t)+'" class="'+(previewTab===t?'active':'')+'">'+t+'</button>').join('')+'</nav>'+content+'<button class="primary" data-quick-project="'+esc(p.id)+'">Registrar avance</button><button class="text-action" data-open-project="'+esc(p.id)+'">Ver detalle completo →</button>';
  }
  function history(p){const records=(p.followUpLog||[]).slice().reverse();return '<section class="card flow-history"><div class="suite-head"><div><h3>Historial del proyecto</h3><p>Novedades y cambios registrados. Consultá también las modificaciones anteriores al final del historial.</p></div></div>'+records.map(r=>'<article class="history-entry"><span class="history-dot"></span><div><div class="history-meta"><b>'+esc(r.actor)+'</b><time>'+esc(stamp(r.at))+'</time></div>'+(r.note?'<p class="history-note">'+esc(r.note)+'</p>':'<p class="history-note">Datos del seguimiento actualizados</p>')+(r.document?'<button class="text-action" data-preview-doc="'+esc(r.document.id)+'">Documento: '+esc(r.document.title)+' · '+esc(r.document.revision)+'</button>':'')+(r.changes?.length?'<details class="trace-details"><summary>Ver '+r.changes.length+' cambios · antes / después</summary><div class="technical-table"><table><thead><tr><th>Dato</th><th>Antes</th><th>Después</th></tr></thead><tbody>'+r.changes.map(c=>'<tr><td>'+esc(c.label||c.field)+'</td><td>'+esc(c.before||'—')+'</td><td>'+esc(c.after||'—')+'</td></tr>').join('')+'</tbody></table></div></details>':'')+'</div></article>').join('')+(!records.length?'<div class="suite-empty">Las próximas actualizaciones quedarán registradas con operador, fecha y cambios.</div>':'')+'<details class="previous-activity"><summary>Ver actividad anterior y otros movimientos</summary>'+feed(p.id)+'</details></section>';}
  function workspace(nextTab){if(nextTab)tab=['Resumen','Seguimiento','Documentos'].includes(nextTab)?nextTab:'Seguimiento';const p=tracker().projects.find(p=>p.id===API.selectedId());if(!p){$('projectWorkspace').innerHTML='<div class="suite-empty">Seleccioná un proyecto.</div>';return;}const t=pending(p),latest=(p.followUpLog||[]).at(-1);let content='';
    if(tab==='Resumen')content='<div class="project-overview-grid"><section class="card flow-next"><div class="suite-label">PRÓXIMO PASO</div><h3>'+esc(p.nextAction||'Definí la próxima acción')+'</h3><div class="actions">'+tag(p.owner||'Sin responsable','neutral')+tag(day(nextDay(p)),nextDay(p)&&nextDay(p)<date()?'risk':'neutral')+'</div><button data-quick-project="'+esc(p.id)+'" class="primary">Actualizar proyecto</button></section><section class="card"><div class="suite-label">ESPERAS Y BLOQUEOS</div>'+(p.status==='Esperando tercero'?'<h3>'+esc(wait(p))+'</h3><p>'+esc((p.waitingSince||meta(p.id).waitingSince)?'Esperando desde '+day(p.waitingSince||meta(p.id).waitingSince):'Fecha de inicio sin registrar')+'</p>':p.blocker?'<h3>'+esc(p.blocker)+'</h3>':'<h3>Sin bloqueos registrados</h3><p>Registrá una espera cuando dependas de una respuesta.</p>')+'</section><section class="card"><div class="suite-label">ÚLTIMO MOVIMIENTO</div><h3>'+esc(latest?.note||p.lastMove||'Todavía no se registraron novedades')+'</h3><p>'+esc(stamp(latest?.at||p.updatedAt))+'</p>'+(latest?'<small>'+esc(latest.actor)+'</small>':'')+'<button id="flowHistory" class="text-action">Ver historial →</button></section></div><section class="card project-brief"><div><div class="suite-label">ALCANCE DEL TRABAJO</div><p>'+esc(p.scope||p.notes||'Agregá una descripción breve de lo que hay que resolver.')+'</p></div><details><summary>Datos del proyecto</summary><dl><dt>Responsable</dt><dd>'+esc(p.owner||'Sin definir')+'</dd><dt>Fecha objetivo</dt><dd>'+esc(day(p.targetDate))+'</dd><dt>Expediente</dt><dd>'+esc(p.expediente||'Sin referencia')+'</dd></dl></details></section><div class="suite-head"><div><h3>Pendientes del proyecto</h3><p>'+t.total+' pendientes'+(t.overdue?' · '+t.overdue+' vencidos':'')+'</p></div><button id="flowTasks">Ver seguimiento →</button></div>'+tasksHtml(p.id,true);
    if(tab==='Seguimiento')content='<div class="suite-head"><div><h3>Pendientes e hitos</h3><p>Los mismos registros que ves en Inicio y Tareas.</p></div><button id="flowNewTask" class="primary">+ Tarea / hito</button></div>'+tasksHtml(p.id,false)+history(p);
    if(tab==='Documentos')content=documentsHtml(p.id);
    $('projectWorkspace').innerHTML='<div class="suite-head"><button id="flowBack" class="text-action">← Proyectos</button><div class="actions"><button data-edit-project="'+esc(p.id)+'">Editar ficha</button><button data-quick-project="'+esc(p.id)+'" class="primary">Actualizar proyecto</button></div></div><div class="workspace-hero"><div class="suite-label">'+esc([p.establishment,p.sector].filter(Boolean).join(' / ')||'PROYECTO')+'</div><h2>'+esc(p.name)+'</h2><div class="actions">'+tag(p.stage||'Etapa sin definir','neutral')+tag(statusLabel(p.status),p.status==='Bloqueado'?'risk':p.status==='Esperando tercero'?'wait':'neutral')+'</div></div><nav class="workspace-tabs" aria-label="Secciones del proyecto">'+['Resumen','Seguimiento','Documentos'].map(s=>'<button data-flow-tab="'+s+'" class="'+(tab===s?'active':'')+'" aria-selected="'+(tab===s)+'">'+s+'</button>').join('')+'</nav><div class="workspace-body">'+content+'</div>';
    $('flowBack').onclick=()=>API.navigate('projects');$('flowHistory')?.addEventListener('click',()=>{workspace('Seguimiento');bind();});$('flowTasks')?.addEventListener('click',()=>{workspace('Seguimiento');bind();});$('flowNewTask')?.addEventListener('click',()=>API.editMilestone());$('flowNewDocument')?.addEventListener('click',()=>API.editDocument());document.querySelectorAll('[data-flow-tab]').forEach(b=>b.onclick=()=>{workspace(b.dataset.flowTab);bind();});
  }
  function protect(d,form){const original=new FormData(form);const baseline=JSON.stringify([...original]);let saving=false;const dirty=()=>JSON.stringify([...new FormData(form)])!==baseline;const close=()=>{if(!saving&&dirty()&&!confirm('Tenés cambios sin guardar. ¿Cerrar esta actualización?'))return;d.close();};$('closeSuiteDialog').onclick=close;d.oncancel=e=>{e.preventDefault();close();};form.querySelector('[data-cancel-flow]').onclick=close;form.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();form.requestSubmit();}};return {saved:()=>{saving=true;d.close();d.oncancel=null;}};}
  function quick(id){const p=tracker().projects.find(p=>p.id===id);if(!p)return;const docs=tracker().documents.filter(d=>d.projectId===id),expectedVersion=p.updatedAt||'';const d=dialog('Actualizar proyecto','<form id="quickProjectForm" class="suite-modal-grid flow-form"><p class="wide form-context">'+esc(p.name)+' · sólo cambiá lo necesario</p><label class="wide">Qué pasó<textarea name="note" maxlength="3000" placeholder="Ej.: recibí la propuesta del proveedor y envié observaciones." rows="3"></textarea></label><label>Estado actual<select name="status">'+statuses(p.status)+'</select></label><label>Etapa<select name="stage">'+stages(p.stage)+'</select></label><label class="wide">Próxima acción<input name="nextAction" maxlength="500" value="'+esc(p.nextAction||'')+'" placeholder="Qué hay que hacer para avanzar"></label><label>Fecha de seguimiento<input name="nextDueDate" type="date" value="'+esc(nextDay(p))+'"></label><label id="waitingField">Esperando a quién / qué<input name="waitingFor" maxlength="500" value="'+esc(p.waitingFor|| (p.status==='Esperando tercero'?p.blocker||'':''))+'" placeholder="Proveedor, cliente o información pendiente"></label><label class="wide" id="blockingField">Qué impide avanzar<input name="blocker" maxlength="1000" value="'+esc(p.blocker||'')+'"></label><details class="wide optional-document"><summary>Relacionar un documento · opcional</summary><label>Documento<select name="documentId"><option value="">Sin documento relacionado</option>'+docs.map(x=>option(x.id,x.title+' · '+(x.revision||'Sin revisión'),'')).join('')+'</select></label></details><p id="quickError" class="wide inline-error" role="alert" hidden></p><div class="wide flow-form-footer"><small>Registro con fecha y operador · Ctrl + Enter para guardar</small><div class="actions"><button type="button" data-cancel-flow>Cancelar</button><button class="primary" type="submit">Guardar actualización</button></div></div></form>');const form=$('quickProjectForm'),close=protect(d,form),show=()=>{$('waitingField').hidden=form.elements.status.value!=='Esperando tercero';$('blockingField').hidden=form.elements.status.value!=='Bloqueado'&&!p.blocker;};show();form.elements.status.onchange=show;form.elements.note.focus();
    form.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));try{const now=new Date().toISOString();API.mutate(data=>{const index=data.projects.findIndex(x=>x.id===id);if(index<0)throw Error('El proyecto ya no está disponible.');data.projects[index]=core.prepare({...data.projects[index],waitingSince:data.projects[index].waitingSince||meta(id).waitingSince||''},{...values,today:date()},{actor:actor(),at:now,id:crypto.randomUUID(),documents:data.documents,expectedVersion});});close.saved();workspace();bind();toast('Actualización guardada localmente. El estado de Drive se confirma en la barra superior.');}catch(error){$('quickError').textContent=error.message;$('quickError').hidden=false;}};
  }
  function edit(id){const p=tracker().projects.find(p=>p.id===id)||{},expected=p.updatedAt||'';const d=dialog(id?'Editar ficha del proyecto':'Nuevo proyecto','<form id="simpleProjectForm" class="suite-modal-grid flow-form"><label class="wide">Nombre del proyecto<input name="name" maxlength="300" value="'+esc(p.name||'')+'" required placeholder="Ej.: Reparación de colector"></label><label>Establecimiento<input name="establishment" maxlength="300" value="'+esc(p.establishment||'')+'" required></label><label>Sector<input name="sector" maxlength="300" value="'+esc(p.sector||'')+'"></label><label class="wide">Alcance del trabajo<textarea name="scope" maxlength="3000" required placeholder="Qué hay que resolver">'+esc(p.scope||p.notes||'')+'</textarea></label><details class="wide optional-document"><summary>Responsable y referencias · opcional</summary><div class="suite-modal-grid"><label>Responsable<input name="owner" value="'+esc(p.owner||actor())+'"></label><label>Fecha objetivo del proyecto<input name="targetDate" type="date" value="'+esc(p.targetDate||'')+'"></label><label class="wide">Expediente / referencia<input name="expediente" value="'+esc(p.expediente||'')+'"></label></div></details><p id="simpleError" class="wide inline-error" role="alert" hidden></p><div class="wide flow-form-footer"><small>Los demás datos se completan durante el seguimiento.</small><div class="actions"><button type="button" data-cancel-flow>Cancelar</button><button type="submit" class="primary">Guardar proyecto</button></div></div></form>');const form=$('simpleProjectForm'),close=protect(d,form);form.elements.name.focus();form.onsubmit=e=>{e.preventDefault();try{const values=Object.fromEntries(new FormData(form));for(const field of ['name','establishment','scope'])if(!values[field].trim())throw Error('Completá el nombre, establecimiento y alcance.');const now=new Date().toISOString();let savedId=id;API.mutate(data=>{if(id){const old=data.projects.find(x=>x.id===id);if(!old)throw Error('El proyecto ya no existe.');if((old.updatedAt||'')!==expected)throw Error('El proyecto cambió. Cerrá esta ventana y revisá sus datos.');Object.assign(old,values,{updatedAt:now});}else{savedId=crypto.randomUUID();data.projects.unshift({...values,id:savedId,stage:'Idea',status:'Activo',nextAction:'',nextDueDate:'',createdAt:now,updatedAt:now});}});close.saved();tab='Resumen';API.select(savedId);toast('Proyecto guardado.');}catch(error){$('simpleError').textContent=error.message;$('simpleError').hidden=false;}};}
  return {portfolio,workspace,table,quick,edit,statusLabel};
};
