window.TBReports=function(ctx){
 'use strict';const $=id=>document.getElementById(id),{esc}=ctx;
 const fmt=v=>String(v??'');
 function open(){
  const today=ctx.date(),saved=ctx.preferences(),defaults={from:today.slice(0,8)+'01',to:today,recipient:'',recipientRole:'',signer:'Joel Fernadez Badi',signerRole:'Proyectos Termomecanicos',priority:'',projectId:''},prefs={...defaults,...saved};if(!TBReportCore.valid(prefs.to)||prefs.to>today)prefs.to=today;
  ctx.dialog('Informe ejecutivo en Word','<form id="reportForm" class="suite-modal-grid report-form"><p class="wide">Tu plantilla institucional se completa con la cartera actual, las novedades y los cierres del período. La vista previa informa qué datos faltan.</p><label>Desde<input name="from" type="date" required max="'+today+'" value="'+esc(prefs.from)+'"></label><label>Hasta<input name="to" type="date" required max="'+today+'" value="'+esc(prefs.to)+'"></label><label class="wide">Proyectos incluidos<select name="projectId"><option value="">Toda la cartera</option>'+ctx.tracker().projects.map(p=>'<option value="'+esc(p.id)+'" '+(prefs.projectId===p.id?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></label><label>Destinatario<input name="recipient" maxlength="200" required value="'+esc(prefs.recipient)+'" placeholder="Nombre de quien recibe el informe"></label><label>Cargo del destinatario<input name="recipientRole" maxlength="200" required value="'+esc(prefs.recipientRole)+'"></label><label>Firmante<input name="signer" maxlength="200" required value="'+esc(prefs.signer)+'"></label><label>Cargo del firmante<input name="signerRole" maxlength="200" required value="'+esc(prefs.signerRole)+'"></label><label class="wide">Prioridad del próximo período<textarea name="priority" maxlength="2000" rows="2" placeholder="Se propone a partir de las próximas acciones registradas">'+esc(prefs.priority)+'</textarea></label><div class="wide actions"><button id="reviewReport" type="button">Revisar datos del informe</button><button id="generateWordReport" class="primary" type="submit">Descargar Word</button></div><p id="reportError" class="wide inline-error" role="alert" hidden></p><div id="reportPreview" class="wide" aria-live="polite"></div></form>');
  const form=$('reportForm'),values=()=>({...Object.fromEntries(new FormData(form)),issued:ctx.date()}),error=e=>{$('reportError').textContent=e.message;$('reportError').hidden=false;};let busy=false;
  const model=()=>TBReportCore.build(ctx.tracker(),ctx.workflow(),ctx.activityRows(),values());
  const save=()=>ctx.savePreferences(Object.fromEntries(new FormData(form)));
  function preview(){try{$('reportError').hidden=true;const m=model();save();if(!form.elements.priority.value&&m.suggested)form.elements.priority.value=m.suggested;
   const totals=m.scalars,keys=[['Activos','TOTAL_ACTIVOS'],['En obra','TOTAL_EN_OBRA'],['Aprobación / contratación','TOTAL_APROBACION_CONTRATACION'],['Esperando terceros','TOTAL_ESPERANDO_TERCEROS'],['Acciones vencidas','TOTAL_VENCIDOS'],['Finalizados en el período','TOTAL_FINALIZADOS_PERIODO']];
   $('reportPreview').innerHTML='<p class="data-note">'+m.projectCount+' proyectos incluidos. Estado actual al '+TBReportCore.day(m.issued)+'. Novedades del '+TBReportCore.day(m.from)+' al '+TBReportCore.day(m.to)+'.</p><div class="technical-table"><table><thead><tr><th>Indicador</th><th>Valor</th></tr></thead><tbody>'+keys.map(([k,v])=>'<tr><td>'+k+'</td><td>'+totals[v]+'</td></tr>').join('')+'</tbody></table></div><h3>'+ (m.warnings.length?m.warnings.length+' datos por completar':'Datos disponibles para el informe')+'</h3>'+(m.warnings.length?'<p>Podés completar la ficha o descargar el informe con estos campos marcados “Sin registrar”. Los cierres sin fecha no se asignan a un período.</p>'+m.warnings.map(w=>'<div class="report-warning"><span><b>'+esc(w.project)+'</b><small>'+esc(w.field)+'</small></span><button type="button" data-report-edit="'+esc(w.projectId)+'">Completar ficha</button></div>').join(''):'<p>Los campos específicos de los proyectos están disponibles.</p>')+'<details><summary>Ver contenido de las ocho secciones</summary>'+[['DEC','Decisiones e intervenciones'],['OBRA','Obras en ejecución'],['AP','Aprobación, cotización o contratación'],['DES','Proyectos en desarrollo'],['FIN','Finalizados en el período']].map(([key,title])=>'<h4>'+title+' · '+m.tables[key].length+'</h4>'+m.tables[key].map(row=>'<p>'+Object.values(row).map(esc).join(' · ')+'</p>').join('')).join('')+'<h4>Cambios del período · '+m.changes.length+'</h4>'+m.changes.map(c=>'<p>'+esc(c)+'</p>').join('')+'<h4>Consideraciones finales</h4><p>'+esc(form.elements.priority.value||'Sin registrar')+'</p></details>';
   document.querySelectorAll('[data-report-edit]').forEach(b=>b.onclick=()=>{save();ctx.editProject(b.dataset.reportEdit);});return m;
  }catch(e){error(e);return null;}}
  $('reviewReport').onclick=preview;
  form.onsubmit=async e=>{e.preventDefault();if(busy)return;if(!form.reportValidity())return;busy=true;const button=$('generateWordReport');button.disabled=true;button.textContent='Generando Word…';try{if(!preview())return;const m=model();save();const response=await fetch('reports/template-hvac.docx',{credentials:'same-origin',cache:'no-cache'});if(!response.ok)throw Error('No se pudo cargar la plantilla Word ('+response.status+').');const blob=await TBReportDocx.generate(await response.arrayBuffer(),m),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='Informe_HVAC_'+m.from+'_'+m.to+'.docx';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);ctx.record('Informe Word generado','',m.projectCount+' proyectos · '+m.from+' al '+m.to+' · '+m.warnings.length+' datos pendientes');ctx.toast('Informe Word generado con tu plantilla.');}catch(e){error(e);}finally{busy=false;button.disabled=false;button.textContent='Descargar Word';}};
  preview();
 }
 return {open};
};
