(() => {
  'use strict';
  const E=TBEngineering,C=TBSuiteCore,API=TBTracker,KEY='thermabot.suite.v1',LIB='thermabot.workspace.v1',BAL='thermabot.proyectos.v1';
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=(key,fallback)=>{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;};
  const date=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
  const num=v=>Number(v||0).toLocaleString('es-AR',{maximumFractionDigits:2});
  const uid=()=>crypto.randomUUID(),empty=t=>'<div class="suite-empty">'+esc(t)+'</div>';
  const tag=(text,type='')=>'<span class="tag '+type+'">'+esc(text||'Sin definir')+'</span>';
  const opt=(values,selected)=>values.map(x=>'<option '+(x===selected?'selected':'')+'>'+esc(x)+'</option>').join('');
  let taskMode='list',taskState='',taskOnlyPending=false,taskOnlyOverdue=false,controlKind='Todos';
  let suite,previous,projectTab='Resumen',chartFilter='',taskProject='',taskQuery='',boardMode='projects',portfolioQuery='',portfolioMode='all',renderTimer,backupTimer,toastTimer,db=null,paletteIndex=0,paletteRows=[],moduleProject='',activeBalances={calculator:null,pressure:null},calculationActivityAt={};
  const FLOW=TBProjectFlow({API,tracker,meta,report:()=>REPORT.open(),workflow:()=>suite.projects,headings:()=>({title:suite.preferences.portfolioTitle||'Proyectos',subtitle:suite.preferences.portfolioSubtitle||'Gestión de informes'}),saveHeading:(key,value)=>{suite.preferences[key==='title'?'portfolioTitle':'portfolioSubtitle']=value;activity('Título de la cartera actualizado','',value);},activity,dialog,toast,esc,tag,date,bind,metrics:engineeringMetrics,openPending:()=>{taskOnlyPending=true;taskState='';taskProject='';taskQuery='';taskOnlyOverdue=false;API.navigate('tasks');renderTasksPage();bind();},allTasks:()=>C.tasks(tracker(),date(),suite.projects),actor:()=>suite?.preferences.actor||'Operador',feed,
    tasksHtml:(id,short)=>taskTable(C.tasks(tracker(),date(),suite.projects).filter(t=>t.projectId===id&&(!short||t.status!=='Cumplido')).slice(0,short?5:10000),true),
    documentsHtml:id=>'<div class="suite-head"><div><h3>Documentos del proyecto</h3><p>Revisión y estado técnico. Guardar un archivo no implica aprobarlo.</p></div><button id="flowNewDocument" class="primary">+ Documento</button></div><div class="technical-table"><table><thead><tr><th>Documento</th><th>Tipo</th><th>Revisión</th><th>Estado</th><th></th></tr></thead><tbody>'+tracker().documents.filter(d=>d.projectId===id).map(d=>'<tr><td><button class="text-action" data-preview-doc="'+esc(d.id)+'">'+esc(d.title)+'</button></td><td>'+esc(d.type||'—')+'</td><td>'+esc(d.revision||'—')+'</td><td>'+tag(d.status||'Borrador',d.status==='Aprobado'?'':'neutral')+'</td><td><div class="actions"><button data-preview-doc="'+esc(d.id)+'">Abrir</button><button data-edit-doc="'+esc(d.id)+'">Editar</button></div></td></tr>').join('')+'</tbody></table></div>'+(tracker().documents.some(d=>d.projectId===id)?'':empty('Vinculá planos, pliegos, memorias e informes desde Drive.'))
  });
  const REPORT=TBReports({esc,tracker,date,workflow:()=>suite.projects,activityRows:()=>suite.activity,preferences:()=>suite.preferences.report||{},savePreferences:p=>{suite.preferences.report=p;saveSuite();},dialog,editProject:id=>FLOW.edit(id),record:activity,toast});
  function initState(){
    suite=read(KEY,{schema:1,projects:{},activity:[],preferences:{actor:'Usuario de este navegador',theme:'light'}});
    if(!suite.projects||!Array.isArray(suite.activity)||!suite.preferences)throw Error('No se pudo leer la configuración de trabajo. Exportá una copia antes de modificarla.');
  }
  function saveSuite(){const old=localStorage.getItem(KEY);if(old)localStorage.setItem(KEY+'.previous',old);suite.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(suite));scheduleBackup();}
  function meta(id){return suite.projects[id]||(suite.projects[id]={finance:{currency:'ARS',lines:[]},source:'Sin definir',quoteOutcome:'Pendiente'});}
  function activity(title,projectId='',detail='',changes=[]){
    suite.activity.push({id:uid(),title,projectId,detail,changes,actor:suite.preferences.actor||'Usuario de este navegador',at:new Date().toISOString()});
    saveSuite();
  }
  function toast(text){let el=$('suiteToast');if(!el){el=document.createElement('div');el.id='suiteToast';el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000);}
  function guard(fn){try{const r=fn();if(r?.catch)r.catch(e=>toast(e.message));}catch(e){toast(e.message);}}
  function tracker(){return API.snapshot();}
  function balances(){const data=read(BAL,[]);if(!Array.isArray(data))throw Error('El archivo de cálculos no tiene el formato esperado.');return data;}
  function library(){return read(LIB,{schema:1,links:{},audits:[]});}
  function selected(){return tracker().projects.find(p=>p.id===API.selectedId());}
  function projectOptions(current,allowEmpty=true){return (allowEmpty?'<option value="">Sin asignar</option>':'')+tracker().projects.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===current?'selected':'')+'>'+esc(p.name)+'</option>').join('');}
  function linked(id){const lib=library();return balances().filter(b=>lib.links[b.id]===id||tracker().projects.some(p=>p.id===id&&p.sourceBalanceId===b.id));}
  function link(balanceId,projectId){const lib=library();const old=localStorage.getItem(LIB);if(old)localStorage.setItem('thermabot.workspace.previous.v1',old);lib.links[balanceId]=projectId;lib.updatedAt=new Date().toISOString();localStorage.setItem(LIB,JSON.stringify(lib));activity('Cálculo vinculado al proyecto',projectId,balances().find(b=>b.id===balanceId)?.nombre||balanceId);window.dispatchEvent(new Event('thermabot:data'));}
  function openProject(id,tab='Resumen'){projectTab=['Resumen','Seguimiento','Documentos'].includes(tab)?tab:'Seguimiento';API.select(id);FLOW.workspace(projectTab);bind();}
  function setModule(view,balanceId,projectId,newBalance=false){
    if(view!=='calculator'){API.navigate('dashboard');return;}
    moduleProject=projectId||API.selectedId()||'';
    const frame=document.querySelector('#view-'+view+' iframe');
    const id=balanceId||(view==='calculator'?linked(moduleProject).find(b=>b.method==='quadri-v3')?.id:linked(moduleProject)[0]?.id);
    if(moduleProject&&API.selectedId()!==moduleProject)API.select(moduleProject);
    API.navigate(view);
    const url=(view==='calculator'?(balances().find(b=>b.id===id)?.method==='quadri-v3'||!id?'quadri/index.html':'index.html'):'pressure.html')+'?embedded=1&projectId='+encodeURIComponent(moduleProject)+(newBalance?'&newBalance='+encodeURIComponent(tracker().projects.find(p=>p.id===moduleProject)?.name||'Nuevo cálculo')+'&revision='+Date.now():id?'&balanceId='+encodeURIComponent(id):'');
    if(frame.getAttribute('src')!==url)frame.src=url;
    renderModule(view);
  }
  function captureChanges(){
    const current=tracker(),assigned=[];
    if(previous){
      for(const collection of ['projects','equipment','milestones','documents']){
        const before=new Map(previous[collection].map(x=>[x.id,x]));
        for(const row of current[collection]){
          const old=before.get(row.id);before.delete(row.id);const title=row.name||row.title||'Registro';
          if(collection==='equipment'&&row.projectId&&(!old||old.projectId!==row.projectId))assigned.push(row);
          if(!old)activity('Creado: '+title,collection==='projects'?row.id:row.projectId,({projects:'Proyecto',equipment:'Equipo',milestones:'Hito',documents:'Documento'})[collection]);
          else {const fields=Object.keys(row).filter(k=>!['updatedAt','createdAt','followUpLog'].includes(k)&&JSON.stringify(row[k])!==JSON.stringify(old[k]));
            if(fields.includes('status')){const pm=meta(collection==='projects'?row.id:row.projectId);if(collection==='projects'&&row.status==='Esperando tercero')pm.waitingSince=date();if(collection==='milestones'){pm.taskFacts=pm.taskFacts||{};pm.taskFacts[row.id]={...(pm.taskFacts[row.id]||{}),completedAt:row.status==='Cumplido'?new Date().toISOString():null};}}
            if(fields.length)activity('Actualizado: '+title,collection==='projects'?row.id:row.projectId,fields.map(k=>({status:'Estado',stage:'Etapa',progress:'Avance',nextAction:'Próxima acción',targetDate:'Fecha objetivo',dueDate:'Fecha',projectId:'Proyecto',blocker:'Bloqueo',notes:'Observaciones',driveUrl:'Enlace'})[k]||k).join(', '),fields.map(field=>({field,before:old[field]??'',after:row[field]??''})));
          }
          if(collection==='projects'&&row.stage==='Cotización'&&!meta(row.id).quotedAt){meta(row.id).quotedAt=new Date().toISOString();saveSuite();}
        }
        for(const old of before.values())activity('Eliminado: '+(old.name||old.title||'Registro'),collection==='projects'?old.id:old.projectId,collection);
      }
    }
    previous=current;
    if(assigned.length)queueMicrotask(()=>guard(()=>{
      let added=false;
      for(const equipment of assigned){const m=meta(equipment.projectId);m.finance=m.finance||{currency:'ARS',lines:[]};if(!m.finance.lines.some(l=>l.equipmentId===equipment.id)){m.finance.lines.push({id:uid(),title:equipment.name,type:'Costo',quantity:1,unitPrice:0,equipmentId:equipment.id,needsPrice:true});added=true;}}
      if(added){saveSuite();toast('Equipo vinculado: se creó su partida pendiente de precio y el hito de instalación.');}
      const missing=assigned.filter(eq=>!tracker().milestones.some(m=>m.projectId===eq.projectId&&m.notes==='Equipo: '+eq.id));
      if(missing.length)API.mutate(data=>missing.forEach(eq=>data.milestones.push({id:uid(),projectId:eq.projectId,title:'Instalación / puesta en servicio: '+eq.name,type:'Puesta en marcha',status:'Pendiente',dueDate:'',owner:data.projects.find(p=>p.id===eq.projectId)?.owner||'',notes:'Equipo: '+eq.id})));
    }));
    scheduleBackup();scheduleRender();
  }
  function stat(label,value,note,risk=''){return '<article class="card suite-stat '+risk+'"><span>'+label+'</span><strong>'+value+'</strong><small>'+note+'</small></article>';}
  function renderProjectBoard(rows){
    return '<div class="kanban" aria-label="Tablero de proyectos">'+['Activo','Esperando tercero','Bloqueado','Finalizado'].map(lane=>{
      const list=rows.filter(p=>C.projectLane(p)===lane);
      return '<section class="lane" data-board="project" data-lane="'+lane+'"><div class="lane-head"><i></i>'+esc(({Activo:'En marcha',Bloqueado:'Requiere atención',Finalizado:'Finalizados'})[lane]||lane)+'<small>'+list.length+'</small></div>'+list.map(p=>'<article class="board-card" draggable="true" data-drag-project="'+esc(p.id)+'">'+tag(p.establishment||'Proyecto')+'<h3><button class="open-project" data-open-project="'+esc(p.id)+'">'+esc(p.name)+'</button></h3><p>'+esc(p.stage||'Etapa sin definir')+' · '+esc(p.status)+'</p><div class="progress-line"><i style="width:'+Math.max(0,Math.min(100,Number(p.progress)||0))+'%"></i></div><div class="board-footer"><span>'+num(p.progress)+'% completado</span><span>'+esc(p.targetDate||'Sin fecha')+'</span></div><label class="subtle">Mover a<select data-project-status="'+esc(p.id)+'">'+opt(['Activo','En revisión','Esperando tercero','Bloqueado','Urgente','Finalizado','Suspendido'],p.status)+'</select></label></article>').join('')+(list.length?'':empty('Sin proyectos en este estado'))+'</section>';
    }).join('')+'</div>';
  }
  function renderTasks(data,projectId=''){
    const list=C.tasks(data,date(),suite.projects).filter(t=>(!projectId||t.projectId===projectId)&&(!taskQuery||[t.title,t.project,t.owner].join(' ').toLowerCase().includes(taskQuery.toLowerCase())));
    return '<div class="kanban tasks" aria-label="Tablero de tareas">'+['Pendiente','En curso','Esperando respuesta','Cumplido'].map(lane=>{const tasks=list.filter(t=>(t.status==='Cumplido'?'Cumplido':t.status==='En curso'?'En curso':t.status==='Esperando respuesta'?'Esperando respuesta':'Pendiente')===lane);return '<section class="lane" data-board="task" data-lane="'+lane+'"><div class="lane-head"><i></i>'+lane+'<small>'+tasks.length+'</small></div>'+tasks.map(t=>'<article class="board-card" draggable="true" data-drag-task="'+esc(t.id)+'">'+tag(t.overdue?'Vencido':t.kind==='next'?'Próxima acción':'Hito',t.overdue?'risk':'neutral')+'<h3><button class="edit-task" data-edit-task="'+esc(t.id)+'" data-task-project="'+esc(t.projectId)+'">'+esc(t.title)+'</button></h3><p>'+esc(t.project)+'</p><div class="board-footer"><span>'+esc(t.owner||'Sin responsable')+'</span><span>'+esc(t.dueDate||'Sin fecha')+'</span></div><label class="subtle">Estado<select data-task-status="'+esc(t.id)+'">'+opt(['Pendiente','En curso','Esperando respuesta','Cumplido'],lane)+'</select></label></article>').join('')+(tasks.length?'':empty('Sin tareas en este estado'))+'</section>';}).join('')+'</div>';
  }

  function engineeringMetrics(projectId=''){
    const data=tracker();return E.metrics(data,C.tasks(data,date(),suite.projects),suite.projects,date(),projectId);
  }
  function metricsHtml(m,compact=false){
    const main=[['Avance técnico',m.progress===null?'—':num(m.progress)+'%','Promedio declarado · activos','',m.progress],['Tareas pendientes',m.pending,'Acciones e hitos sin cumplir'],['Tareas vencidas',m.overdue,'Fecha límite anterior a hoy',m.overdue?'risk':''],['Restricciones abiertas',m.restrictions,'Registros + bloqueos de ficha',m.restrictions?'risk':''],['Entregables aprobados',m.approved+' / '+m.deliverables,'Documentos y entregables'],['Esperando respuesta',m.waiting,'Proyectos esperando terceros'],['Tiempo medio de espera',m.waitAverage===null?'—':num(m.waitAverage)+' d',m.waitCoverage+' de '+m.waiting+' con fecha de inicio'],['Salud '+(compact?'del proyecto':'de la cartera'),m.health,'Bloqueos, riesgos y vencimientos',m.health==='Crítica'?'risk':'']];
    const secondary=[['PPC semanal',m.ppc===null?'—':num(m.ppc)+'%',m.fulfilled+' / '+m.committed+' compromisos'],['WIP',m.wip,'Tareas en curso'],['Riesgos activos',m.risks,'Registro de riesgos'],['Cambios abiertos',m.changes,'Registro de cambios'],['Hitos próximos',m.upcoming.length,'Ventana de 21 días'],['Proyectos activos',m.active,'Excluye finalizados / suspendidos']];
    const card=([label,value,note,risk='',progress])=>'<article class="card suite-stat '+risk+'"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong><small>'+esc(note)+'</small>'+(progress!=null?'<div class="metric-line"><i style="width:'+progress+'%"></i></div>':'')+'</article>';
    return '<div class="engineering-metrics">'+main.map(card).join('')+'</div><div class="engineering-metrics secondary">'+secondary.map(card).join('')+'</div>';
  }
  function projectTable(list){return FLOW.table(list);}
  function renderDashboard(){ $('commandCenter').innerHTML=''; }
  function taskTable(list,contextProject=false){return '<div class="technical-table"><table><thead><tr><th>Tarea / hito</th>'+(contextProject?'':'<th>Proyecto</th>')+'<th>Responsable</th><th>Fecha límite</th><th>Estado</th><th></th></tr></thead><tbody>'+list.map(t=>'<tr class="'+(t.status==='Cumplido'?'row-done':'')+'"><td><div class="task-check"><input type="checkbox" data-complete-task="'+esc(t.id)+'" '+(t.status==='Cumplido'?'checked':'')+' aria-label="Completar '+esc(t.title)+'"><div><button class="text-action" data-edit-task="'+esc(t.id)+'" data-task-project="'+esc(t.projectId)+'">'+esc(t.title)+'</button><small>'+esc(t.kind==='next'?'Próxima acción':t.type||'Hito')+'</small></div></div></td>'+(contextProject?'':'<td><button class="text-action" data-open-project="'+esc(t.projectId)+'">'+esc(t.project)+'</button></td>')+'<td>'+esc(t.owner||'Sin asignar')+'</td><td>'+esc(t.dueDate?t.dueDate.split('-').reverse().join('/'):'Sin fecha')+(t.overdue?'<small>'+tag('Vencida','risk')+'</small>':'')+'</td><td><select class="status-edit" data-task-status="'+esc(t.id)+'" aria-label="Estado de '+esc(t.title)+'">'+opt(['Pendiente','En curso','Esperando respuesta','Cumplido'],t.status==='Cumplido'?'Cumplido':t.status==='En curso'?'En curso':t.status==='Esperando respuesta'?'Esperando respuesta':'Pendiente')+'</select></td><td><button data-edit-task="'+esc(t.id)+'" data-task-project="'+esc(t.projectId)+'" aria-label="Editar '+esc(t.title)+'">Editar</button></td></tr>').join('')+'</tbody></table>'+(!list.length?empty('No hay tareas en esta selección. Cambiá los filtros o agregá un hito.'):'')+'<div class="table-foot">'+list.length+' tareas en la selección</div></div>';}
  function renderTasksPage(){
    const data=tracker(),all=C.tasks(data,date(),suite.projects),m=engineeringMetrics();
    const list=all.filter(t=>(!taskOnlyPending||t.status!=='Cumplido')&&(!taskProject||t.projectId===taskProject)&&(!taskState||(t.status==='Vencido'?'Pendiente':t.status)===taskState)&&(!taskOnlyOverdue||t.overdue)&&(!taskQuery||[t.title,t.project,t.owner].join(' ').toLowerCase().includes(taskQuery.toLowerCase())));
    $('taskWorkspace').innerHTML='<div class="suite-head"><div><div class="suite-label">GESTIÓN / TAREAS</div><h2>Tareas</h2><p>Acciones e hitos de los proyectos activos. La misma cola que ves en Proyectos.</p></div><div class="actions"><div class="view-switch"><button id="taskListMode" class="'+(taskMode==='list'?'primary':'')+'">Lista</button><button id="taskBoardMode" class="'+(taskMode==='board'?'primary':'')+'">Tablero</button></div><button id="newOpsTask" class="primary">+ Tarea / hito</button></div></div><div class="suite-grid">'+stat('Pendientes',m.pending,'Acciones e hitos')+stat('Vencidas',m.overdue,'Requieren atención',m.overdue?'risk':'')+stat('En curso',m.wip,'Trabajo iniciado')+stat('En espera',all.filter(t=>t.status==='Esperando respuesta').length,'Respuesta pendiente')+'</div><div class="suite-toolbar"><label class="grow">Buscar tareas<input id="opsTaskQuery" value="'+esc(taskQuery)+'" placeholder="Tarea, proyecto o responsable"></label><label>Proyecto<select id="opsTaskProject">'+projectOptions(taskProject).replace('Sin asignar','Todos')+'</select></label><label>Estado<select id="opsTaskState"><option value="">Todos</option>'+opt(['Pendiente','En curso','Esperando respuesta','Cumplido'],taskState)+'</select></label><label><span><input type="checkbox" id="opsTaskPending" '+(taskOnlyPending?'checked':'')+'> Sólo pendientes</span></label><label><span><input type="checkbox" id="opsTaskOverdue" '+(taskOnlyOverdue?'checked':'')+'> Sólo vencidas</span></label></div>'+(taskMode==='list'?taskTable(list):renderTasks({...data,milestones:data.milestones.filter(m=>list.some(t=>t.id===m.id)),projects:data.projects.map(p=>({...p,nextAction:list.some(t=>t.id==='next:'+p.id)?p.nextAction:''}))},taskProject));
    const refresh=()=>{renderTasksPage();bind();};$('newOpsTask').onclick=()=>API.editMilestone();$('taskListMode').onclick=()=>{taskMode='list';refresh();};$('taskBoardMode').onclick=()=>{taskMode='board';refresh();};$('opsTaskProject').onchange=e=>{taskProject=e.target.value;refresh();};$('opsTaskState').onchange=e=>{taskState=e.target.value;refresh();};$('opsTaskPending').onchange=e=>{taskOnlyPending=e.target.checked;refresh();};$('opsTaskOverdue').onchange=e=>{taskOnlyOverdue=e.target.checked;refresh();};$('opsTaskQuery').oninput=e=>{taskQuery=e.target.value;const pos=e.target.selectionStart;refresh();$('opsTaskQuery').focus();$('opsTaskQuery').setSelectionRange(pos,pos);};
  }
  function controlHtml(p){const m=meta(p.id),rows=(m.controls||[]).filter(r=>controlKind==='Todos'||r.kind===controlKind);return '<div class="suite-head"><div><h3>Control de ingeniería</h3><p>Restricciones, riesgos, cambios y entregables del proyecto.</p></div><button id="newControl" class="primary">+ Registro</button></div><div class="suite-toolbar"><label>Tipo<select id="controlKind">'+opt(['Todos','Restricción','Riesgo','Cambio','Entregable'],controlKind)+'</select></label>'+(p.status==='Esperando tercero'?'<label>Esperando desde<input type="date" id="waitingSince" max="'+date()+'" value="'+esc(m.waitingSince||'')+'"></label><button id="saveWaiting">Guardar fecha de espera</button>':'')+'</div>'+(p.blocker?'<div class="health-rule"><b>Restricción de la ficha:</b> '+esc(p.blocker)+' <button data-edit-project="'+esc(p.id)+'">Editar ficha</button></div>':'')+'<div class="technical-table"><table><thead><tr><th>Tipo</th><th>Descripción</th><th>Responsable</th><th>Prioridad</th><th>Objetivo</th><th>Estado</th><th></th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+tag(r.kind,r.kind==='Riesgo'?'risk':'neutral')+'</td><td>'+esc(r.title)+'<small>'+esc(r.notes||'')+'</small></td><td>'+esc(r.owner||'Sin asignar')+'</td><td>'+tag(r.severity||'Media',r.severity==='Alta'?'risk':'neutral')+'</td><td>'+esc(r.dueDate||'—')+'</td><td>'+tag(r.status,E.open(r)?'wait':'')+'</td><td><button data-edit-control="'+esc(r.id)+'">Editar</button></td></tr>').join('')+'</tbody></table>'+(!rows.length?empty('Agregá registros para seguir restricciones, riesgos, cambios y entregables.'):'')+'</div><p class="data-note">La salud considera bloqueos, riesgos de prioridad alta y tareas vencidas. Los documentos aprobados también cuentan como entregables.</p>';}
  function controlEditor(p,id){const m=meta(p.id),old=(m.controls||[]).find(r=>r.id===id)||{};dialog(id?'Editar registro de control':'Nuevo registro de control','<form id="controlForm" class="suite-modal-grid"><label>Tipo<select name="kind">'+opt(['Restricción','Riesgo','Cambio','Entregable'],old.kind||'Restricción')+'</select></label><label>Estado<select name="status">'+opt(['Abierto','En revisión','Resuelto','Aprobado','Cerrado','Cancelado'],old.status||'Abierto')+'</select></label><label class="wide">Descripción<input name="title" maxlength="300" required value="'+esc(old.title||'')+'"></label><label>Responsable<input name="owner" value="'+esc(old.owner||p.owner||'')+'"></label><label>Prioridad<select name="severity">'+opt(['Baja','Media','Alta'],old.severity||'Media')+'</select></label><label>Fecha objetivo<input type="date" name="dueDate" value="'+esc(old.dueDate||'')+'"></label><label class="wide">Observaciones<textarea name="notes">'+esc(old.notes||'')+'</textarea></label><button class="primary wide">Guardar registro</button></form>');$('controlForm').onsubmit=e=>guard(()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(!f.title.trim())throw Error('Ingresá una descripción.');m.controls=m.controls||[];const record={...old,...f,title:f.title.trim(),id:old.id||uid(),createdAt:old.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)m.controls=m.controls.map(r=>r.id===id?record:r);else m.controls.push(record);activity((id?'Actualizado: ':'Creado: ')+record.kind,p.id,record.title);$('suiteDialog').close();render();});}


  function renderPortfolio(){FLOW.portfolio();}
  function renderWorkspace(){FLOW.workspace();}
  function financeHtml(p,m,f){return '<div class="suite-head"><div><h3>Presupuesto y resultado</h3><p>Moneda: '+esc(m.finance?.currency||'ARS')+' · Los ingresos representan cobros registrados.</p></div><div class="actions"><button id="addFinanceLine" class="primary">+ Partida</button></div></div><div class="suite-grid">'+stat('Presupuestado',num(f.quoted),m.finance?.currency||'ARS')+stat('Costos',num(f.cost),f.pendingPrices?f.pendingPrices+' partidas pendientes de precio':'Compras y ejecución')+stat('Ingresos',num(f.revenue),'Cobros registrados')+stat('Resultado',f.pendingPrices?'Parcial':num(f.profit),f.pendingPrices?'Completá los precios pendientes':f.margin===null?'Sin ingresos para calcular margen':num(f.margin)+'% de margen')+'</div><div class="card" style="margin-top:18px;overflow:auto"><table><thead><tr><th>Tipo</th><th>Concepto</th><th>Cantidad</th><th>Unitario</th><th>Total</th><th></th></tr></thead><tbody>'+(m.finance?.lines||[]).map(l=>'<tr><td>'+esc(l.type)+'</td><td>'+esc(l.title)+(l.needsPrice?' · Precio pendiente':'')+'</td><td>'+num(l.quantity)+'</td><td>'+(l.needsPrice?'—':num(l.unitPrice))+'</td><td>'+(l.needsPrice?'—':num(Number(l.quantity)*Number(l.unitPrice)))+'</td><td><button data-remove-finance="'+esc(l.id)+'">Eliminar</button></td></tr>').join('')+'</tbody></table>'+(!m.finance?.lines?.length?empty('Registrá partidas para conocer el presupuesto y el resultado.'):'' )+'</div><p class="subtle">Origen: '+esc(m.source||'Sin definir')+' · Cotización: '+esc(m.quoteOutcome||'Pendiente')+'. Estos datos se incluyen en la copia completa de la aplicación.</p>';}

  function equipmentList(list,inProject=false){return '<div class="technical-table"><table><thead><tr><th>Equipo</th><th>Modelo / capacidad</th><th>Proyecto</th><th>Ubicación</th><th>Estado</th><th>Proveedor</th><th></th></tr></thead><tbody>'+list.map(e=>'<tr><td><b>'+esc(e.name)+'</b><small>'+esc(e.tag||'')+'</small></td><td>'+esc(e.model||'—')+'<small>'+esc(e.capacity||'Sin capacidad registrada')+'</small></td><td>'+esc(tracker().projects.find(p=>p.id===e.projectId)?.name||'Sin asignar')+'</td><td>'+esc(e.location||'—')+'</td><td>'+tag(e.status||'A definir',e.status==='Fuera de servicio'?'risk':'neutral')+'</td><td>'+esc(e.supplier||'—')+'</td><td><div class="actions"><button data-edit-eq="'+esc(e.id)+'">Editar</button>'+(inProject?'<button data-equipment-cost="'+esc(e.id)+'">Costo / hito</button>':'<button data-assign-eq="'+esc(e.id)+'">Asignar</button>')+'</div></td></tr>').join('')+'</tbody></table>'+(list.length?'':empty('Todavía no hay equipos en esta selección.'))+'</div>';}

  function dialog(title,html){let d=$('suiteDialog');if(!d){d=document.createElement('dialog');d.id='suiteDialog';d.className='suite-dialog suite';document.body.append(d);}d.oncancel=null;d.innerHTML='<div class="dialog-head"><h2>'+esc(title)+'</h2><button id="closeSuiteDialog" aria-label="Cerrar">×</button></div>'+html;$('closeSuiteDialog').onclick=()=>d.close();if(!d.open)d.showModal();return d;}
  function financeLine(p,equipment=null){
    const d=dialog(equipment?'Costo e instalación del equipo':'Nueva partida','<form id="financeForm" class="suite-modal-grid"><label class="wide">Concepto<input name="title" required value="'+esc(equipment?.name||'')+'"></label><label>Tipo<select name="type">'+opt(['Presupuesto','Costo','Ingreso'],equipment?'Costo':'Presupuesto')+'</select></label><label>Cantidad<input name="quantity" type="number" min="0.01" step="any" value="1" required></label><label>Precio unitario<input name="unitPrice" type="number" min="0" step="any" required></label><label>Moneda<select name="currency">'+opt(['ARS','USD','EUR'],meta(p.id).finance?.currency||'ARS')+'</select></label>'+(equipment?'<label class="wide"><span><input name="createMilestone" type="checkbox" checked> Crear hito para instalación / puesta en servicio</span></label><label>Fecha del hito<input name="dueDate" type="date"></label>':'')+'<div class="wide suite-notice">Usá una sola moneda por proyecto. El total se calcula como cantidad × precio unitario.</div><button class="primary wide" type="submit">Guardar partida</button></form>');
    $('financeForm').onsubmit=e=>guard(()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const m=meta(p.id);m.finance=m.finance||{lines:[],currency:f.currency};if(m.finance.lines.length&&m.finance.currency!==f.currency)throw Error('El proyecto ya tiene partidas en '+m.finance.currency+'. Usá esa moneda para mantener los totales coherentes.');m.finance.currency=f.currency;const existing=equipment?m.finance.lines.find(l=>l.equipmentId===equipment.id&&l.needsPrice):null;const line={id:existing?.id||uid(),title:f.title,type:f.type,quantity:Number(f.quantity),unitPrice:Number(f.unitPrice),equipmentId:equipment?.id||'',needsPrice:false};if(existing)Object.assign(existing,line);else m.finance.lines.push(line);activity('Partida financiera registrada',p.id,f.title);if(equipment&&f.createMilestone)API.mutate(data=>{const hit=data.milestones.find(m=>m.projectId===p.id&&m.notes==='Equipo: '+equipment.id);if(hit){if(f.dueDate)hit.dueDate=f.dueDate;}else data.milestones.push({id:uid(),projectId:p.id,title:'Instalación / puesta en servicio: '+equipment.name,type:'Puesta en marcha',status:'Pendiente',dueDate:f.dueDate,owner:p.owner||'',notes:'Equipo: '+equipment.id});});d.close();renderWorkspace();bind();});
  }
  function crm(p){const m=meta(p.id),d=dialog('Cliente y cotización','<form id="crmForm" class="suite-modal-grid"><label>Cliente / contacto<input name="contact" value="'+esc(m.contact||'')+'"></label><label>Origen del proyecto<select name="source">'+opt(['Sin definir','Recomendación','Cliente recurrente','Web','LinkedIn','Licitación','Otro'],m.source||'Sin definir')+'</select></label><label>Resultado de cotización<select name="quoteOutcome">'+opt(['Pendiente','Ganada','Perdida'],m.quoteOutcome||'Pendiente')+'</select></label><label>Fecha de cotización<input name="quotedAt" type="date" value="'+esc((m.quotedAt||'').slice(0,10))+'"></label><button class="primary wide">Guardar</button></form>');$('crmForm').onsubmit=e=>{e.preventDefault();Object.assign(m,Object.fromEntries(new FormData(e.target)));activity('Datos comerciales actualizados',p.id);d.close();renderWorkspace();bind();};}
  function assignEquipment(p,eqId=''){
    const data=tracker(),d=dialog('Asignar equipo al proyecto','<form id="assignEquipmentForm" class="suite-modal-grid"><label class="wide">Equipo<select name="equipmentId">'+data.equipment.map(e=>'<option value="'+esc(e.id)+'" '+(e.id===eqId?'selected':'')+'>'+esc(e.name)+' · '+esc(data.projects.find(p=>p.id===e.projectId)?.name||'Sin asignar')+'</option>').join('')+'</select></label><label class="wide">Proyecto<select name="projectId">'+projectOptions(p?.id||'')+'</select></label><p class="wide suite-notice">La asignación cambia el proyecto del equipo. Después podés registrar su costo y el hito de instalación desde el proyecto.</p><button class="primary wide" '+(!data.equipment.length?'disabled':'')+'>Asignar equipo</button></form>');$('assignEquipmentForm').onsubmit=e=>guard(()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));API.mutate(data=>{const eq=data.equipment.find(x=>x.id===f.equipmentId);if(eq)eq.projectId=f.projectId;});d.close();if(f.projectId)openProject(f.projectId,'Equipos');toast('Equipo asignado. Registrá su costo y fecha con “Costo / hito”.');});
  }
  function assignCalculation(p){const d=dialog('Vincular cálculo existente','<form id="linkCalculationForm"><label>Cálculo<select name="balanceId">'+balances().map(b=>'<option value="'+esc(b.id)+'">'+esc(b.nombre)+'</option>').join('')+'</select></label><p class="suite-notice">El cálculo aparecerá acá y en Cálculos guardados.</p><button class="primary" '+(!balances().length?'disabled':'')+'>Vincular a este proyecto</button></form>');$('linkCalculationForm').onsubmit=e=>guard(()=>{e.preventDefault();link(new FormData(e.target).get('balanceId'),p.id);d.close();renderWorkspace();bind();});}
  function previewDocument(id){const d=tracker().documents.find(x=>x.id===id);if(!d)return;const url=C.previewUrl(d.driveUrl);dialog(d.title,url?'<iframe class="preview-document" title="Vista previa de '+esc(d.title)+'" src="'+esc(url)+'" referrerpolicy="no-referrer" allow="fullscreen"></iframe><p class="subtle">La vista depende de los permisos de Drive y del formato. Drive puede pedir iniciar sesión. Los DWG necesitan una vista compatible o una copia PDF.</p>':empty('Este enlace no permite una vista incrustada. Para planos DWG, adjuntá también una versión PDF.'));}
  function calculateRows(b){return (b.ambientes||[]).map(a=>THERMABOT_ENGINE.calcular_ambiente(a,b.condiciones||{},b.cerramientos||[]));}
  function compareCalculations(list=balances()){if(list.some(b=>b.method==='quadri-v3')){dialog('Comparación de balances','<table><thead><tr><th>Balance</th><th>Método</th><th>kW de edificio</th><th>Hora pico</th></tr></thead><tbody>'+list.map(b=>'<tr><td>'+esc(b.nombre)+'</td><td>'+esc(b.method||'Anterior')+'</td><td>'+(b.summary?num(b.summary.total_kw):'—')+'</td><td>'+esc(b.summary?.peakHour??'—')+'</td></tr>').join('')+'</tbody></table><p>Los cálculos anteriores conservan su método original. Abrilos para ver sus resultados; no se convierten automáticamente.</p>');return;}
    const d=dialog('Comparar cálculos','<p class="subtle">Comparación de cargas calculadas por ambiente. La suma de máximos no aplica diversidad ni simultaneidad entre locales.</p><div class="suite-toolbar">'+list.map(b=>'<label><span><input type="checkbox" data-compare-balance="'+esc(b.id)+'" checked> '+esc(b.nombre)+'</span></label>').join('')+'</div><div id="compareResults" class="suite-compare"></div>');
    const render=()=>{const chosen=[...d.querySelectorAll('[data-compare-balance]:checked')].map(x=>list.find(b=>b.id===x.dataset.compareBalance));const summaries=chosen.map(b=>{const rs=calculateRows(b),sum=k=>rs.reduce((s,r)=>s+Number(r[k]||0),0);return {b,rs,total:sum('total_kw'),sensible:sum('sensible_total_kw'),latent:sum('latente_total_kw'),area:sum('superficie_m2'),supply:sum('caudal_impulsion_m3h')};});$('compareResults').innerHTML='<table><thead><tr><th>Dato</th>'+summaries.map(x=>'<th>'+esc(x.b.nombre)+'</th>').join('')+'</tr></thead><tbody>'+[['Ciudad',x=>esc(x.b.condiciones?.ciudad||'')],['Ambientes',x=>x.rs.length],['Superficie · m²',x=>num(x.area)],['Carga total · kW',x=>num(x.total)],['Sensible · kW',x=>num(x.sensible)],['Latente · kW',x=>num(x.latent)],['Impulsión · m³/h',x=>num(x.supply)]].map(([label,get])=>'<tr><th>'+label+'</th>'+summaries.map(x=>'<td>'+get(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';};d.querySelectorAll('[data-compare-balance]').forEach(c=>c.onchange=()=>guard(render));guard(render);
  }
  function printPage(title,body){
    const frame=document.createElement('iframe');frame.style.cssText='position:fixed;left:-10000px;width:900px;height:1000px';frame.title='Informe para imprimir';
    frame.onload=()=>{const win=frame.contentWindow;win.addEventListener('afterprint',()=>setTimeout(()=>frame.remove(),500),{once:true});win.focus();win.print();};
    frame.srcdoc='<!doctype html><html lang="es"><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>@page{size:A4;margin:18mm}body{font:13px Arial,sans-serif;color:#16392c;line-height:1.65}header{border-bottom:3px solid #256e56;padding:10px 0;margin-bottom:25px}h1{font-size:26px}h2{font-size:19px}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:left}small{color:#65796d}img{max-width:100%;max-height:260px}footer{margin-top:35px;border-top:1px solid #ddd;padding:12px;font-size:10px}</style></head><body><header><b>THERMABOT · BIOINGENIERÍA</b><br><small>Gestión técnica HVAC · '+new Date().toLocaleDateString('es-AR')+'</small></header><h1>'+esc(title)+'</h1>'+body+'<footer>Preparado por '+esc(suite.preferences.actor||'Bioingeniería')+' · THERMABOT</footer></body></html>';
    document.body.append(frame);toast('Elegí “Guardar como PDF” en el diálogo de impresión.');
  }
  function clientSheet(p){const snapshot=C.publicSnapshot(p,tracker());dialog('Ficha para el cliente','<p>Incluye el avance, la etapa y los hitos. Las notas internas, los bloqueos y los costos quedan fuera de esta ficha.</p><div class="suite-notice"><b>'+esc(snapshot.name)+'</b><p>'+esc(snapshot.establishment)+' · '+esc(snapshot.stage)+' · '+num(snapshot.progress)+'% de avance</p></div><p class="subtle">En esta versión la ficha se comparte como PDF. Los enlaces privados y el portal del cliente requieren un servicio con control de acceso.</p><button id="printClientSheet" class="primary">Generar PDF para compartir</button>');$('printClientSheet').onclick=()=>printPage(snapshot.name,'<p>'+esc(snapshot.establishment)+' · '+esc(snapshot.stage)+'</p><h2>Avance: '+num(snapshot.progress)+'%</h2><p>Estado: '+esc(snapshot.status)+'</p><table><tr><th>Hito</th><th>Estado</th><th>Fecha</th></tr>'+snapshot.milestones.map(m=>'<tr><td>'+esc(m.title)+'</td><td>'+esc(m.status)+'</td><td>'+esc(m.dueDate||'Por definir')+'</td></tr>').join('')+'</table>');}
  function balancePdf(id){const b=balances().find(b=>b.id===id);if(!b)return;if(b.method==='quadri-v3'){setModule('calculator',id,library().links[id]);toast('Abrí Informe PDF en el balance Quadri.');return;}const findings=TBWorkspace.audit(b).findings;if(findings.some(f=>f.severity==='CRÍTICO')){dialog('Revisá los datos antes de emitir','<p>Hay entradas críticas que necesitan corregirse.</p>'+findings.filter(f=>f.severity==='CRÍTICO').map(f=>'<p><b>'+esc(f.subject)+'</b>: '+esc(f.problem)+'</p>').join(''));return;}const rs=calculateRows(b);printPage('Balance térmico · '+b.nombre,'<p>Ciudad: '+esc(b.condiciones?.ciudad)+' · Exterior: '+num(b.condiciones?.tempExterior)+' °C · Interior: '+num(b.condiciones?.tempInterior)+' °C</p><table><tr><th>Ambiente</th><th>m²</th><th>Sensible kW</th><th>Latente kW</th><th>Total kW</th><th>Impulsión m³/h</th></tr>'+rs.map(r=>'<tr><td>'+esc(r.nombre)+'</td><td>'+num(r.superficie_m2)+'</td><td>'+num(r.sensible_total_kw)+'</td><td>'+num(r.latente_total_kw)+'</td><td>'+num(r.total_kw)+'</td><td>'+num(r.caudal_impulsion_m3h)+'</td></tr>').join('')+'</table><h2>Suma de cargas por ambiente: '+num(rs.reduce((s,r)=>s+r.total_kw,0))+' kW</h2><p><small>Suma de máximos individuales sin diversidad. Cálculo estimativo con condiciones y materiales cargados; completar la verificación de ingeniería y la selección de equipos.</small></p>'+rs.flatMap(r=>r.alertas||[]).map(a=>'<p>'+esc(a)+'</p>').join(''));activity('Informe térmico preparado',library().links[id]||'',b.nombre);}
  function caseStudy(p){const m=meta(p.id);dialog('Caso de éxito','<form id="caseForm" class="suite-modal-grid"><label class="wide">Problema que resolviste<textarea name="challenge" required>'+esc(m.caseStudy?.challenge||'')+'</textarea></label><label class="wide">Solución y resultado comprobado<textarea name="result" required>'+esc(m.caseStudy?.result||'')+'</textarea></label><label class="wide">Fotografías autorizadas<input id="casePhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="wide"><span><input name="permission" type="checkbox" required> Puedo compartir estos datos y estas imágenes.</span></label><button class="primary wide">Preparar ficha técnica</button></form>');$('caseForm').onsubmit=e=>guard(async()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const photos=[...$('casePhotos').files];if(photos.length>4||photos.some(x=>x.size>2000000))throw Error('Usá hasta 4 fotos de menos de 2 MB cada una.');const urls=await Promise.all(photos.map(file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('No se pudo leer una foto.'));r.readAsDataURL(file);})));m.caseStudy={challenge:f.challenge,result:f.result,preparedAt:new Date().toISOString()};activity('Caso de éxito preparado',p.id);printPage('Caso de éxito · '+p.name,'<p>'+esc(p.system)+' · '+esc(p.establishment)+'</p><h2>El desafío</h2><p>'+esc(f.challenge)+'</p><h2>La solución y el resultado</h2><p>'+esc(f.result)+'</p>'+urls.map(u=>'<img src="'+esc(u)+'" alt="Fotografía del proyecto">').join(''));$('suiteDialog').close();});}
  function feed(projectId=''){const list=suite.activity.filter(a=>!projectId||a.projectId===projectId).slice().reverse();return '<p class="subtle">Historial de cambios registrados en la aplicación. El nombre identifica al operador configurado; no es una firma verificada.</p><div class="card">'+list.slice(0,200).map(a=>'<article class="activity-item"><time>'+esc(new Date(a.at).toLocaleString('es-AR'))+' · '+esc(a.actor)+'</time><strong>'+esc(a.title)+'</strong><p>'+esc(a.detail)+'</p>'+(a.changes?.length?'<details class="trace-details"><summary>Ver cambios · antes / después</summary><div class="technical-table"><table><thead><tr><th>Dato</th><th>Antes</th><th>Después</th></tr></thead><tbody>'+a.changes.map(c=>'<tr><td>'+esc(c.label||c.field)+'</td><td>'+esc(typeof c.before==='object'?JSON.stringify(c.before):c.before??'—')+'</td><td>'+esc(typeof c.after==='object'?JSON.stringify(c.after):c.after??'—')+'</td></tr>').join('')+'</tbody></table></div></details>':'')+(a.projectId?'<button data-open-project="'+esc(a.projectId)+'">'+esc(tracker().projects.find(p=>p.id===a.projectId)?.name||'Proyecto archivado / eliminado')+'</button>':'')+'</article>').join('')+(list.length?'':empty('Las próximas modificaciones aparecerán acá.'))+'</div>';}
  function renderActivity(){$('activityFeed').innerHTML='<div class="suite-head"><div><h2>Actividad</h2><p>Quién registró cada cambio y cuándo.</p></div><button id="exportActivity">Descargar historial</button></div>'+feed();$('exportActivity').onclick=()=>download(suite.activity,'THERMABOT-actividad.json');}
  function renderModule(view){
    if(view!=='calculator')return;
    const p=tracker().projects.find(p=>p.id===(moduleProject||API.selectedId()));if(!moduleProject&&p)moduleProject=p.id;
    $(view==='calculator'?'calculatorContext':'pressureContext').innerHTML='<label>Proyecto de seguimiento<select id="'+view+'Project">'+projectOptions(moduleProject)+'</select></label><button id="'+view+'Save" class="primary">'+(p?'Guardar en '+esc(p.name):'Guardar cálculo')+'</button><button id="'+view+'PDF">Generar PDF para el cliente</button><button id="'+view+'Compare">Comparar cálculos</button><span class="subtle">Borrador local y estado de Drive al pie.</span>';
    $(view+'Project').onchange=e=>{moduleProject=e.target.value;if(view==='calculator')setModule(view,undefined,moduleProject);else setModule(view,undefined,moduleProject);};$(view+'Save').onclick=()=>{const frame=document.querySelector('#view-'+view+' iframe');frame.contentWindow.postMessage({type:'thermabot:save',projectId:moduleProject},location.origin);};$(view+'PDF').onclick=()=>{if(view==='calculator'&&document.querySelector('#view-calculator iframe').getAttribute('src')?.startsWith('quadri/')){document.querySelector('#view-calculator iframe').contentWindow.postMessage({type:'thermabot:print'},location.origin);return;}if(view==='pressure'){document.querySelector('#view-pressure iframe').contentWindow.postMessage({type:'thermabot:print'},location.origin);toast('Elegí Guardar como PDF.');return;}const id=activeBalances.calculator||linked(moduleProject)[0]?.id;if(!id){toast('Guardá el cálculo para preparar el informe.');return;}balancePdf(id);};$(view+'Compare').onclick=()=>compareCalculations();
  }
  function bind(){
    const createLink=$('view-balances')?.querySelector('.heading a');if(createLink)createLink.onclick=e=>{e.preventDefault();setModule('calculator');};
    document.querySelectorAll('[data-open-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.openProject,b.dataset.openTab||'Resumen'));
    document.querySelectorAll('[data-edit-project]').forEach(b=>b.onclick=()=>FLOW.edit(b.dataset.editProject));
    document.querySelectorAll('[data-quick-project]').forEach(b=>b.onclick=()=>FLOW.quick(b.dataset.quickProject));
    document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setModule(b.dataset.tool,b.dataset.balance,b.dataset.toolProject,!!b.dataset.newBalance));
    document.querySelectorAll('[data-edit-eq]').forEach(b=>b.onclick=()=>API.editEquipment(b.dataset.editEq));
    document.querySelectorAll('[data-assign-eq]').forEach(b=>b.onclick=()=>assignEquipment(null,b.dataset.assignEq));
    document.querySelectorAll('[data-equipment-cost]').forEach(b=>b.onclick=()=>financeLine(selected(),tracker().equipment.find(e=>e.id===b.dataset.equipmentCost)));
    document.querySelectorAll('[data-preview-doc]').forEach(b=>b.onclick=()=>previewDocument(b.dataset.previewDoc));
    document.querySelectorAll('[data-edit-doc]').forEach(b=>b.onclick=()=>API.editDocument(b.dataset.editDoc));
    document.querySelectorAll('[data-client-pdf]').forEach(b=>b.onclick=()=>guard(()=>balancePdf(b.dataset.clientPdf)));
    document.querySelectorAll('[data-case-project]').forEach(b=>b.onclick=()=>caseStudy(tracker().projects.find(p=>p.id===b.dataset.caseProject)));
    document.querySelectorAll('[data-edit-task]').forEach(b=>b.onclick=()=>b.dataset.editTask.startsWith('next:')?FLOW.quick(b.dataset.taskProject):API.editMilestone(b.dataset.editTask));
    document.querySelectorAll('[data-project-status]').forEach(b=>b.onchange=()=>moveProject(b.dataset.projectStatus,b.value));
    document.querySelectorAll('[data-complete-task]').forEach(b=>b.onchange=()=>moveTask(b.dataset.completeTask,b.checked?'Cumplido':'Pendiente'));
    document.querySelectorAll('[data-commit-task]').forEach(b=>b.onclick=()=>guard(()=>{const task=C.tasks(tracker(),date(),suite.projects).find(t=>t.id===b.dataset.commitTask);if(!task?.dueDate)throw Error('Primero ingresá la fecha límite de la tarea.');if(E.week(task.dueDate)!==E.week(date()))throw Error('El compromiso semanal requiere una fecha límite dentro de esta semana.');const m=meta(task.projectId);m.taskFacts=m.taskFacts||{};const f=m.taskFacts[task.id]||{};if(f.committedWeek===E.week(date())&&!confirm('Quitar este compromiso modifica el denominador del PPC semanal. ¿Continuar?'))return;m.taskFacts[task.id]={...f,dueDate:task.dueDate,committedWeek:f.committedWeek===E.week(date())?'':E.week(date())};activity('Compromiso semanal actualizado',task.projectId,task.title);render();}));
    document.querySelectorAll('[data-task-status]').forEach(b=>b.onchange=()=>moveTask(b.dataset.taskStatus,b.value));
    document.querySelectorAll('[draggable=true]').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('application/thermabot',JSON.stringify({kind:el.dataset.dragProject?'project':'task',id:el.dataset.dragProject||el.dataset.dragTask}));e.dataTransfer.effectAllowed='move';});
    document.querySelectorAll('.lane').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over');};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>guard(()=>{e.preventDefault();el.classList.remove('drag-over');const raw=e.dataTransfer.getData('application/thermabot');if(!raw)return;const payload=JSON.parse(raw);if(payload.kind!==el.dataset.board)return;if(payload.kind==='project')moveProject(payload.id,el.dataset.lane);else moveTask(payload.id,el.dataset.lane);});});
    // Keep the saved calculations page inside the same navigation flow.
    $('balanceList')?.querySelectorAll('a').forEach(a=>{if(a.textContent.includes('Abrir'))a.onclick=e=>{e.preventDefault();setModule('calculator',new URL(a.href).searchParams.get('balanceId'));};});
  }
  function moveProject(id,status){if(!['Activo','En revisión','Esperando tercero','Bloqueado','Urgente','Finalizado','Suspendido'].includes(status))return;API.mutate(data=>{const p=data.projects.find(p=>p.id===id);if(p){p.status=status;p.updatedAt=new Date().toISOString();}});toast('Estado del proyecto actualizado.');}
  function moveTask(id,status){if(!['Pendiente','En curso','Esperando respuesta','Cumplido'].includes(status))return;const task=C.tasks(tracker(),date(),suite.projects).find(t=>t.id===id);if(task){const m=meta(task.projectId);m.taskFacts=m.taskFacts||{};m.taskFacts[id]={...(m.taskFacts[id]||{}),completedAt:status==='Cumplido'?new Date().toISOString():null};saveSuite();}API.mutate(data=>{if(id.startsWith('next:')){const p=data.projects.find(p=>p.id===id.slice(5));if(!p)return;if(status==='Cumplido'){const completedId=uid();data.milestones.push({id:completedId,projectId:p.id,title:p.nextAction,type:'Otro',status:'Cumplido',dueDate:p.nextDueDate===undefined?p.targetDate||'':p.nextDueDate,owner:p.owner||'',notes:'Próxima acción completada desde el tablero'});const pm=meta(p.id);if(pm.taskFacts?.[id]){pm.taskFacts[completedId]=pm.taskFacts[id];delete pm.taskFacts[id];}pm.nextTaskStatus='Pendiente';saveSuite();p.nextAction='';}else {meta(p.id).nextTaskStatus=status;activity('Estado de tarea actualizado',p.id,p.nextAction+' · '+status);}}else{const m=data.milestones.find(m=>m.id===id);if(m)m.status=status;}});toast('Tarea actualizada.');}
  function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>guard(render),80);}
  function render(){renderDashboard();renderTasksPage();renderPortfolio();renderWorkspace();renderActivity();renderModule('calculator');bind();if(API.view()==='equipment'){let el=$('equipmentCatalog');if(!el){el=document.createElement('section');el.id='equipmentCatalog';el.className='suite';$('view-equipment').append(el);$('view-equipment').querySelector('.tracker-panel').hidden=true;}el.innerHTML=equipmentList(tracker().equipment);bind();}if(API.view()==='balances'&&!$('compareAllCalculations')){const b=document.createElement('button');b.id='compareAllCalculations';b.textContent='Comparar cálculos';b.onclick=()=>compareCalculations();$('view-balances').querySelector('.heading').append(b);}status();}
  function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function snapshot(){return {format:'thermabot-suite',schema:1,exportedAt:new Date().toISOString(),tracker:tracker(),balances:balances(),library:library(),suite:JSON.parse(JSON.stringify(suite))};}
  function openBackupDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('thermabot-safe-copies',1);request.onupgradeneeded=()=>request.result.createObjectStore('snapshots',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  function scheduleBackup(){clearTimeout(backupTimer);backupTimer=setTimeout(()=>guard(makeBackup),1800);}
  async function makeBackup(){if(!db)return;const value=snapshot(),key=JSON.stringify({tracker:value.tracker,balances:value.balances,library:value.library,suite:value.suite});if(key===makeBackup.previous)return;await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readwrite'),store=tx.objectStore('snapshots');store.put({id:Date.now(),at:value.exportedAt,value});const all=store.getAllKeys();all.onsuccess=()=>all.result.slice(0,Math.max(0,all.result.length-30)).forEach(k=>store.delete(k));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});makeBackup.previous=key;localStorage.setItem('thermabot.suite.backupAt',value.exportedAt);status();}
  async function backupVersions(){if(!db)throw Error('El navegador no habilitó las copias internas. Descargá una copia completa.');const list=await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots'),r=tx.objectStore('snapshots').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});dialog('Copias automáticas de este navegador','<p class="subtle">Se conservan hasta 30 versiones. Estas copias están en este equipo; para conservarlas fuera del navegador, descargá una copia completa o usá Drive.</p><div class="suite-list">'+list.reverse().map(x=>'<article><div class="suite-row"><span>'+esc(new Date(x.at).toLocaleString('es-AR'))+'</span><button data-download-version="'+x.id+'">Descargar versión</button></div><p>'+x.value.tracker.projects.length+' proyectos · '+x.value.balances.length+' cálculos</p></article>').join('')+'</div>');document.querySelectorAll('[data-download-version]').forEach(b=>b.onclick=()=>download(list.find(x=>x.id===Number(b.dataset.downloadVersion)).value,'THERMABOT-copia-'+b.dataset.downloadVersion+'.json'));}
  async function restoreFile(file){
    if(file.size>20000000)throw Error('La copia supera 20 MB.');const value=JSON.parse(await file.text());
    if(value.format!=='thermabot-suite'||value.schema!==1||!value.tracker||!['projects','equipment','milestones','documents'].every(k=>Array.isArray(value.tracker[k]))||!Array.isArray(value.balances)||!value.suite?.projects||!Array.isArray(value.suite.activity)||!value.suite.preferences||!value.library?.links||!Array.isArray(value.library.audits))throw Error('No es una copia completa de THERMABOT.');
    value.balances.forEach(TBWorkspace.validateBalance);
    if(!confirm('¿Restaurar esta copia completa? Primero se descargará una copia de los datos actuales.'))return;
    download(snapshot(),'THERMABOT-antes-de-restaurar.json');
    const keys=['thermabot.tracker.v1',BAL,LIB,KEY];const values=[value.tracker,value.balances,value.library,value.suite];const old=keys.map(k=>localStorage.getItem(k));
    try{keys.forEach((key,i)=>{if(old[i])localStorage.setItem(key+'.before-restore',old[i]);localStorage.setItem(key,JSON.stringify(values[i]));});}catch(error){keys.forEach((key,i)=>{if(old[i]===null)localStorage.removeItem(key);else localStorage.setItem(key,old[i]);});throw error;}
    initState();previous=null;API.refresh();previous=tracker();activity('Copia completa restaurada','','Archivo '+file.name);scheduleRender();toast('Copia restaurada en este navegador. Revisá Drive antes de sincronizar.');
  }
  function renderSettings(){
    $('suiteSettings').innerHTML='<div class="suite-head"><div><h2>Configuración</h2><p>Un solo lugar para las conexiones y la recuperación.</p></div></div><div class="suite-two"><section class="card"><h3>Mi perfil y apariencia</h3><form id="preferencesForm"><label>Nombre del operador<input name="actor" value="'+esc(suite.preferences.actor||'')+'" required></label><label>Tema<select name="theme">'+opt(['Claro','Oscuro','Según el dispositivo'],suite.preferences.theme==='dark'?'Oscuro':suite.preferences.theme==='system'?'Según el dispositivo':'Claro')+'</select></label><button class="primary" style="margin-top:14px">Guardar preferencias</button></form></section><section class="card"><h3>Copias de seguridad</h3><p class="subtle">Los cambios se guardan automáticamente en este navegador. También se conservan versiones internas cuando el navegador lo permite.</p><div class="actions"><button id="exportSuite">Descargar copia completa</button><button id="showBackups">Ver copias automáticas</button><label class="button">Restaurar copia completa<input id="restoreSuite" type="file" accept=".json" hidden></label></div><p id="backupInfo" class="subtle"></p></section></div><section class="card"><h3>Google Drive</h3><p class="subtle">Proyectos, historiales y cálculos usan la conexión privada configurada. El estado de Drive confirma únicamente lo que se verificó en la nube.</p><p id="cloudSettingsStatus" class="suite-notice"></p><div class="actions"><button id="retryCloudSave">Comprobar guardado pendiente</button></div><p class="suite-notice">El historial se conserva junto a los proyectos. La barra superior indica si hay cambios locales pendientes o un guardado verificado en Drive.</p></section>';
    $('preferencesForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));suite.preferences.actor=f.actor;suite.preferences.theme=f.theme==='Oscuro'?'dark':f.theme==='Según el dispositivo'?'system':'light';saveSuite();applyTheme();toast('Preferencias guardadas.');};$('exportSuite').onclick=()=>download(snapshot(),'THERMABOT-copia-completa.json');$('showBackups').onclick=()=>guard(backupVersions);$('restoreSuite').onchange=e=>{const file=e.target.files[0];if(file)guard(()=>restoreFile(file));e.target.value='';};$('retryCloudSave').onclick=()=>guard(async()=>{if(window.TBDesignPreview){toast('Esta prueba guarda sólo en el navegador.');return;}await window.TBCloud?.save();status();});status();
  }
  function status(){if(window.TBDesignPreview){const q=document.getElementById('driveQuickBtn'),r=document.getElementById('trackerSaveStatus');if(q.textContent!=='Prueba local · nube desactivada')q.textContent='Prueba local · nube desactivada';if(r.textContent!=='Diseño de prueba · datos locales')r.textContent='Diseño de prueba · datos locales';}let el=$('suiteSaveIndicator');if(!el){el=document.createElement('div');el.id='suiteSaveIndicator';el.className='status-indicator';$('trackerMeta').after(el);}const text=window.TBCloud?.status()||$('driveQuickBtn').textContent||'Copia local';el.innerHTML='<i></i><span>'+esc(text)+'</span>';el.classList.toggle('verified',/verificad|sincronizad/i.test(text)&&!/pendiente|error|desconectad/i.test(text));if($('cloudSettingsStatus'))$('cloudSettingsStatus').textContent=text;const at=localStorage.getItem('thermabot.suite.backupAt');if($('backupInfo'))$('backupInfo').textContent=at?'Última copia interna: '+new Date(at).toLocaleString('es-AR'):'La copia interna se crea después del próximo cambio.';}
  function applyTheme(){const resolved=suite.preferences.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):suite.preferences.theme||'light';document.body.dataset.theme=resolved;document.querySelectorAll('.module-frame').forEach(f=>f.contentWindow?.postMessage({type:'thermabot:theme',theme:document.body.dataset.theme},location.origin));}
  function palette(){let d=$('suitePalette');if(!d){d=document.createElement('dialog');d.id='suitePalette';d.className='suite-dialog palette suite';document.body.append(d);}d.oncancel=null;d.innerHTML='<div class="dialog-head"><span class="suite-label">IR A CUALQUIER PARTE</span><button id="closePalette" aria-label="Cerrar buscador">×</button></div><input id="paletteQuery" aria-label="Buscar proyectos, tareas, equipos, documentos y cálculos" placeholder="Buscar proyecto, tarea, cálculo, documento o equipo…"><div id="paletteResults" class="palette-results"></div><p class="subtle">↑ ↓ para elegir · Enter para abrir · Esc para cerrar</p>';$('closePalette').onclick=()=>d.close();d.showModal();$('paletteQuery').focus();const render=()=>{paletteRows=C.search(tracker(),balances(),$('paletteQuery').value);paletteIndex=0;showPaletteResults();};$('paletteQuery').oninput=render;d.onkeydown=e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();paletteIndex=Math.max(0,Math.min(paletteRows.length-1,paletteIndex+(e.key==='ArrowDown'?1:-1)));showPaletteResults();}if(e.key==='Enter'){e.preventDefault();choosePalette(paletteRows[paletteIndex]);}};render();}
  function showPaletteResults(){$('paletteResults').innerHTML=paletteRows.map((r,i)=>'<button data-palette-result="'+i+'" class="'+(i===paletteIndex?'primary':'')+'">'+tag(r.kind,'neutral')+'<span><strong>'+esc(r.title)+'</strong><small>'+esc(r.detail)+'</small></span></button>').join('')||(empty('No se encontraron resultados.'));document.querySelectorAll('[data-palette-result]').forEach(b=>b.onclick=()=>choosePalette(paletteRows[Number(b.dataset.paletteResult)]));}
  function choosePalette(row){if(!row)return;$('suitePalette').close();if(row.kind==='Cálculo'){setModule('calculator',row.id,library().links[row.id]);return;}if(row.projectId){openProject(row.projectId,({Equipo:'Resumen',Documento:'Documentos',Hito:'Seguimiento',Tarea:'Seguimiento'})[row.kind]||'Resumen');if(row.kind==='Documento')previewDocument(row.id);}else if(row.kind==='Equipo'){API.navigate('equipment');API.editEquipment(row.id);}else if(row.kind==='Documento')previewDocument(row.id);else API.editMilestone(row.id);}

  function installWorkbenchIcons(){const paths={dashboard:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',projects:'M3 6h7l2 2h9v12H3z',tasks:'M4 5h3v3H4z M11 6h9 M4 11h3v3H4z M11 12h9 M4 17h3v3H4z M11 18h9',balances:'M5 3h14v18H5z M8 7h8 M8 11h2 M14 11h2 M8 15h2 M14 15h2',equipment:'M4 7h16v13H4z M8 7V4h8v3 M8 11h8 M8 15h8',activity:'M12 3a9 9 0 1 1-9 9 M3 4v8h8 M12 7v5l4 2',calculator:'M12 3v4 M12 17v4 M3 12h4 M17 12h4 M5 5l3 3 M16 16l3 3 M5 19l3-3 M16 8l3-3 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',pressure:'M3 8h16l-4-4 M21 16H5l4 4',audits:'M4 12l5 5L20 6',settings:'M12 3v4 M12 17v4 M3 12h4 M17 12h4 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',marketing:'M4 20V4 M4 20h16 M8 15l4-4 4 2 4-7'};document.querySelectorAll('.rail [data-view] b').forEach(el=>{el.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[el.parentElement.dataset.view]||paths.projects)+'"/></svg>';});document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=b.getBoundingClientRect(),dot=document.createElement('span');b.classList.add('ripple-host');dot.className='ripple-dot';const size=Math.max(r.width,r.height);Object.assign(dot.style,{width:size+'px',height:size+'px',left:(e.clientX-r.left-size/2)+'px',top:(e.clientY-r.top-size/2)+'px'});b.append(dot);setTimeout(()=>dot.remove(),500);});}
  function init(){
    guard(()=>{initState();previous=tracker();API.editProject=FLOW.edit;applyTheme();installWorkbenchIcons();
      if(document.body.dataset.projectTab){projectTab=document.body.dataset.projectTab;FLOW.workspace(projectTab);}
      window.addEventListener('thermabot:projecttab',e=>{projectTab=e.detail;FLOW.workspace(projectTab);bind();});
      document.body.classList.toggle('collapsed',!!suite.preferences.collapsed);
      document.querySelectorAll('.rail [data-view]').forEach(b=>b.setAttribute('aria-label',b.getAttribute('title')||b.textContent.trim()));
      const collapseLabel=()=>{$('collapseRail').setAttribute('aria-expanded',String(!suite.preferences.collapsed));$('collapseRail').setAttribute('aria-label',suite.preferences.collapsed?'Expandir menú':'Contraer menú');};collapseLabel();
      $('collapseRail').onclick=()=>{suite.preferences.collapsed=!suite.preferences.collapsed;document.body.classList.toggle('collapsed',suite.preferences.collapsed);collapseLabel();saveSuite();};
      $('newProjectBtn').onclick=()=>FLOW.edit();$('openThermalTool').onclick=()=>setModule('calculator');$('openEngineeringReview').onclick=()=>API.navigate('audits');matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(suite.preferences.theme==='system')applyTheme();});
      $('themeBtn').onclick=()=>{suite.preferences.theme=suite.preferences.theme==='dark'?'light':'dark';saveSuite();applyTheme();};$('globalSearchBtn').onclick=palette;
      document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('suitePalette')?.open)palette();}});
      window.addEventListener('thermabot:data',()=>guard(captureChanges));window.addEventListener('thermabot:render',scheduleRender);window.addEventListener('thermabot:portfolio',scheduleRender);window.addEventListener('thermabot:navigate',()=>{if(API.view()==='settings')renderSettings();if(['calculator','pressure'].includes(API.view())){moduleProject=API.selectedId()||moduleProject;renderModule(API.view());}scheduleRender();});
      window.addEventListener('storage',e=>guard(()=>{if(e.key==='thermabot.tracker.v1')API.refresh();if(e.key===KEY)initState();scheduleBackup();scheduleRender();}));
      window.addEventListener('message',e=>guard(()=>{if(e.origin!==location.origin||!['calculator','pressure'].some(v=>document.querySelector('#view-'+v+' iframe')?.contentWindow===e.source))return;const msg=e.data;if(msg?.type==='thermabot:navigate'){if(msg.view==='project'&&tracker().projects.some(p=>p.id===msg.projectId))openProject(msg.projectId);else if(['dashboard','balances','pressure'].includes(msg.view))API.navigate(msg.view);return;}if(msg?.type==='thermabot:saved'&&typeof msg.balanceId==='string'){const sourceModule=['calculator','pressure'].find(v=>document.querySelector('#view-'+v+' iframe')?.contentWindow===e.source);activeBalances[sourceModule]=msg.balanceId;
        const projectId=tracker().projects.some(p=>p.id===msg.projectId)?msg.projectId:API.view()===sourceModule?moduleProject:library().links[msg.balanceId]||'';
        if(projectId&&library().links[msg.balanceId]!==projectId)link(msg.balanceId,projectId);
        if(msg.explicit||Date.now()-(calculationActivityAt[msg.balanceId]||0)>30000){activity(msg.explicit?'Cálculo guardado':'Cálculo actualizado',projectId,balances().find(b=>b.id===msg.balanceId)?.nombre||'');calculationActivityAt[msg.balanceId]=Date.now();}scheduleBackup();scheduleRender();if(msg.explicit)toast(moduleProject?'Cálculo guardado y vinculado al proyecto.':'Cálculo guardado. Seleccioná un proyecto para vincularlo.');}if(msg?.type==='thermabot:ready'){e.source.postMessage({type:'thermabot:theme',theme:document.body.dataset.theme},location.origin);const sourceModule=['calculator','pressure'].find(v=>document.querySelector('#view-'+v+' iframe')?.contentWindow===e.source);activeBalances[sourceModule]=msg.balanceId;}}));
      const statusButton=$('driveQuickBtn');if(statusButton){const observer=new MutationObserver(status);observer.observe(statusButton,{childList:true,characterData:true,subtree:true});}
      openBackupDB().then(value=>{db=value;scheduleBackup();}).catch(()=>toast('Este navegador no habilitó las copias internas. Podés descargar una copia completa.'));
      document.querySelectorAll('.module-frame').forEach(f=>f.addEventListener('load',applyTheme));render();renderSettings();
    });
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();



