(() => {
  'use strict';
  const C=TBSuiteCore,API=TBTracker,KEY='thermabot.suite.v1',LIB='thermabot.workspace.v1',BAL='thermabot.proyectos.v1';
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=(key,fallback)=>{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;};
  const date=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
  const num=v=>Number(v||0).toLocaleString('es-AR',{maximumFractionDigits:2});
  const uid=()=>crypto.randomUUID(),empty=t=>'<div class="suite-empty">'+esc(t)+'</div>';
  const tag=(text,type='')=>'<span class="tag '+type+'">'+esc(text||'Sin definir')+'</span>';
  const opt=(values,selected)=>values.map(x=>'<option '+(x===selected?'selected':'')+'>'+esc(x)+'</option>').join('');
  let suite,previous,projectTab='Resumen',chartFilter='',taskProject='',taskQuery='',boardMode='projects',portfolioQuery='',portfolioMode='all',renderTimer,backupTimer,toastTimer,db=null,paletteIndex=0,paletteRows=[],moduleProject='',activeBalances={calculator:null,pressure:null},calculationActivityAt={};
  function initState(){
    suite=read(KEY,{schema:1,projects:{},activity:[],preferences:{actor:'Usuario de este navegador',theme:'light'}});
    if(!suite.projects||!Array.isArray(suite.activity)||!suite.preferences)throw Error('No se pudo leer la configuración de trabajo. Exportá una copia antes de modificarla.');
  }
  function saveSuite(){const old=localStorage.getItem(KEY);if(old)localStorage.setItem(KEY+'.previous',old);suite.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(suite));scheduleBackup();}
  function meta(id){return suite.projects[id]||(suite.projects[id]={finance:{currency:'ARS',lines:[]},source:'Sin definir',quoteOutcome:'Pendiente'});}
  function activity(title,projectId='',detail=''){
    suite.activity.push({id:uid(),title,projectId,detail,actor:suite.preferences.actor||'Usuario de este navegador',at:new Date().toISOString()});
    saveSuite();
  }
  function toast(text){let el=$('suiteToast');if(!el){el=document.createElement('div');el.id='suiteToast';el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000);}
  function guard(fn){try{const r=fn();if(r?.catch)r.catch(e=>toast(e.message));}catch(e){toast(e.message);}}
  function tracker(){return API.snapshot();}
  function balances(){const data=read(BAL,[]);if(!Array.isArray(data))throw Error('El archivo de cálculos no tiene el formato esperado.');return data;}
  function library(){return read(LIB,{schema:1,links:{},audits:[]});}
  function selected(){return tracker().projects.find(p=>p.id===API.selectedId());}
  function projectOptions(current,allowEmpty=true){return (allowEmpty?'<option value="">Sin asignar</option>':'')+tracker().projects.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===current?'selected':'')+'>'+esc(p.name)+'</option>').join('');}
  function linked(id){const lib=library();return balances().filter(b=>lib.links[b.id]===id||tracker().projects.some(p=>p.id===id&&p.sourceBalanceId===b.id));}
  function link(balanceId,projectId){const lib=library();const old=localStorage.getItem(LIB);if(old)localStorage.setItem('thermabot.workspace.previous.v1',old);lib.links[balanceId]=projectId;lib.updatedAt=new Date().toISOString();localStorage.setItem(LIB,JSON.stringify(lib));activity('Cálculo vinculado al proyecto',projectId,balances().find(b=>b.id===balanceId)?.nombre||balanceId);window.dispatchEvent(new Event('thermabot:data'));}
  function openProject(id,tab='Resumen'){projectTab=tab;API.select(id);}
  function setModule(view,balanceId,projectId,newBalance=false){
    moduleProject=projectId||API.selectedId()||'';
    const frame=document.querySelector('#view-'+view+' iframe');
    const id=balanceId||linked(moduleProject)[0]?.id;
    API.navigate(view);
    const url=(view==='calculator'?'index.html':'pressure.html')+'?embedded=1'+(newBalance?'&newBalance='+encodeURIComponent(tracker().projects.find(p=>p.id===moduleProject)?.name||'Nuevo cálculo')+'&revision='+Date.now():id?'&balanceId='+encodeURIComponent(id):'');
    if(frame.getAttribute('src')!==url)frame.src=url;
    renderModule(view);
  }
  function captureChanges(){
    const current=tracker(),assigned=[];
    if(previous){
      for(const collection of ['projects','equipment','milestones','documents']){
        const before=new Map(previous[collection].map(x=>[x.id,x]));
        for(const row of current[collection]){
          const old=before.get(row.id);before.delete(row.id);const title=row.name||row.title||'Registro';
          if(collection==='equipment'&&row.projectId&&(!old||old.projectId!==row.projectId))assigned.push(row);
          if(!old)activity('Creado: '+title,collection==='projects'?row.id:row.projectId,({projects:'Proyecto',equipment:'Equipo',milestones:'Hito',documents:'Documento'})[collection]);
          else {const fields=Object.keys(row).filter(k=>!['updatedAt','createdAt'].includes(k)&&JSON.stringify(row[k])!==JSON.stringify(old[k]));
            if(fields.length)activity('Actualizado: '+title,collection==='projects'?row.id:row.projectId,fields.map(k=>({status:'Estado',stage:'Etapa',progress:'Avance',nextAction:'Próxima acción',targetDate:'Fecha objetivo',dueDate:'Fecha',projectId:'Proyecto',blocker:'Bloqueo',notes:'Observaciones',driveUrl:'Enlace'})[k]||k).join(', '));
          }
          if(collection==='projects'&&row.stage==='Cotización'&&!meta(row.id).quotedAt){meta(row.id).quotedAt=new Date().toISOString();saveSuite();}
        }
        for(const old of before.values())activity('Eliminado: '+(old.name||old.title||'Registro'),collection==='projects'?old.id:old.projectId,collection);
      }
    }
    previous=current;
    if(assigned.length)queueMicrotask(()=>guard(()=>{
      let added=false;
      for(const equipment of assigned){const m=meta(equipment.projectId);m.finance=m.finance||{currency:'ARS',lines:[]};if(!m.finance.lines.some(l=>l.equipmentId===equipment.id)){m.finance.lines.push({id:uid(),title:equipment.name,type:'Costo',quantity:1,unitPrice:0,equipmentId:equipment.id,needsPrice:true});added=true;}}
      if(added){saveSuite();toast('Equipo vinculado: se creó su partida pendiente de precio y el hito de instalación.');}
      const missing=assigned.filter(eq=>!tracker().milestones.some(m=>m.projectId===eq.projectId&&m.notes==='Equipo: '+eq.id));
      if(missing.length)API.mutate(data=>missing.forEach(eq=>data.milestones.push({id:uid(),projectId:eq.projectId,title:'Instalación / puesta en servicio: '+eq.name,type:'Puesta en marcha',status:'Pendiente',dueDate:'',owner:data.projects.find(p=>p.id===eq.projectId)?.owner||'',notes:'Equipo: '+eq.id})));
    }));
    scheduleBackup();scheduleRender();
  }
  function stat(label,value,note,risk=''){return '<article class="card suite-stat '+risk+'"><span>'+label+'</span><strong>'+value+'</strong><small>'+note+'</small></article>';}
  function renderProjectBoard(rows){
    return '<div class="kanban" aria-label="Tablero de proyectos">'+['Activo','Esperando tercero','Bloqueado','Finalizado'].map(lane=>{
      const list=rows.filter(p=>C.projectLane(p)===lane);
      return '<section class="lane" data-board="project" data-lane="'+lane+'"><div class="lane-head"><i></i>'+esc(({Activo:'En marcha',Bloqueado:'Requiere atención',Finalizado:'Finalizados'})[lane]||lane)+'<small>'+list.length+'</small></div>'+list.map(p=>'<article class="board-card" draggable="true" data-drag-project="'+esc(p.id)+'">'+tag(p.establishment||'Proyecto')+'<h3><button class="open-project" data-open-project="'+esc(p.id)+'">'+esc(p.name)+'</button></h3><p>'+esc(p.stage||'Etapa sin definir')+' · '+esc(p.status)+'</p><div class="progress-line"><i style="width:'+Math.max(0,Math.min(100,Number(p.progress)||0))+'%"></i></div><div class="board-footer"><span>'+num(p.progress)+'% completado</span><span>'+esc(p.targetDate||'Sin fecha')+'</span></div><label class="subtle">Mover a<select data-project-status="'+esc(p.id)+'">'+opt(['Activo','En revisión','Esperando tercero','Bloqueado','Urgente','Finalizado','Suspendido'],p.status)+'</select></label></article>').join('')+(list.length?'':empty('Sin proyectos en este estado'))+'</section>';
    }).join('')+'</div>';
  }
  function renderTasks(data,projectId=''){
    const list=C.tasks(data,date(),suite.projects).filter(t=>(!projectId||t.projectId===projectId)&&(!taskQuery||[t.title,t.project,t.owner].join(' ').toLowerCase().includes(taskQuery.toLowerCase())));
    return '<div class="kanban tasks" aria-label="Tablero de tareas">'+['Pendiente','En curso','Cumplido'].map(lane=>{const tasks=list.filter(t=>(t.status==='Cumplido'?'Cumplido':t.status==='En curso'?'En curso':'Pendiente')===lane);return '<section class="lane" data-board="task" data-lane="'+lane+'"><div class="lane-head"><i></i>'+lane+'<small>'+tasks.length+'</small></div>'+tasks.map(t=>'<article class="board-card" draggable="true" data-drag-task="'+esc(t.id)+'">'+tag(t.overdue?'Vencido':t.kind==='next'?'Próxima acción':'Hito',t.overdue?'risk':'neutral')+'<h3><button class="edit-task" data-edit-task="'+esc(t.id)+'" data-task-project="'+esc(t.projectId)+'">'+esc(t.title)+'</button></h3><p>'+esc(t.project)+'</p><div class="board-footer"><span>'+esc(t.owner||'Sin responsable')+'</span><span>'+esc(t.dueDate||'Sin fecha')+'</span></div><label class="subtle">Estado<select data-task-status="'+esc(t.id)+'">'+opt(['Pendiente','En curso','Cumplido'],lane)+'</select></label></article>').join('')+(tasks.length?'':empty('Sin tareas en este estado'))+'</section>';}).join('')+'</div>';
  }
  function renderDashboard(){
    const data=tracker(),tasks=C.tasks(data,date(),suite.projects),pending=tasks.filter(t=>t.status!=='Cumplido'),active=data.projects.filter(C.active);
    const counts={};active.forEach(p=>counts[p.stage||'Sin etapa']=(counts[p.stage||'Sin etapa']||0)+1);const maximum=Math.max(1,...Object.values(counts));
    $('commandCenter').innerHTML='<section class="card suite-banner"><div class="suite-label">BIOINGENIERÍA · TU ESPACIO DE TRABAJO</div><h2>Todo lo que necesitás resolver, acá.</h2><p>'+ (pending.length?'<b>'+pending.length+' pendientes</b>, '+pending.filter(t=>t.overdue).length+' vencidos y '+active.length+' proyectos en marcha. Abrí un proyecto para continuar con su ingeniería.':'Creá un proyecto o conectá tu seguimiento existente para empezar a organizar el trabajo.')+'</p></section><div class="suite-grid">'+stat('Proyectos en marcha',active.length,data.projects.length+' en la cartera')+stat('Tareas pendientes',pending.length,'Próximas acciones e hitos')+stat('Vencidos',pending.filter(t=>t.overdue).length,'Fechas que necesitan atención','risk')+stat('Esperando respuesta',active.filter(p=>p.status==='Esperando tercero').length,'Seguimiento de terceros')+'</div><div class="suite-two"><section class="card"><div class="suite-head"><div><h3>De la idea a la obra</h3><span class="subtle">Tocá una etapa para filtrar el tablero.</span></div>'+(chartFilter?'<button id="clearStage">Ver todas</button>':'')+'</div><div class="bar-chart">'+Object.entries(counts).map(([stage,count])=>'<div class="chart-row '+(stage===chartFilter?'selected':'')+'"><button data-chart-stage="'+esc(stage)+'">'+esc(stage)+'</button><div class="chart-track"><i style="width:'+count/maximum*100+'%"></i></div><b>'+count+'</b></div>').join('')+(active.length?'':empty('El gráfico aparece cuando hay proyectos.'))+'</div></section><section class="card"><h3>Lo primero para hoy</h3><div class="suite-list">'+pending.slice(0,3).map(t=>'<article><div class="suite-row"><button data-open-project="'+esc(t.projectId)+'" data-open-tab="Hitos">'+esc(t.title)+'</button>'+tag(t.overdue?'Vencido':t.dueDate||'Sin fecha',t.overdue?'risk':'neutral')+'</div><p>'+esc(t.project)+'</p></article>').join('')+(pending.length?'':empty('Sin pendientes registrados.'))+'</div></section></div><div class="suite-head"><div><h2>Tu trabajo en movimiento</h2><p>Arrastrá una tarjeta o usá su selector para cambiar el estado.</p></div><div class="actions"><button id="showProjectBoard" class="'+(boardMode==='projects'?'primary':'')+'">Proyectos</button><button id="showTaskBoard" class="'+(boardMode==='tasks'?'primary':'')+'">Pendientes · '+pending.length+'</button><button id="newDashboardTask">+ Tarea</button></div></div>'+ (boardMode==='tasks'?'<div class="suite-toolbar"><label>Proyecto<select id="taskProjectFilter">'+projectOptions(taskProject).replace('Sin asignar','Todos')+'</select></label></div>'+renderTasks(data,taskProject):renderProjectBoard(data.projects.filter(p=>p.status!=='Suspendido'&&(!chartFilter||p.stage===chartFilter)))) ;
    $('showProjectBoard').onclick=()=>{boardMode='projects';renderDashboard();bind();};$('showTaskBoard').onclick=()=>{boardMode='tasks';renderDashboard();bind();};$('newDashboardTask').onclick=()=>API.editMilestone();
    $('taskProjectFilter')?.addEventListener('change',e=>{taskProject=e.target.value;renderDashboard();bind();});$('clearStage')?.addEventListener('click',()=>{chartFilter='';renderDashboard();bind();});
    document.querySelectorAll('[data-chart-stage]').forEach(b=>b.onclick=()=>{chartFilter=chartFilter===b.dataset.chartStage?'':b.dataset.chartStage;boardMode='projects';renderDashboard();bind();});
  }
  function renderPortfolio(){
    const data=tracker();const list=data.projects.filter(p=>(portfolioMode==='all'||(portfolioMode==='active'?C.active(p):p.status==='Finalizado'))&&[p.name,p.establishment,p.system,p.sector].join(' ').toLowerCase().includes(portfolioQuery.toLowerCase()));
    $('projectPortfolio').innerHTML='<div class="suite-head"><div><div class="suite-label">CARTERA DE TRABAJO</div><h2>Proyectos</h2><p>Una ficha para todo: ingeniería, equipos, documentos, tareas y números.</p></div><button class="primary" id="newPortfolioProject">+ Proyecto</button></div><div class="suite-toolbar"><label style="flex:1">Buscar<input id="portfolioSearch" placeholder="Proyecto, establecimiento o sistema" value="'+esc(portfolioQuery)+'"></label><label>Mostrar<select id="portfolioMode">'+opt(['Todos','En marcha','Finalizados'],({all:'Todos',active:'En marcha',finished:'Finalizados'})[portfolioMode])+'</select></label></div><div class="project-cards">'+list.map(p=>'<article class="card"><div class="suite-row">'+tag(p.establishment||'Establecimiento sin definir')+tag(p.status,['Urgente','Bloqueado'].includes(p.status)?'risk':'neutral')+'</div><h3><button data-open-project="'+esc(p.id)+'">'+esc(p.name)+'</button></h3><p class="subtle">'+esc(p.system||'Sistema por definir')+' · '+esc(p.stage)+'</p><div class="progress-line"><i style="width:'+Math.max(0,Math.min(100,Number(p.progress)||0))+'%"></i></div><div class="board-footer"><span>'+num(p.progress)+'% de avance</span><span>'+linked(p.id).length+' cálculos</span></div><p class="subtle">'+esc(p.nextAction||'Definí la próxima acción al abrir el proyecto.')+'</p></article>').join('')+'</div>'+(list.length?'':empty('No hay proyectos en esta selección.'));
    $('newPortfolioProject').onclick=()=>API.editProject();$('portfolioSearch').oninput=e=>{portfolioQuery=e.target.value;const pos=e.target.selectionStart;renderPortfolio();bind();$('portfolioSearch').focus();$('portfolioSearch').setSelectionRange(pos,pos);};$('portfolioMode').onchange=e=>{portfolioMode=({'Todos':'all','En marcha':'active','Finalizados':'finished'})[e.target.value];renderPortfolio();bind();};
  }
  function renderWorkspace(){
    const p=selected();if(!p){$('projectWorkspace').innerHTML=empty('Seleccioná un proyecto de la cartera.');return;}
    const tabs=['Resumen','Cálculos','Equipos','Documentos','Hitos','Finanzas','Actividad'],data=tracker(),m=meta(p.id),fin=C.financial(m.finance);
    let body='';
    if(projectTab==='Resumen')body='<div class="suite-grid">'+stat('Avance',num(p.progress)+'%',p.stage||'Etapa sin definir')+stat('Cálculos',linked(p.id).length,'Balances y redes guardadas')+stat('Equipos',data.equipment.filter(e=>e.projectId===p.id).length,'Asignados al proyecto')+stat('Pendientes',C.tasks(data,date(),suite.projects).filter(t=>t.projectId===p.id&&t.status!=='Cumplido').length,'Acciones e hitos')+'</div><div class="suite-two"><section class="card"><h3>Próximo paso</h3><p>'+esc(p.nextAction||'Todavía no definiste la próxima acción.')+'</p><div class="actions">'+tag(p.targetDate||'Sin fecha objetivo','neutral')+tag(p.owner||'Sin responsable','neutral')+'</div><p class="subtle">Bloqueo / espera: '+esc(p.blocker||'Sin bloqueos registrados')+'</p><button data-edit-project="'+esc(p.id)+'">Actualizar seguimiento</button></section><section class="card"><h3>Ficha técnica</h3><p>'+esc(p.establishment||'')+' · '+esc(p.sector||'')+'</p><p>Sistema: '+esc(p.system||'Por definir')+'</p><p class="subtle">Expediente: '+esc(p.expediente||'Sin referencia')+' · Planos: '+esc(p.drawingRevision||'Sin revisión')+'</p><p class="subtle">'+esc(p.notes||'Sin observaciones')+'</p></section></div>'+ (p.status==='Finalizado'?'<section class="card"><h3>Proyecto finalizado</h3><p>Prepará una ficha técnica con el resultado y fotos autorizadas para compartir tu trabajo.</p><button id="caseOffer" class="primary">Crear caso de éxito</button></section>':p.stage==='Cotización'?'<section class="card"><h3>Seguimiento de la cotización</h3><p>Registrá su resultado y entregá al cliente una ficha de avance.</p><button id="quoteOffer">Registrar cotización</button></section>':'');
    if(projectTab==='Cálculos')body='<div class="suite-head"><h3>Ingeniería del proyecto</h3><div class="actions"><button data-new-balance="true" data-tool="calculator" data-tool-project="'+esc(p.id)+'">+ Balance térmico</button><button data-tool="pressure" data-tool-project="'+esc(p.id)+'">Presurización</button><button id="compareProject">Comparar</button><button id="assignCalculation">Vincular existente</button></div></div><div class="suite-list">'+linked(p.id).map(b=>'<article><div class="suite-row"><div><h3>'+esc(b.nombre)+'</h3><p>'+b.ambientes.length+' ambientes · '+esc(b.condiciones?.ciudad||'')+(b.pressureNetwork?' · Con red de presión':'')+'</p></div><div class="actions"><button data-tool="calculator" data-balance="'+esc(b.id)+'" data-tool-project="'+esc(p.id)+'">Continuar balance</button><button data-tool="pressure" data-balance="'+esc(b.id)+'" data-tool-project="'+esc(p.id)+'">Red de presión</button><button data-client-pdf="'+esc(b.id)+'">PDF</button></div></div></article>').join('')+'</div>'+(!linked(p.id).length?empty('Creá un balance para este proyecto o vinculá un cálculo guardado.'):'' );
    if(projectTab==='Equipos')body='<div class="suite-head"><h3>Equipos asignados</h3><div class="actions"><button id="assignEquipment">Asignar del catálogo</button><button id="createEquipment">+ Equipo</button></div></div>'+equipmentList(data.equipment.filter(e=>e.projectId===p.id),true);
    if(projectTab==='Documentos')body='<div class="suite-head"><h3>Documentación del proyecto</h3><button id="createDocument">+ Documento</button></div><div class="suite-list">'+data.documents.filter(d=>d.projectId===p.id).map(d=>'<article><div class="suite-row"><div><h3>'+esc(d.title)+'</h3><p>'+esc(d.type)+' · '+esc(d.revision)+' · '+esc(d.status)+'</p></div><div class="actions"><button data-preview-doc="'+esc(d.id)+'">Previsualizar</button><button data-edit-doc="'+esc(d.id)+'">Editar</button></div></div></article>').join('')+'</div>'+(!data.documents.some(d=>d.projectId===p.id)?empty('Adjuntá las referencias de planos, pliegos e informes de este proyecto.'):'' );
    if(projectTab==='Hitos')body='<div class="suite-head"><div><h3>Hitos y próximas acciones</h3><p>Los cambios se reflejan también en el tablero de inicio.</p></div><button id="createMilestone">+ Tarea / hito</button></div>'+renderTasks(data,p.id);
    if(projectTab==='Finanzas')body=financeHtml(p,m,fin);
    if(projectTab==='Actividad')body=feed(p.id);
    $('projectWorkspace').innerHTML='<div class="suite-head"><button id="backToPortfolio">← Todos los proyectos</button><div class="actions"><button id="clientSnapshot">Ficha para cliente</button><button data-edit-project="'+esc(p.id)+'">Editar proyecto</button></div></div><div class="workspace-hero"><div class="suite-label">'+esc(p.establishment||'PROYECTO')+' · '+esc(p.sector||'HVAC')+'</div><h2>'+esc(p.name)+'</h2><div class="actions">'+tag(p.stage,'neutral')+tag(p.status)+tag(p.owner||'Sin responsable','neutral')+'</div></div><nav class="workspace-tabs" aria-label="Secciones del proyecto">'+tabs.map(t=>'<button data-project-tab="'+t+'" class="'+(projectTab===t?'active':'')+'">'+t+'</button>').join('')+'</nav><div class="workspace-body">'+body+'</div>';
    $('backToPortfolio').onclick=()=>API.navigate('projects');document.querySelectorAll('[data-project-tab]').forEach(b=>b.onclick=()=>{projectTab=b.dataset.projectTab;renderWorkspace();bind();});
    $('clientSnapshot').onclick=()=>clientSheet(p);$('createEquipment')?.addEventListener('click',()=>API.editEquipment());$('createDocument')?.addEventListener('click',()=>API.editDocument());$('createMilestone')?.addEventListener('click',()=>API.editMilestone());$('assignEquipment')?.addEventListener('click',()=>assignEquipment(p));$('compareProject')?.addEventListener('click',()=>compareCalculations(linked(p.id)));$('assignCalculation')?.addEventListener('click',()=>assignCalculation(p));$('addFinanceLine')?.addEventListener('click',()=>financeLine(p));$('editCRM')?.addEventListener('click',()=>crm(p));$('caseOffer')?.addEventListener('click',()=>caseStudy(p));$('quoteOffer')?.addEventListener('click',()=>crm(p));
    document.querySelectorAll('[data-remove-finance]').forEach(b=>b.onclick=()=>{if(!confirm('¿Eliminar esta partida?'))return;m.finance.lines=m.finance.lines.filter(l=>l.id!==b.dataset.removeFinance);activity('Partida financiera eliminada',p.id);renderWorkspace();bind();});
  }
  function financeHtml(p,m,f){return '<div class="suite-head"><div><h3>Presupuesto y resultado</h3><p>Moneda: '+esc(m.finance?.currency||'ARS')+' · Los ingresos representan cobros registrados.</p></div><div class="actions"><button id="editCRM">Cliente y cotización</button><button id="addFinanceLine" class="primary">+ Partida</button></div></div><div class="suite-grid">'+stat('Presupuestado',num(f.quoted),m.finance?.currency||'ARS')+stat('Costos',num(f.cost),f.pendingPrices?f.pendingPrices+' partidas pendientes de precio':'Compras y ejecución')+stat('Ingresos',num(f.revenue),'Cobros registrados')+stat('Resultado',f.pendingPrices?'Parcial':num(f.profit),f.pendingPrices?'Completá los precios pendientes':f.margin===null?'Sin ingresos para calcular margen':num(f.margin)+'% de margen')+'</div><div class="card" style="margin-top:18px;overflow:auto"><table><thead><tr><th>Tipo</th><th>Concepto</th><th>Cantidad</th><th>Unitario</th><th>Total</th><th></th></tr></thead><tbody>'+(m.finance?.lines||[]).map(l=>'<tr><td>'+esc(l.type)+'</td><td>'+esc(l.title)+(l.needsPrice?' · Precio pendiente':'')+'</td><td>'+num(l.quantity)+'</td><td>'+(l.needsPrice?'—':num(l.unitPrice))+'</td><td>'+(l.needsPrice?'—':num(Number(l.quantity)*Number(l.unitPrice)))+'</td><td><button data-remove-finance="'+esc(l.id)+'">Eliminar</button></td></tr>').join('')+'</tbody></table>'+(!m.finance?.lines?.length?empty('Registrá partidas para conocer el presupuesto y el resultado.'):'' )+'</div><p class="subtle">Origen: '+esc(m.source||'Sin definir')+' · Cotización: '+esc(m.quoteOutcome||'Pendiente')+'. Estos datos se incluyen en la copia completa de la aplicación.</p>';}
  function equipmentList(list,inProject=false){return '<div class="suite-list">'+list.map(e=>'<article><div class="suite-row"><div><h3>'+esc(e.name)+'</h3><p>'+esc(e.model||'Modelo por definir')+' · '+esc(e.capacity||'Sin capacidad registrada')+' · '+esc(e.status)+'</p><p>'+esc(tracker().projects.find(p=>p.id===e.projectId)?.name||'Sin asignar')+'</p></div><div class="actions"><button data-edit-eq="'+esc(e.id)+'">Editar</button>'+(inProject?'<button data-equipment-cost="'+esc(e.id)+'">Costo / hito</button>':'<button data-assign-eq="'+esc(e.id)+'">Asignar</button>')+'</div></div></article>').join('')+'</div>'+(list.length?'':empty('Todavía no hay equipos en esta selección.'));}
  function dialog(title,html){let d=$('suiteDialog');if(!d){d=document.createElement('dialog');d.id='suiteDialog';d.className='suite-dialog suite';document.body.append(d);}d.innerHTML='<div class="dialog-head"><h2>'+esc(title)+'</h2><button id="closeSuiteDialog" aria-label="Cerrar">×</button></div>'+html;$('closeSuiteDialog').onclick=()=>d.close();if(!d.open)d.showModal();return d;}
  function financeLine(p,equipment=null){
    const d=dialog(equipment?'Costo e instalación del equipo':'Nueva partida','<form id="financeForm" class="suite-modal-grid"><label class="wide">Concepto<input name="title" required value="'+esc(equipment?.name||'')+'"></label><label>Tipo<select name="type">'+opt(['Presupuesto','Costo','Ingreso'],equipment?'Costo':'Presupuesto')+'</select></label><label>Cantidad<input name="quantity" type="number" min="0.01" step="any" value="1" required></label><label>Precio unitario<input name="unitPrice" type="number" min="0" step="any" required></label><label>Moneda<select name="currency">'+opt(['ARS','USD','EUR'],meta(p.id).finance?.currency||'ARS')+'</select></label>'+(equipment?'<label class="wide"><span><input name="createMilestone" type="checkbox" checked> Crear hito para instalación / puesta en servicio</span></label><label>Fecha del hito<input name="dueDate" type="date"></label>':'')+'<div class="wide suite-notice">Usá una sola moneda por proyecto. El total se calcula como cantidad × precio unitario.</div><button class="primary wide" type="submit">Guardar partida</button></form>');
    $('financeForm').onsubmit=e=>guard(()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const m=meta(p.id);m.finance=m.finance||{lines:[],currency:f.currency};if(m.finance.lines.length&&m.finance.currency!==f.currency)throw Error('El proyecto ya tiene partidas en '+m.finance.currency+'. Usá esa moneda para mantener los totales coherentes.');m.finance.currency=f.currency;const existing=equipment?m.finance.lines.find(l=>l.equipmentId===equipment.id&&l.needsPrice):null;const line={id:existing?.id||uid(),title:f.title,type:f.type,quantity:Number(f.quantity),unitPrice:Number(f.unitPrice),equipmentId:equipment?.id||'',needsPrice:false};if(existing)Object.assign(existing,line);else m.finance.lines.push(line);activity('Partida financiera registrada',p.id,f.title);if(equipment&&f.createMilestone)API.mutate(data=>{const hit=data.milestones.find(m=>m.projectId===p.id&&m.notes==='Equipo: '+equipment.id);if(hit){if(f.dueDate)hit.dueDate=f.dueDate;}else data.milestones.push({id:uid(),projectId:p.id,title:'Instalación / puesta en servicio: '+equipment.name,type:'Puesta en marcha',status:'Pendiente',dueDate:f.dueDate,owner:p.owner||'',notes:'Equipo: '+equipment.id});});d.close();renderWorkspace();bind();});
  }
  function crm(p){const m=meta(p.id),d=dialog('Cliente y cotización','<form id="crmForm" class="suite-modal-grid"><label>Cliente / contacto<input name="contact" value="'+esc(m.contact||'')+'"></label><label>Origen del proyecto<select name="source">'+opt(['Sin definir','Recomendación','Cliente recurrente','Web','LinkedIn','Licitación','Otro'],m.source||'Sin definir')+'</select></label><label>Resultado de cotización<select name="quoteOutcome">'+opt(['Pendiente','Ganada','Perdida'],m.quoteOutcome||'Pendiente')+'</select></label><label>Fecha de cotización<input name="quotedAt" type="date" value="'+esc((m.quotedAt||'').slice(0,10))+'"></label><button class="primary wide">Guardar</button></form>');$('crmForm').onsubmit=e=>{e.preventDefault();Object.assign(m,Object.fromEntries(new FormData(e.target)));activity('Datos comerciales actualizados',p.id);d.close();renderWorkspace();renderMarketing();bind();};}
  function assignEquipment(p,eqId=''){
    const data=tracker(),d=dialog('Asignar equipo al proyecto','<form id="assignEquipmentForm" class="suite-modal-grid"><label class="wide">Equipo<select name="equipmentId">'+data.equipment.map(e=>'<option value="'+esc(e.id)+'" '+(e.id===eqId?'selected':'')+'>'+esc(e.name)+' · '+esc(data.projects.find(p=>p.id===e.projectId)?.name||'Sin asignar')+'</option>').join('')+'</select></label><label class="wide">Proyecto<select name="projectId">'+projectOptions(p?.id||'')+'</select></label><p class="wide suite-notice">La asignación cambia el proyecto del equipo. Después podés registrar su costo y el hito de instalación desde el proyecto.</p><button class="primary wide" '+(!data.equipment.length?'disabled':'')+'>Asignar equipo</button></form>');$('assignEquipmentForm').onsubmit=e=>guard(()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));API.mutate(data=>{const eq=data.equipment.find(x=>x.id===f.equipmentId);if(eq)eq.projectId=f.projectId;});d.close();if(f.projectId)openProject(f.projectId,'Equipos');toast('Equipo asignado. Registrá su costo y fecha con “Costo / hito”.');});
  }
  function assignCalculation(p){const d=dialog('Vincular cálculo existente','<form id="linkCalculationForm"><label>Cálculo<select name="balanceId">'+balances().map(b=>'<option value="'+esc(b.id)+'">'+esc(b.nombre)+'</option>').join('')+'</select></label><p class="suite-notice">El cálculo aparecerá acá y en Cálculos guardados.</p><button class="primary" '+(!balances().length?'disabled':'')+'>Vincular a este proyecto</button></form>');$('linkCalculationForm').onsubmit=e=>guard(()=>{e.preventDefault();link(new FormData(e.target).get('balanceId'),p.id);d.close();renderWorkspace();bind();});}
  function previewDocument(id){const d=tracker().documents.find(x=>x.id===id);if(!d)return;const url=C.previewUrl(d.driveUrl);dialog(d.title,url?'<iframe class="preview-document" title="Vista previa de '+esc(d.title)+'" src="'+esc(url)+'" referrerpolicy="no-referrer" allow="fullscreen"></iframe><p class="subtle">La vista depende de los permisos de Drive y del formato. Drive puede pedir iniciar sesión. Los DWG necesitan una vista compatible o una copia PDF.</p>':empty('Este enlace no permite una vista incrustada. Para planos DWG, adjuntá también una versión PDF.'));}
  function calculateRows(b){return (b.ambientes||[]).map(a=>THERMABOT_ENGINE.calcular_ambiente(a,b.condiciones||{},b.cerramientos||[]));}
  function compareCalculations(list=balances()){
    const d=dialog('Comparar cálculos','<p class="subtle">Comparación de cargas calculadas por ambiente. La suma de máximos no aplica diversidad ni simultaneidad entre locales.</p><div class="suite-toolbar">'+list.map(b=>'<label><span><input type="checkbox" data-compare-balance="'+esc(b.id)+'" checked> '+esc(b.nombre)+'</span></label>').join('')+'</div><div id="compareResults" class="suite-compare"></div>');
    const render=()=>{const chosen=[...d.querySelectorAll('[data-compare-balance]:checked')].map(x=>list.find(b=>b.id===x.dataset.compareBalance));const summaries=chosen.map(b=>{const rs=calculateRows(b),sum=k=>rs.reduce((s,r)=>s+Number(r[k]||0),0);return {b,rs,total:sum('total_kw'),sensible:sum('sensible_total_kw'),latent:sum('latente_total_kw'),area:sum('superficie_m2'),supply:sum('caudal_impulsion_m3h')};});$('compareResults').innerHTML='<table><thead><tr><th>Dato</th>'+summaries.map(x=>'<th>'+esc(x.b.nombre)+'</th>').join('')+'</tr></thead><tbody>'+[['Ciudad',x=>esc(x.b.condiciones?.ciudad||'')],['Ambientes',x=>x.rs.length],['Superficie · m²',x=>num(x.area)],['Carga total · kW',x=>num(x.total)],['Sensible · kW',x=>num(x.sensible)],['Latente · kW',x=>num(x.latent)],['Impulsión · m³/h',x=>num(x.supply)]].map(([label,get])=>'<tr><th>'+label+'</th>'+summaries.map(x=>'<td>'+get(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';};d.querySelectorAll('[data-compare-balance]').forEach(c=>c.onchange=()=>guard(render));guard(render);
  }
  function printPage(title,body){
    const frame=document.createElement('iframe');frame.style.cssText='position:fixed;left:-10000px;width:900px;height:1000px';frame.title='Informe para imprimir';
    frame.onload=()=>{const win=frame.contentWindow;win.addEventListener('afterprint',()=>setTimeout(()=>frame.remove(),500),{once:true});win.focus();win.print();};
    frame.srcdoc='<!doctype html><html lang="es"><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>@page{size:A4;margin:18mm}body{font:13px Arial,sans-serif;color:#16392c;line-height:1.65}header{border-bottom:3px solid #256e56;padding:10px 0;margin-bottom:25px}h1{font-size:26px}h2{font-size:19px}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:left}small{color:#65796d}img{max-width:100%;max-height:260px}footer{margin-top:35px;border-top:1px solid #ddd;padding:12px;font-size:10px}</style></head><body><header><b>THERMABOT · BIOINGENIERÍA</b><br><small>Gestión técnica HVAC · '+new Date().toLocaleDateString('es-AR')+'</small></header><h1>'+esc(title)+'</h1>'+body+'<footer>Preparado por '+esc(suite.preferences.actor||'Bioingeniería')+' · THERMABOT</footer></body></html>';
    document.body.append(frame);toast('Elegí “Guardar como PDF” en el diálogo de impresión.');
  }
  function clientSheet(p){const snapshot=C.publicSnapshot(p,tracker());dialog('Ficha para el cliente','<p>Incluye el avance, la etapa y los hitos. Las notas internas, los bloqueos y los costos quedan fuera de esta ficha.</p><div class="suite-notice"><b>'+esc(snapshot.name)+'</b><p>'+esc(snapshot.establishment)+' · '+esc(snapshot.stage)+' · '+num(snapshot.progress)+'% de avance</p></div><p class="subtle">En esta versión la ficha se comparte como PDF. Los enlaces privados y el portal del cliente requieren un servicio con control de acceso.</p><button id="printClientSheet" class="primary">Generar PDF para compartir</button>');$('printClientSheet').onclick=()=>printPage(snapshot.name,'<p>'+esc(snapshot.establishment)+' · '+esc(snapshot.stage)+'</p><h2>Avance: '+num(snapshot.progress)+'%</h2><p>Estado: '+esc(snapshot.status)+'</p><table><tr><th>Hito</th><th>Estado</th><th>Fecha</th></tr>'+snapshot.milestones.map(m=>'<tr><td>'+esc(m.title)+'</td><td>'+esc(m.status)+'</td><td>'+esc(m.dueDate||'Por definir')+'</td></tr>').join('')+'</table>');}
  function balancePdf(id){const b=balances().find(b=>b.id===id);if(!b)return;const findings=TBWorkspace.audit(b).findings;if(findings.some(f=>f.severity==='CRÍTICO')){dialog('Revisá los datos antes de emitir','<p>Hay entradas críticas que necesitan corregirse.</p>'+findings.filter(f=>f.severity==='CRÍTICO').map(f=>'<p><b>'+esc(f.subject)+'</b>: '+esc(f.problem)+'</p>').join(''));return;}const rs=calculateRows(b);printPage('Balance térmico · '+b.nombre,'<p>Ciudad: '+esc(b.condiciones?.ciudad)+' · Exterior: '+num(b.condiciones?.tempExterior)+' °C · Interior: '+num(b.condiciones?.tempInterior)+' °C</p><table><tr><th>Ambiente</th><th>m²</th><th>Sensible kW</th><th>Latente kW</th><th>Total kW</th><th>Impulsión m³/h</th></tr>'+rs.map(r=>'<tr><td>'+esc(r.nombre)+'</td><td>'+num(r.superficie_m2)+'</td><td>'+num(r.sensible_total_kw)+'</td><td>'+num(r.latente_total_kw)+'</td><td>'+num(r.total_kw)+'</td><td>'+num(r.caudal_impulsion_m3h)+'</td></tr>').join('')+'</table><h2>Suma de cargas por ambiente: '+num(rs.reduce((s,r)=>s+r.total_kw,0))+' kW</h2><p><small>Suma de máximos individuales sin diversidad. Cálculo estimativo con condiciones y materiales cargados; completar la verificación de ingeniería y la selección de equipos.</small></p>'+rs.flatMap(r=>r.alertas||[]).map(a=>'<p>'+esc(a)+'</p>').join(''));activity('Informe térmico preparado',library().links[id]||'',b.nombre);}
  function caseStudy(p){const m=meta(p.id);dialog('Caso de éxito','<form id="caseForm" class="suite-modal-grid"><label class="wide">Problema que resolviste<textarea name="challenge" required>'+esc(m.caseStudy?.challenge||'')+'</textarea></label><label class="wide">Solución y resultado comprobado<textarea name="result" required>'+esc(m.caseStudy?.result||'')+'</textarea></label><label class="wide">Fotografías autorizadas<input id="casePhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="wide"><span><input name="permission" type="checkbox" required> Puedo compartir estos datos y estas imágenes.</span></label><button class="primary wide">Preparar ficha técnica</button></form>');$('caseForm').onsubmit=e=>guard(async()=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const photos=[...$('casePhotos').files];if(photos.length>4||photos.some(x=>x.size>2000000))throw Error('Usá hasta 4 fotos de menos de 2 MB cada una.');const urls=await Promise.all(photos.map(file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('No se pudo leer una foto.'));r.readAsDataURL(file);})));m.caseStudy={challenge:f.challenge,result:f.result,preparedAt:new Date().toISOString()};activity('Caso de éxito preparado',p.id);printPage('Caso de éxito · '+p.name,'<p>'+esc(p.system)+' · '+esc(p.establishment)+'</p><h2>El desafío</h2><p>'+esc(f.challenge)+'</p><h2>La solución y el resultado</h2><p>'+esc(f.result)+'</p>'+urls.map(u=>'<img src="'+esc(u)+'" alt="Fotografía del proyecto">').join(''));$('suiteDialog').close();});}
  function feed(projectId=''){const list=suite.activity.filter(a=>!projectId||a.projectId===projectId).slice().reverse();return '<p class="subtle">Historial de esta aplicación y este navegador. El nombre identifica al operador configurado; no es una firma verificada.</p><div class="card">'+list.slice(0,200).map(a=>'<article class="activity-item"><time>'+esc(new Date(a.at).toLocaleString('es-AR'))+' · '+esc(a.actor)+'</time><strong>'+esc(a.title)+'</strong><p>'+esc(a.detail)+'</p>'+(a.projectId?'<button data-open-project="'+esc(a.projectId)+'">'+esc(tracker().projects.find(p=>p.id===a.projectId)?.name||'Proyecto archivado / eliminado')+'</button>':'')+'</article>').join('')+(list.length?'':empty('Las próximas modificaciones aparecerán acá.'))+'</div>';}
  function renderActivity(){$('activityFeed').innerHTML='<div class="suite-head"><div><h2>Actividad</h2><p>Quién registró cada cambio y cuándo.</p></div><button id="exportActivity">Descargar historial</button></div>'+feed();$('exportActivity').onclick=()=>download(suite.activity,'THERMABOT-actividad.json');}
  function renderMarketing(){
    const data=tracker(),m=C.marketing(data,suite.projects),sources={};data.projects.forEach(p=>{const src=meta(p.id).source||'Sin definir';sources[src]=(sources[src]||0)+1;});const max=Math.max(1,...Object.values(sources));const currencies=[...new Set(Object.values(suite.projects).filter(x=>x.finance?.lines?.length).map(x=>x.finance.currency))];
    $('marketingCenter').innerHTML='<div class="suite-head"><div><div class="suite-label">GESTIÓN COMERCIAL</div><h2>Resultados y marketing</h2><p>Indicadores calculados con los datos comerciales que registres en cada proyecto.</p></div></div><div class="suite-grid">'+stat('Cotizaciones registradas',m.quoted,'Con fecha o etapa Cotización')+stat('Ganadas',m.won,'Resultado indicado como Ganada')+stat('Conversión',m.conversion===null?'—':num(m.conversion)+'%',m.resolved+' cotizaciones resueltas; excluye pendientes')+stat('Proyectos finalizados',data.projects.filter(p=>p.status==='Finalizado').length,'Disponibles para crear casos de éxito')+'</div><div class="suite-two"><section class="card"><h3>Origen de los proyectos</h3><div class="bar-chart">'+Object.entries(sources).map(([label,value])=>'<div class="chart-row"><span>'+esc(label)+'</span><div class="chart-track"><i style="width:'+value/max*100+'%"></i></div><b>'+value+'</b></div>').join('')+'</div></section><section class="card"><h3>Resultado por tipo de obra</h3>'+ (currencies.length>1?'<p class="suite-notice">Hay distintas monedas. Revisá el resultado dentro de cada proyecto; no se suman importes de monedas diferentes.</p>':'<p class="subtle">Ingresos menos costos registrados · '+esc(currencies[0]||'ARS')+'</p><table><tr><th>Sistema</th><th>Ingresos</th><th>Costos</th><th>Resultado</th></tr>'+m.groups.filter(g=>g.revenue||g.cost).map(g=>'<tr><td>'+esc(g.name)+'</td><td>'+num(g.revenue)+'</td><td>'+num(g.cost)+'</td><td>'+num(g.profit)+'</td></tr>').join('')+'</table>')+'</section></div><div class="suite-head"><h3>Proyectos para mostrar</h3></div><div class="project-cards">'+data.projects.filter(p=>p.status==='Finalizado').map(p=>'<article class="card"><h3>'+esc(p.name)+'</h3><p class="subtle">'+esc(p.system)+' · '+esc(p.establishment)+'</p><button data-case-project="'+esc(p.id)+'">Preparar caso de éxito</button></article>').join('')+'</div>';
  }
  function renderModule(view){
    const p=tracker().projects.find(p=>p.id===(moduleProject||API.selectedId()));if(!moduleProject&&p)moduleProject=p.id;
    $(view==='calculator'?'calculatorContext':'pressureContext').innerHTML='<label>Proyecto de seguimiento<select id="'+view+'Project">'+projectOptions(moduleProject)+'</select></label><button id="'+view+'Save" class="primary">'+(p?'Guardar en '+esc(p.name):'Guardar cálculo')+'</button><button id="'+view+'PDF">Generar PDF para el cliente</button><button id="'+view+'Compare">Comparar cálculos</button><span class="subtle">Cambios guardados en este navegador.</span>';
    $(view+'Project').onchange=e=>{moduleProject=e.target.value;renderModule(view);};$(view+'Save').onclick=()=>{const frame=document.querySelector('#view-'+view+' iframe');frame.contentWindow.postMessage({type:'thermabot:save',projectId:moduleProject},location.origin);};$(view+'PDF').onclick=()=>{if(view==='pressure'){document.querySelector('#view-pressure iframe').contentWindow.postMessage({type:'thermabot:print'},location.origin);toast('Elegí Guardar como PDF.');return;}const id=activeBalances.calculator||linked(moduleProject)[0]?.id;if(!id){toast('Guardá el cálculo para preparar el informe.');return;}balancePdf(id);};$(view+'Compare').onclick=()=>compareCalculations();
  }
  function bind(){
    const createLink=$('view-balances')?.querySelector('.heading a');if(createLink)createLink.onclick=e=>{e.preventDefault();setModule('calculator');};
    document.querySelectorAll('[data-open-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.openProject,b.dataset.openTab||'Resumen'));
    document.querySelectorAll('[data-edit-project]').forEach(b=>b.onclick=()=>API.editProject(b.dataset.editProject));
    document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setModule(b.dataset.tool,b.dataset.balance,b.dataset.toolProject,!!b.dataset.newBalance));
    document.querySelectorAll('[data-edit-eq]').forEach(b=>b.onclick=()=>API.editEquipment(b.dataset.editEq));
    document.querySelectorAll('[data-assign-eq]').forEach(b=>b.onclick=()=>assignEquipment(null,b.dataset.assignEq));
    document.querySelectorAll('[data-equipment-cost]').forEach(b=>b.onclick=()=>financeLine(selected(),tracker().equipment.find(e=>e.id===b.dataset.equipmentCost)));
    document.querySelectorAll('[data-preview-doc]').forEach(b=>b.onclick=()=>previewDocument(b.dataset.previewDoc));
    document.querySelectorAll('[data-edit-doc]').forEach(b=>b.onclick=()=>API.editDocument(b.dataset.editDoc));
    document.querySelectorAll('[data-client-pdf]').forEach(b=>b.onclick=()=>guard(()=>balancePdf(b.dataset.clientPdf)));
    document.querySelectorAll('[data-case-project]').forEach(b=>b.onclick=()=>caseStudy(tracker().projects.find(p=>p.id===b.dataset.caseProject)));
    document.querySelectorAll('[data-edit-task]').forEach(b=>b.onclick=()=>b.dataset.editTask.startsWith('next:')?API.editProject(b.dataset.taskProject):API.editMilestone(b.dataset.editTask));
    document.querySelectorAll('[data-project-status]').forEach(b=>b.onchange=()=>moveProject(b.dataset.projectStatus,b.value));
    document.querySelectorAll('[data-task-status]').forEach(b=>b.onchange=()=>moveTask(b.dataset.taskStatus,b.value));
    document.querySelectorAll('[draggable=true]').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('application/thermabot',JSON.stringify({kind:el.dataset.dragProject?'project':'task',id:el.dataset.dragProject||el.dataset.dragTask}));e.dataTransfer.effectAllowed='move';});
    document.querySelectorAll('.lane').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over');};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>guard(()=>{e.preventDefault();el.classList.remove('drag-over');const raw=e.dataTransfer.getData('application/thermabot');if(!raw)return;const payload=JSON.parse(raw);if(payload.kind!==el.dataset.board)return;if(payload.kind==='project')moveProject(payload.id,el.dataset.lane);else moveTask(payload.id,el.dataset.lane);});});
    // Keep the saved calculations page inside the same navigation flow.
    $('balanceList')?.querySelectorAll('a').forEach(a=>{if(a.textContent.includes('Abrir'))a.onclick=e=>{e.preventDefault();setModule('calculator',new URL(a.href).searchParams.get('balanceId'));};});
  }
  function moveProject(id,status){if(!['Activo','En revisión','Esperando tercero','Bloqueado','Urgente','Finalizado','Suspendido'].includes(status))return;API.mutate(data=>{const p=data.projects.find(p=>p.id===id);if(p){p.status=status;p.updatedAt=new Date().toISOString();}});toast('Estado del proyecto actualizado.');}
  function moveTask(id,status){if(!['Pendiente','En curso','Cumplido'].includes(status))return;API.mutate(data=>{if(id.startsWith('next:')){const p=data.projects.find(p=>p.id===id.slice(5));if(!p)return;if(status==='Cumplido'){data.milestones.push({id:uid(),projectId:p.id,title:p.nextAction,type:'Otro',status:'Cumplido',dueDate:p.targetDate||'',owner:p.owner||'',notes:'Próxima acción completada desde el tablero'});p.nextAction='';}else {meta(p.id).nextTaskStatus=status;activity('Estado de tarea actualizado',p.id,p.nextAction+' · '+status);}}else{const m=data.milestones.find(m=>m.id===id);if(m)m.status=status;}});toast('Tarea actualizada.');}
  function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>guard(render),80);}
  function render(){renderDashboard();renderPortfolio();renderWorkspace();renderActivity();renderMarketing();renderModule('calculator');renderModule('pressure');bind();if(API.view()==='equipment'){let el=$('equipmentCatalog');if(!el){el=document.createElement('section');el.id='equipmentCatalog';el.className='suite';$('view-equipment').append(el);$('view-equipment').querySelector('.tracker-panel').hidden=true;}el.innerHTML=equipmentList(tracker().equipment);bind();}if(API.view()==='balances'&&!$('compareAllCalculations')){const b=document.createElement('button');b.id='compareAllCalculations';b.textContent='Comparar cálculos';b.onclick=()=>compareCalculations();$('view-balances').querySelector('.heading').append(b);}status();}
  function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function snapshot(){return {format:'thermabot-suite',schema:1,exportedAt:new Date().toISOString(),tracker:tracker(),balances:balances(),library:library(),suite:JSON.parse(JSON.stringify(suite))};}
  function openBackupDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('thermabot-safe-copies',1);request.onupgradeneeded=()=>request.result.createObjectStore('snapshots',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  function scheduleBackup(){clearTimeout(backupTimer);backupTimer=setTimeout(()=>guard(makeBackup),1800);}
  async function makeBackup(){if(!db)return;const value=snapshot(),key=JSON.stringify({tracker:value.tracker,balances:value.balances,library:value.library,suite:value.suite});if(key===makeBackup.previous)return;await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readwrite'),store=tx.objectStore('snapshots');store.put({id:Date.now(),at:value.exportedAt,value});const all=store.getAllKeys();all.onsuccess=()=>all.result.slice(0,Math.max(0,all.result.length-30)).forEach(k=>store.delete(k));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});makeBackup.previous=key;localStorage.setItem('thermabot.suite.backupAt',value.exportedAt);status();}
  async function backupVersions(){if(!db)throw Error('El navegador no habilitó las copias internas. Descargá una copia completa.');const list=await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots'),r=tx.objectStore('snapshots').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});dialog('Copias automáticas de este navegador','<p class="subtle">Se conservan hasta 30 versiones. Estas copias están en este equipo; para conservarlas fuera del navegador, descargá una copia completa o usá Drive.</p><div class="suite-list">'+list.reverse().map(x=>'<article><div class="suite-row"><span>'+esc(new Date(x.at).toLocaleString('es-AR'))+'</span><button data-download-version="'+x.id+'">Descargar versión</button></div><p>'+x.value.tracker.projects.length+' proyectos · '+x.value.balances.length+' cálculos</p></article>').join('')+'</div>');document.querySelectorAll('[data-download-version]').forEach(b=>b.onclick=()=>download(list.find(x=>x.id===Number(b.dataset.downloadVersion)).value,'THERMABOT-copia-'+b.dataset.downloadVersion+'.json'));}
  async function restoreFile(file){
    if(file.size>20000000)throw Error('La copia supera 20 MB.');const value=JSON.parse(await file.text());
    if(value.format!=='thermabot-suite'||value.schema!==1||!value.tracker||!['projects','equipment','milestones','documents'].every(k=>Array.isArray(value.tracker[k]))||!Array.isArray(value.balances)||!value.suite?.projects||!Array.isArray(value.suite.activity)||!value.suite.preferences||!value.library?.links||!Array.isArray(value.library.audits))throw Error('No es una copia completa de THERMABOT.');
    value.balances.forEach(TBWorkspace.validateBalance);
    if(!confirm('¿Restaurar esta copia completa? Primero se descargará una copia de los datos actuales.'))return;
    download(snapshot(),'THERMABOT-antes-de-restaurar.json');
    const keys=['thermabot.tracker.v1',BAL,LIB,KEY];const values=[value.tracker,value.balances,value.library,value.suite];const old=keys.map(k=>localStorage.getItem(k));
    try{keys.forEach((key,i)=>{if(old[i])localStorage.setItem(key+'.before-restore',old[i]);localStorage.setItem(key,JSON.stringify(values[i]));});}catch(error){keys.forEach((key,i)=>{if(old[i]===null)localStorage.removeItem(key);else localStorage.setItem(key,old[i]);});throw error;}
    initState();previous=null;API.refresh();previous=tracker();activity('Copia completa restaurada','','Archivo '+file.name);scheduleRender();toast('Copia restaurada en este navegador. Revisá Drive antes de sincronizar.');
  }
  function renderSettings(){
    $('suiteSettings').innerHTML='<div class="suite-head"><div><h2>Configuración y guardado</h2><p>Un solo lugar para las conexiones y la recuperación.</p></div></div><div class="suite-two"><section class="card"><h3>Tu espacio de trabajo</h3><form id="preferencesForm"><label>Nombre del operador<input name="actor" value="'+esc(suite.preferences.actor||'')+'" required></label><label>Tema<select name="theme">'+opt(['Claro','Oscuro'],suite.preferences.theme==='dark'?'Oscuro':'Claro')+'</select></label><button class="primary" style="margin-top:14px">Guardar preferencias</button></form></section><section class="card"><h3>Copias de seguridad</h3><p class="subtle">Los cambios se guardan automáticamente en este navegador. También se conservan versiones internas cuando el navegador lo permite.</p><div class="actions"><button id="exportSuite">Descargar copia completa</button><button id="showBackups">Ver copias automáticas</button><label class="button">Restaurar copia completa<input id="restoreSuite" type="file" accept=".json" hidden></label></div><p id="backupInfo" class="subtle"></p></section></div><section class="card"><h3>Google Drive</h3><p class="subtle">El seguimiento usa su planilla y la conexión existente. Los cálculos conservan su respaldo separado. El estado de Drive confirma únicamente lo que se verificó en la nube.</p><div class="actions"><button id="openTrackerConnection">Conexión del seguimiento</button><button id="openCalculationConnection">Cálculos y versiones de Drive</button></div><p class="suite-notice">Finanzas y actividad se conservan en la copia completa de la aplicación. Todavía no se sincronizan con la planilla del seguimiento.</p></section>';
    $('preferencesForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));suite.preferences.actor=f.actor;suite.preferences.theme=f.theme==='Oscuro'?'dark':'light';saveSuite();applyTheme();toast('Preferencias guardadas.');};$('exportSuite').onclick=()=>download(snapshot(),'THERMABOT-copia-completa.json');$('showBackups').onclick=()=>guard(backupVersions);$('restoreSuite').onchange=e=>{const file=e.target.files[0];if(file)guard(()=>restoreFile(file));e.target.value='';};$('openTrackerConnection').onclick=()=>API.navigate('drive');$('openCalculationConnection').onclick=()=>API.navigate('backup');status();
  }
  function status(){let el=$('suiteSaveIndicator');if(!el){el=document.createElement('div');el.id='suiteSaveIndicator';el.className='status-indicator';$('trackerMeta').after(el);}const text=$('driveQuickBtn').textContent||'Copia local';el.innerHTML='<i></i><span>'+esc(text)+'</span>';el.classList.toggle('verified',/verificad|sincronizad/i.test(text)&&!/pendiente|error|desconectad/i.test(text));const at=localStorage.getItem('thermabot.suite.backupAt');if($('backupInfo'))$('backupInfo').textContent=at?'Última copia interna: '+new Date(at).toLocaleString('es-AR'):'La copia interna se crea después del próximo cambio.';}
  function applyTheme(){document.body.dataset.theme=suite.preferences.theme||'light';document.querySelectorAll('.module-frame').forEach(f=>f.contentWindow?.postMessage({type:'thermabot:theme',theme:suite.preferences.theme},location.origin));}
  function palette(){let d=$('suitePalette');if(!d){d=document.createElement('dialog');d.id='suitePalette';d.className='suite-dialog palette suite';document.body.append(d);}d.innerHTML='<div class="dialog-head"><span class="suite-label">IR A CUALQUIER PARTE</span><button id="closePalette" aria-label="Cerrar buscador">×</button></div><input id="paletteQuery" aria-label="Buscar proyectos, equipos, documentos y cálculos" placeholder="Buscar proyecto, cálculo, plano, equipo…"><div id="paletteResults" class="palette-results"></div><p class="subtle">↑ ↓ para elegir · Enter para abrir · Esc para cerrar</p>';$('closePalette').onclick=()=>d.close();d.showModal();$('paletteQuery').focus();const render=()=>{paletteRows=C.search(tracker(),balances(),$('paletteQuery').value);paletteIndex=0;showPaletteResults();};$('paletteQuery').oninput=render;d.onkeydown=e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();paletteIndex=Math.max(0,Math.min(paletteRows.length-1,paletteIndex+(e.key==='ArrowDown'?1:-1)));showPaletteResults();}if(e.key==='Enter'){e.preventDefault();choosePalette(paletteRows[paletteIndex]);}};render();}
  function showPaletteResults(){$('paletteResults').innerHTML=paletteRows.map((r,i)=>'<button data-palette-result="'+i+'" class="'+(i===paletteIndex?'primary':'')+'">'+tag(r.kind,'neutral')+'<span><strong>'+esc(r.title)+'</strong><small>'+esc(r.detail)+'</small></span></button>').join('')||(empty('No se encontraron resultados.'));document.querySelectorAll('[data-palette-result]').forEach(b=>b.onclick=()=>choosePalette(paletteRows[Number(b.dataset.paletteResult)]));}
  function choosePalette(row){if(!row)return;$('suitePalette').close();if(row.kind==='Cálculo'){setModule('calculator',row.id,library().links[row.id]);return;}if(row.projectId){openProject(row.projectId,({Equipo:'Equipos',Documento:'Documentos',Hito:'Hitos'})[row.kind]||'Resumen');if(row.kind==='Documento')previewDocument(row.id);}else if(row.kind==='Equipo'){API.navigate('equipment');API.editEquipment(row.id);}else if(row.kind==='Documento')previewDocument(row.id);else API.editMilestone(row.id);}
  function init(){
    guard(()=>{initState();previous=tracker();applyTheme();
      if(document.body.dataset.projectTab)projectTab=document.body.dataset.projectTab;
      window.addEventListener('thermabot:projecttab',e=>{projectTab=e.detail;});
      document.body.classList.toggle('collapsed',!!suite.preferences.collapsed);
      document.querySelectorAll('.rail [data-view]').forEach(b=>b.setAttribute('aria-label',b.getAttribute('title')||b.textContent.trim()));
      const collapseLabel=()=>{$('collapseRail').setAttribute('aria-expanded',String(!suite.preferences.collapsed));$('collapseRail').setAttribute('aria-label',suite.preferences.collapsed?'Expandir menú':'Contraer menú');};collapseLabel();
      $('collapseRail').onclick=()=>{suite.preferences.collapsed=!suite.preferences.collapsed;document.body.classList.toggle('collapsed',suite.preferences.collapsed);collapseLabel();saveSuite();};
      $('themeBtn').onclick=()=>{suite.preferences.theme=suite.preferences.theme==='dark'?'light':'dark';saveSuite();applyTheme();};$('globalSearchBtn').onclick=palette;
      document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('suitePalette')?.open)palette();}});
      window.addEventListener('thermabot:data',()=>guard(captureChanges));window.addEventListener('thermabot:render',scheduleRender);window.addEventListener('thermabot:portfolio',scheduleRender);window.addEventListener('thermabot:navigate',()=>{if(API.view()==='settings')renderSettings();if(['calculator','pressure'].includes(API.view())){moduleProject=API.selectedId()||moduleProject;renderModule(API.view());}scheduleRender();});
      window.addEventListener('storage',e=>guard(()=>{if(e.key==='thermabot.tracker.v1')API.refresh();if(e.key===KEY)initState();scheduleBackup();scheduleRender();}));
      window.addEventListener('message',e=>guard(()=>{if(e.origin!==location.origin||!['calculator','pressure'].some(v=>document.querySelector('#view-'+v+' iframe')?.contentWindow===e.source))return;const msg=e.data;if(msg?.type==='thermabot:saved'&&typeof msg.balanceId==='string'){const sourceModule=['calculator','pressure'].find(v=>document.querySelector('#view-'+v+' iframe')?.contentWindow===e.source);activeBalances[sourceModule]=msg.balanceId;
        const projectId=API.view()===sourceModule?moduleProject:library().links[msg.balanceId]||'';
        if(projectId&&library().links[msg.balanceId]!==projectId)link(msg.balanceId,projectId);
        if(msg.explicit||Date.now()-(calculationActivityAt[msg.balanceId]||0)>30000){activity(msg.explicit?'Cálculo guardado':'Cálculo actualizado',projectId,balances().find(b=>b.id===msg.balanceId)?.nombre||'');calculationActivityAt[msg.balanceId]=Date.now();}scheduleBackup();scheduleRender();if(msg.explicit)toast(moduleProject?'Cálculo guardado y vinculado al proyecto.':'Cálculo guardado. Seleccioná un proyecto para vincularlo.');}if(msg?.type==='thermabot:ready'){e.source.postMessage({type:'thermabot:theme',theme:suite.preferences.theme},location.origin);const sourceModule=['calculator','pressure'].find(v=>document.querySelector('#view-'+v+' iframe')?.contentWindow===e.source);activeBalances[sourceModule]=msg.balanceId;}}));
      const observer=new MutationObserver(status);observer.observe($('driveQuickBtn'),{childList:true,characterData:true,subtree:true});
      openBackupDB().then(value=>{db=value;scheduleBackup();}).catch(()=>toast('Este navegador no habilitó las copias internas. Podés descargar una copia completa.'));
      document.querySelectorAll('.module-frame').forEach(f=>f.addEventListener('load',applyTheme));render();renderSettings();
    });
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
