import type {InternalLoads,FactorInput,Trace,Warning,Datum,Result} from './types.ts';
import {numberOf,nonnegative,fraction,hourly,trace,variable,calculated,EngineeringError,positive} from './core.ts';
import {coolingLoad} from './rts.ts';
export function internalLoads(i:InternalLoads,factors:FactorInput,mode:'RTS'|'instantaneo',fallback:'instantaneo'|'error'):{components:Record<string,{sensible:number[];latent:number[]}>;returnHeat:number[];mode:('RTS'|'instantaneo')[];trace:Trace[];warnings:Warning[]} {
 const profiles=[['people',i.people.schedule],['lights',i.lights.schedule],['equipment',i.equipment.schedule]].map(([key,d])=>{const p=hourly(d as Datum[],'1',key as string);p.forEach(v=>{if(v<0||v>1)throw new EngineeringError('Horario fuera de 0…1',key as string);});return p;});
 const N=nonnegative(numberOf(i.people.count,'1')),qs=nonnegative(numberOf(i.people.sensible,'W')),ql=nonnegative(numberOf(i.people.latent,'W')),pg=profiles[0].map(f=>N*qs*f),pl=profiles[0].map(f=>N*ql*f);
 const p=coolingLoad(pg,fraction(i.people.radiantFraction),factors.rts,mode,fallback,'people');
 const watts=nonnegative(numberOf(i.lights.installedPower,'W')),ul=fraction(i.lights.utilization),sa=positive(numberOf(i.lights.allowance,'1'),'Fsa'),space=fraction(i.lights.spaceFraction),el=profiles[1].map(f=>watts*ul*sa*f),lg=el.map(q=>q*space),ret=el.map(q=>q*(1-space)),l=coolingLoad(lg,fraction(i.lights.radiantFraction),factors.rts,mode,fallback,'lights');
 const power=nonnegative(numberOf(i.equipment.inputPower,'W')),use=fraction(i.equipment.use),load=fraction(i.equipment.load),sp=fraction(i.equipment.spaceFraction),ss=fraction(i.equipment.sensibleFraction),ll=fraction(i.equipment.latentFraction);if(ss+ll>1+1e-10)throw new EngineeringError('fsensible + flatente > 1','equipment');const eg=profiles[2].map(f=>power*use*load*sp*f*ss),latent=profiles[2].map(f=>power*use*load*sp*f*ll),e=coolingLoad(eg,fraction(i.equipment.radiantFraction),factors.rts,mode,fallback,'equipment');
 return {components:{personas:{sensible:p.value.load,latent:pl},iluminacion:{sensible:l.value.load,latent:Array(24).fill(0)},equipos:{sensible:e.value.load,latent}},returnHeat:ret,mode:[p.value.mode,l.value.mode,e.value.mode],warnings:[...p.warnings,...l.warnings,...e.warnings],trace:[trace('people-gain','Personas · ganancias sensible y latente','Qs=N qs fhorario; Ql=N ql fhorario',{N:variable(i.people.count),qs:variable(i.people.sensible),ql:variable(i.people.latent),horario:calculated(profiles[0],'1','Horario de ocupación ingresado')},pg,'W','9'),trace('people-latent','Personas · latente instantánea','Ql=N ql fhorario',{N:variable(i.people.count),ql:variable(i.people.latent),horario:calculated(profiles[0],'1','Horario de ocupación ingresado')},pl,'W','9'),...p.trace,
 trace('lights-gain','Iluminación · ganancias al ambiente','qspace=Winst Ful Fsa fhorario fspace',{Winst:variable(i.lights.installedPower),Ful:variable(i.lights.utilization),Fsa:variable(i.lights.allowance),fspace:variable(i.lights.spaceFraction),horario:calculated(profiles[1],'1','Horario de luces ingresado')},lg,'W','10'),trace('lights-return','Iluminación · calor al retorno','qreturn=Winst Ful Fsa fhorario (1−fspace)',{Winst:variable(i.lights.installedPower),Ful:variable(i.lights.utilization),Fsa:variable(i.lights.allowance),fspace:variable(i.lights.spaceFraction),horario:calculated(profiles[1],'1','Horario de luces ingresado')},ret,'W','10'),...l.trace,
 trace('equipment-gain','Equipos · ganancia sensible','qs=Pinput Fuse Fload Fspace fhorario fsensible',{Pinput:variable(i.equipment.inputPower),Fuse:variable(i.equipment.use),Fload:variable(i.equipment.load),Fspace:variable(i.equipment.spaceFraction),fsensible:variable(i.equipment.sensibleFraction),horario:calculated(profiles[2],'1','Horario de equipos ingresado')},eg,'W','11'),trace('equipment-latent','Equipos · ganancia latente','ql=Pinput Fuse Fload Fspace fhorario flatente',{Pinput:variable(i.equipment.inputPower),Fuse:variable(i.equipment.use),Fload:variable(i.equipment.load),Fspace:variable(i.equipment.spaceFraction),flatente:variable(i.equipment.latentFraction),horario:calculated(profiles[2],'1','Horario de equipos ingresado')},latent,'W','11'),...e.trace]};
}
export function motorHeat(power:Datum,efficiency:Datum,use:Datum,load:Datum,location:'ambos-dentro'|'motor-fuera'|'maquina-fuera'|'ambos-fuera'):Result<number> {const P=nonnegative(numberOf(power,'W')),eta=positive(fraction(efficiency),'η'),fu=fraction(use),fl=fraction(load),q=location==='ambos-dentro'?P/eta*fu*fl:location==='motor-fuera'?P*fu*fl:location==='maquina-fuera'?P*(1-eta)/eta*fu*fl:0;return {value:q,warnings:[],trace:[trace('motor','Calor de motor y máquina',location==='ambos-dentro'?'q=(P/η)Fuse Fload':location==='motor-fuera'?'q=P Fuse Fload':location==='maquina-fuera'?'q=P(1−η)/η Fuse Fload':'q=0',{P:variable(power),eta:variable(efficiency),Fuse:variable(use),Fload:variable(load)},q,'W','11.1')]};}
