import {demoInput} from './demo.ts';
import {datum} from './core.ts';
import {enableQuadri} from './quadri.ts';
export function quadriReference(season:'verano'|'invierno'='verano') {
 const i=enableQuadri(demoInput('quadri-referencia'));i.id='oficina-quadri';i.room='Oficina · ejemplo resuelto del libro';i.name='Caso de verificación · Quadri';const q=i.quadri!;q.season=season;q.city='buenos-aires';q.solarBasis='35';q.outdoorSummer=datum(35,'°C','biblioteca','Quadri p.116');q.rhSummer=datum(40,'%','biblioteca','Quadri p.116');q.outdoorWinter=datum(0,'°C','biblioteca','Quadri p.130');q.indoorWinter=datum(22,'°C','biblioteca','Quadri p.130');q.dailyRange='11';q.ductSummer=datum(10,'%','biblioteca','Quadri p.117');q.zd=datum(15,'%','biblioteca','Quadri p.130');q.zc=datum(10,'%','biblioteca','Quadri p.130');q.floorMode='terreno';q.activity='sentado';q.ventMode='porcentaje';q.flowMode='adoptado';q.adoptedFlow=datum(60,'m³/min','biblioteca','Quadri pp.118/131 · caudal adoptado');q.humidityMode='abaco';q.lighting='medida';
 i.geometry={length:datum(12,'m','biblioteca','Quadri p.116'),width:datum(4.5,'m','biblioteca','Quadri p.116'),height:datum(3,'m','biblioteca','Quadri p.116')};
 i.climate.indoorTemperature=datum(25,'°C','biblioteca','Quadri p.116');i.climate.indoorRH=datum(50,'%','biblioteca','Quadri p.116');i.climate.supplyTemperature=datum(15,'°C','biblioteca','Quadri p.118');i.climate.pressure=datum(101325,'Pa','supuesto','Ábaco a nivel del mar');
 const base=i.surfaces[0];i.surfaces=[['ne','Muro NE',36,1.62,-135,'exterior'],['se','Muro SE',13.5,1.62,-45,'exterior'],['interior','Tabiques sin climatizar',42,2.3,0,'no-climatizado'],['techo','Cubierta',54,1.5,0,'exterior']].map(([id,name,A,K,az,b])=>({...structuredClone(base),id:id as string,name:name as string,kind:id==='techo'?'roof' as const:'wall' as const,areaMode:'manual' as const,grossArea:datum(A as number,'m²','biblioteca','Quadri pp.116/130'),area:datum(A as number,'m²','biblioteca','Área bruta'),u:datum(K as number,'kcal/(h·m²·°C)','biblioteca','Quadri pp.116/130'),azimuth:datum(az as number,'°'),tilt:datum(id==='techo'?0:90,'°'),quadriBoundary:b as any}));
 const w=i.windows[0];i.windows=[{...w,id:'vidrio-ne',name:'Ventana NE · cortina exterior clara',parentId:'ne',area:datum(17.6,'m²','biblioteca','Quadri p.116'),u:datum(5,'kcal/(h·m²·°C)','biblioteca','Quadri p.116'),quadriC:datum(.3,'1','biblioteca','Cuadro 5-III, p.108'),quadriShading:'cortina-exterior',sunlitFraction:Array.from({length:24},()=>datum(1,'1','biblioteca','Área soleada del ejemplo'))}];
 const all=()=>Array.from({length:24},()=>datum(1,'1','biblioteca','Ocupación / uso del ejemplo'));
 Object.assign(i.internals.people,{count:datum(10,'1','biblioteca','Quadri p.117'),sensible:datum(55/.86,'W','biblioteca','Quadri p.117 · 55 kcal/h persona'),latent:datum(45/.86,'W','biblioteca','Quadri p.117 · 45 kcal/h persona'),schedule:all()});Object.assign(i.internals.lights,{installedPower:datum(1080,'W','biblioteca','54 m² × 20 W/m² · Quadri p.117'),utilization:datum(1,'1'),allowance:datum(1,'1'),spaceFraction:datum(1,'1'),schedule:all()});Object.assign(i.internals.equipment,{inputPower:datum(4000/.86,'W','biblioteca','4000 kcal/h · Quadri p.117'),use:datum(1,'1'),load:datum(1,'1'),spaceFraction:datum(1,'1'),sensibleFraction:datum(1,'1'),latentFraction:datum(0,'1'),schedule:all()});i.infiltrationACH=datum(0,'ACH','biblioteca','Ejemplo sin infiltración adicional');i.outdoorFlow=datum(720,'m³/h','biblioteca','12 m³/min · Quadri p.118');i.systemSensible=datum(0,'W');i.systemLatent=datum(0,'W');return i;
}
