import type {ProjectInput,Calculation,Datum,Trace,Warning,HourResult,RoomPartition,AirState} from './types.ts';
import {datum,numberOf,range,positive,nonnegative,validateTree,EngineeringError,calculated,variable,uniqueWarnings} from './core.ts';
import {prepareEnvelope} from './geometria_edificio.ts';
import {partitionExterior} from './particiones.ts';
import {airState,humidityRatio,rhFromHumidity,atmosphericPressure} from './psicrometria.ts';
import {QUADRI_SOURCE,QUADRI_CITIES,QUADRI_MATERIALS,QUADRI_EQ,QUADRI_SOLAR,SOLAR_ORIENTATIONS,QUADRI_CORRECTIONS,CORRECTION_HOURS} from './catalogo_quadri.ts';
export const QUADRI_VERSION='3.0.0-quadri-preview.1';
export interface QuadriSettings {
 season:'verano'|'invierno';city:string;solarBasis:string;dailyRange:string;rounding:'planilla'|'precision';
 outdoorSummer:Datum;rhSummer:Datum;outdoorWinter:Datum;rhWinter:Datum;indoorWinter:Datum;
 ductSummer:Datum;zd:Datum;zhMode:'auto'|'manual';zh:Datum;zc:Datum;
 floorMode:'ninguno'|'terreno';floorK:Datum;groundT:Datum;
 activity:string;lighting:string;ventMode:'porcentaje'|'manual';outsidePct:Datum;minPerPerson:Datum;
 flowMode:'calculado'|'adoptado';adoptedFlow:Datum;winterSupply:Datum;
 humidityMode:'calculada'|'abaco';he:Datum;hi:Datum;
 equipmentTotal:Datum;equipmentSensible:Datum;equipmentFlow:Datum;equipmentName:string;equipmentSource:string;
}
export interface QuadriHour {hour:number;QSi:number;QLi:number;QTi:number;Qse:number;Qle:number;QTe:number;QT:number;QST:number;Qo:number;Qt:number;FCS:number|null;C:number|null;Ca:number;PRA:number|null;PRS:number|null;supplyT:number|null;supplyW:number|null;mix:AirState|null;supply:AirState|null;condensate:number|null;psychValid:boolean;zh:number;selection:{checked:boolean;total:boolean;sensible:boolean;flow:boolean}|null;}
const source=(page:string)=>QUADRI_SOURCE+' · '+page;
const d=(value:number,unit:any,label:string,p='supuesto')=>datum(value,unit,p as any,label);
export function quadriDefaults():QuadriSettings {return {
 season:'verano',city:'rosario',solarBasis:'interpolar',dailyRange:'11',rounding:'planilla',
 outdoorSummer:d(36,'°C',source('Cuadro 1-III, p.96'),'biblioteca'),rhSummer:d(40,'%',source('Cuadro 1-III, p.96'),'biblioteca'),outdoorWinter:d(.4,'°C',source('Cuadro 1-III, p.96'),'biblioteca'),rhWinter:d(80,'%',source('Cuadro 1-III, p.96'),'biblioteca'),indoorWinter:d(21.5,'°C',source('p.97 · confort recomendado'),'biblioteca'),
 ductSummer:d(0,'%', 'Sin conductos declarados · revisar'),zd:d(7,'%',source('Cuadro 10-III, p.126 · continuo'),'biblioteca'),zhMode:'auto',zh:d(0,'%', 'Orientación automática'),zc:d(0,'%', 'Sin pérdidas de conductos declaradas · revisar'),floorMode:'ninguno',floorK:d(1,'kcal/(h·m²·°C)',source('p.125 · piso sobre terreno'),'biblioteca'),groundT:d(10,'°C',source('p.125 · aproximación práctica'),'biblioteca'),
 activity:'manual',lighting:'medida',ventMode:'manual',outsidePct:d(20,'%', 'Propuesta editable · Cuadro 8-III, p.111'),minPerPerson:d(.5,'m³/min',source('Cuadro 9-III, p.112 · oficina general por persona'),'biblioteca'),flowMode:'calculado',adoptedFlow:d(60,'m³/min', 'Caudal adoptado pendiente de verificar'),winterSupply:d(40,'°C','Impulsión de invierno propuesta editable'),humidityMode:'calculada',he:d(14,'g/kg','Lectura manual del ábaco · ejemplo p.118'),hi:d(10,'g/kg','Lectura manual del ábaco · ejemplo p.118'),equipmentTotal:d(0,'kcal/h','Pendiente ficha fabricante'),equipmentSensible:d(0,'kcal/h','Pendiente ficha fabricante'),equipmentFlow:d(0,'m³/h','Pendiente ficha fabricante'),equipmentName:'',equipmentSource:''
};}
// Old inputs are preserved; method-dependent choices remain explicitly pending.
export function enableQuadri(original:ProjectInput):ProjectInput {const i=structuredClone(original);if(!i.quadri)i.quadri=quadriDefaults();if(!i.quadri.solarBasis)i.quadri.solarBasis='35';i.requestedMode='instantaneo';return i;}
export function quadriTrace(id:string,label:string,equation:string,variables:Record<string,any>,result:number|number[]|null,unit:string,page:string,warnings:string[]=[]):Trace {
 if(result!==null)(Array.isArray(result)?result:[result]).forEach(v=>{if(!Number.isFinite(v))throw new EngineeringError('Resultado no finito',id);});
 return {id,label,equation,variables,result,unit,source:source(page),engineVersion:QUADRI_VERSION,warnings};
}
export function quadriOrientation(az:number):string {const normalized=((az+180)%360+360)%360;return ['N','NE','E','SE','S','SO','O','NO'][Math.round(normalized/45)%8];}
function interp(hour:number,values:number[]):number {const n=CORRECTION_HOURS.findIndex(h=>h>=hour);if(n<0||hour<6)throw new EngineeringError('Hora sin corrección tabulada');if(CORRECTION_HOURS[n]===hour)return values[n];const a=n-1,f=(hour-CORRECTION_HOURS[a])/(CORRECTION_HOURS[n]-CORRECTION_HOURS[a]);return values[a]+f*(values[n]-values[a]);}
export function quadriEquivalent(orientation:string,k:number,hour:number,dt:number):{value:number;row:number;base:number} {
 const rows=QUADRI_EQ[orientation],ks=orientation==='H'?[4,3,2.3,1.6,.8]:[3,2.3,1.6,.8];if(!rows||hour<6||hour>23||!Number.isInteger(hour))throw new EngineeringError('Orientación/hora sin tabla Quadri');positive(k,'K');
 const row=ks.reduce((a,b)=>Math.abs(b-k)<Math.abs(a-k)?b:a),base=rows[ks.indexOf(row)][hour-6];return {value:base+dt-10,row,base};
}
export function quadriSolar(orientation:string,hour:number,latitude:number,basis:string):{value:number;source:string} {
 const col=SOLAR_ORIENTATIONS.indexOf(orientation);if(col<0||!Number.isInteger(hour)||hour<6||hour>18)throw new EngineeringError('Hora/orientación fuera de tabla solar');
 if(basis!=='interpolar'){if(!QUADRI_SOLAR[basis])throw new EngineeringError('Latitud tabulada inválida');return {value:QUADRI_SOLAR[basis][hour-6][col],source:'Cuadro 4-III, pp.106–107 · '+basis+'° S · '+orientation+' · '+hour+' h'};}
 range(latitude,-40,-25,'Latitud solar · tablas sólo 25–40° S');const abs=-latitude,lo=Math.min(35,Math.floor((abs-25)/5)*5+25),hi=lo+5,f=(abs-lo)/5,a=QUADRI_SOLAR[String(lo)][hour-6][col],b=QUADRI_SOLAR[String(hi)][hour-6][col];return {value:a+(b-a)*f,source:'Cuadro 4-III · interpolación lineal explícita '+lo+'–'+hi+'° S; I='+a+'+('+b+'−'+a+')·'+f+'; '+orientation+' · '+hour+' h'};
}
function saturatedRoot(line:(t:number)=>number,hi:number,p:number):number|null {
 const f=(t:number)=>humidityRatio(t,1,p)*1000-line(t);let upper=hi,last=f(upper);
 // Select the nearest physical intersection below the process starting point.
 for(let lower=hi-.25;lower>=-60;lower-=.25){const next=f(lower);if(next*last<=0){let a=lower,b=upper;for(let j=0;j<70;j++){const m=(a+b)/2;if(f(m)*f(a)<=0)b=m;else a=m;}const t=(a+b)/2;return line(t)>=0?t:null;}upper=lower;last=next;}return null;
}
export function quadriPsych(tRoom:number,wRoom:number,tOut:number,wOut:number,tSupply:number,C:number,Ca:number,QLi:number,p:number):{PRA:number|null;PRS:number|null;mix:AirState|null;supply:AirState|null;condensate:number|null;supplyW:number|null} {
 if(C<=0||Ca>C||tSupply>=tRoom)return {PRA:null,PRS:null,mix:null,supply:null,condensate:null,supplyW:null};
 const a=Ca/C,tm=(1-a)*tRoom+a*tOut,wm=(1-a)*wRoom+a*wOut,wi=wRoom-QLi/(42*C),slope=(wRoom-wi)/(tRoom-tSupply);
 const PRA=saturatedRoot(t=>wRoom-slope*(tRoom-t),tRoom,p);
 let mix:AirState|null=null,supply:AirState|null=null;
 const state=(t:number,w:number,id:string)=>airState(datum(t,'°C','calculado','Balance Quadri'),datum(rhFromHumidity(t,w/1000,p)*100,'%','calculado','Humedad específica → HR'),datum(p,'Pa','ingresado','Presión de proyecto'),id);
 try{mix=state(tm,wm,'mix');if(wi>=0)supply=state(tSupply,wi,'supply');}catch{ /* Infeasible states are visible, never silently clamped. */ }
 const PRS=tm>tSupply&&mix&&supply?saturatedRoot(t=>wm-(wm-wi)/(tm-tSupply)*(tm-t),tSupply,p):null;
 const condensate=mix&&supply?Math.max(0,C*60/mix.v*(wm-wi)/1000):null;
 return {PRA,PRS,mix,supply,condensate,supplyW:wi};
}
export function calculateQuadri(original:ProjectInput,links:RoomPartition[]=[]):Calculation {
 const prepared=prepareEnvelope(enableQuadri(original)),input=prepared.input,q=input.quadri!,exterior=partitionExterior(input,links),warnings:Warning[]=[],td:Trace[]=prepared.trace.concat(exterior.trace);
 validateTree(input);if(!['verano','invierno'].includes(q.season)||!QUADRI_CORRECTIONS[q.dailyRange]||!['planilla','precision'].includes(q.rounding)||!['calculado','adoptado'].includes(q.flowMode)||!['porcentaje','manual'].includes(q.ventMode)||!['calculada','abaco'].includes(q.humidityMode)||!['auto','manual'].includes(q.zhMode)||!['ninguno','terreno'].includes(q.floorMode))throw new EngineeringError('Configuración Quadri inválida');
 const warn=(code:string,message:string,path='quadri')=>warnings.push({code,message,path});
 const add=(id:string,label:string,formula:string,vars:Record<string,any>,value:number|null,unit:string,page:string)=>{td.push(quadriTrace(id,label,formula,vars,value,unit,page));return value;};
 const round=(x:number)=>q.rounding==='planilla'?Math.round(x):x;
 const summer=q.season==='verano',te=numberOf(summer?q.outdoorSummer:q.outdoorWinter,'°C'),ti=numberOf(summer?input.climate.indoorTemperature:q.indoorWinter,'°C'),rhbase=range(numberOf(summer?q.rhSummer:q.rhWinter,'%'),0,100,'HR exterior'),rhRoom=range(numberOf(input.climate.indoorRH,'%'),0,100,'HR interior'),p=input.climate.pressure||atmosphericPressure(input.climate.location.altitude).value;
 range(te,-60,60,'Exterior');range(ti,-20,50,'Interior');const pressure=numberOf(p,'Pa');
 const room=airState(datum(ti,'°C','calculado',summer?input.climate.indoorTemperature.source:q.indoorWinter.source),datum(rhRoom,'%','ingresado',input.climate.indoorRH.source),p,'room');td.push(...room.trace);
 const dsummer=range(numberOf(q.ductSummer,'1'),0,1,'Conductos verano'),zd=range(numberOf(q.zd,'1'),0,1,'Zd'),zc=range(numberOf(q.zc,'1'),0,1,'Zc');
 let orientations=[...new Set(exterior.surfaces.filter(s=>s.kind!=='roof'&&s.area.value>0&&(!s.quadriBoundary||s.quadriBoundary==='exterior')).map(s=>quadriOrientation(s.azimuth.value)))];
 let zh=0;if(q.zhMode==='manual')zh=range(numberOf(q.zh,'1'),-.05,.05,'Zh');else if(orientations.length===1)zh=['N','NE','NO'].includes(orientations[0])?-.05:['S','SE','SO'].includes(orientations[0])?.05:0;else if(orientations.length===2){const angles=orientations.map(o=>['N','NE','E','SE','S','SO','O','NO'].indexOf(o)*Math.PI/4),x=angles.reduce((a,b)=>a+Math.sin(b),0),y=angles.reduce((a,b)=>a+Math.cos(b),0);if(Math.hypot(x,y)<1e-8){warn('WINTER_OPPOSITE_WALLS','Dos fachadas opuestas: indicá Zh manual; la regla de esquina no aplica.');zh=0;}else{const corner=quadriOrientation(Math.atan2(x,y)*180/Math.PI-180),supp=(o:string)=>['N','NE','NO'].includes(o)?-.05:['S','SE','SO'].includes(o)?.05:0;zh=supp(corner);}}else if(orientations.length>=3)zh=Math.max(...orientations.map(o=>['S','SE','SO'].includes(o)?.05:['N','NE','NO'].includes(o)?-.05:0));
 add('winter-zh','Suplemento por orientación','Una fachada: orientación; dos: bisectriz de esquina; tres/cuatro: mayor suplemento',{fachadas:calculated(orientations.join(', '),'orientación','Áreas exteriores positivas'),modo:calculated(q.zhMode,'1','Configuración')},zh*100,'%','p.127 · hemisferio sur');
 if(!summer&&q.zhMode==='auto'&&warnings.some(w=>w.code==='WINTER_OPPOSITE_WALLS'))throw new EngineeringError('Elegí Zh manual para fachadas opuestas');
 const kOf=(s:any)=>{const mat=QUADRI_MATERIALS.find(m=>m.id===s.quadriMaterial);if(s.quadriMaterial&&!mat)throw new EngineeringError('Material Quadri inexistente',s.name);if(mat&&mat.kind!==(input.windows.some(w=>w.id===s.id)?'window':s.kind||'wall'))throw new EngineeringError('Material de otro tipo de cerramiento',s.name);return positive(mat?(summer?mat.summer:mat.winter):numberOf(s.u,'kcal/(h·m²·°C)'),s.name+'.K');};
 if(summer)warn('MANUAL_TABLE_BASIS','Δt equivalente: tabla a 35° S, variación 11°C, fila K más próxima. Solar: '+(q.solarBasis==='interpolar'?'interpolación entre latitudes tabuladas para la latitud ingresada':q.solarBasis+'° S tabulados')+'. Revisá las hipótesis de construcción y variación diaria.');
 if(summer)warn('TABLE_HOURS','Perfil de verano: horas solares 06–18. No se extrapolan cargas nocturnas ni se declara un pico de 24 horas. Correcciones entre horas de Cuadro 2-III: interpolación lineal.');
 if(!summer)warn('WINTER_METHOD','Invierno: cálculo estacionario; no se descuentan ganancias de personas, luces ni equipos. No incluye humidificación.');
 if(q.flowMode==='adoptado')warn('ADOPTED_FLOW','Con C adoptado, la impulsión efectiva se deriva de QSi/17C; la temperatura ingresada sólo verifica el caudal requerido.');
 if(input.systemSensible.value!==0||input.systemLatent.value!==0)throw new EngineeringError('Adicionales heredados del sistema: incorporalos explícitamente al equipo/ductos antes de usar Quadri.');
 if(q.humidityMode==='abaco'&&summer)warn('MANUAL_HUMIDITY','he/hi son lecturas manuales del ábaco. Los estados dibujados derivan de temperatura y HR; ambas lecturas pueden diferir por redondeo.');
 if(q.activity==='manual')warn('PEOPLE_MANUAL','Calor por persona heredado o manual: elegí una actividad del Cuadro 6-III o verificá los valores.');
 if(summer&&Math.abs(ti-25)>.01&&q.activity!=='manual')warn('PEOPLE_TEMPERATURE','Cuadro 6-III corresponde a 25 °C. No se inventa una corrección para otra temperatura.');
 const pending=[input.internals.people.count,input.internals.lights.installedPower,input.internals.equipment.inputPower,input.outdoorFlow].filter(d=>d.source.startsWith('Pendiente'));
 if(pending.length)warn('PENDING_ROOM_DATA','Hay cargas o ventilación pendientes de completar. Los ceros iniciales no equivalen a datos verificados.');
 const domain=summer?Array.from({length:13},(_,i)=>i+6):[15],outdoor:AirState[]=[],details:QuadriHour[]=[],hours:HourResult[]=[];let peakSupply=room;
 for(const hour of domain){
  const corr=QUADRI_CORRECTIONS[q.dailyRange],t=summer?te+interp(hour,corr.t):te,hr=summer?rhbase+interp(hour,corr.rh):rhbase;
  range(hr,0,100,'HR exterior · '+hour+'h');const out=airState(datum(t,'°C','calculado',source('Cuadros 1/2-III, pp.96/100')),datum(hr,'%','calculado',source('Cuadros 1/2-III, pp.96/100')),p,'out-'+hour);outdoor.push(out);td.push(...out.trace);
  add('climate-'+hour,'Clima de cálculo · '+hour+' h','Te(h)=Te15+corrección; HR(h)=HR15+corrección',{Te15:variable(summer?q.outdoorSummer:q.outdoorWinter),HR15:variable(summer?q.rhSummer:q.rhWinter),variacion:calculated(q.dailyRange,'°C','Adoptada por usuario, no clima Rosario verificado')},t,'°C','Cuadros 1/2-III, pp.96/100');
  const components:Record<string,{sensible:number;latent:number}>={},partValue:number[]=[];
  const comp=(key:string,s:number,l=0)=>{components[key]??={sensible:0,latent:0};components[key].sensible+=s/.86;components[key].latent+=l/.86;};
  let opaque=0,glass=0,solar=0,partitions=0,soilLoss=0;
  for(const sf of exterior.surfaces){if(sf.area.value===0)continue;const k=kOf(sf),boundary=sf.quadriBoundary||'exterior';if(!['exterior','no-climatizado','climatizado'].includes(boundary))throw new EngineeringError('Exposición inválida',sf.name);let dt=0;const vars:any={K:calculated(k,'kcal/(h·m²·°C)',sf.quadriMaterial?QUADRI_MATERIALS.find(m=>m.id===sf.quadriMaterial)!.name+' · Cuadro 3-I, pp.44–45':sf.u.source),A:variable(sf.area)};
   if(boundary==='climatizado')dt=0;else if(boundary==='no-climatizado')dt=summer?t-3-ti:ti-(ti+te)/2;
   else if(!summer)dt=ti-te;else if(sf.quadriDelta){dt=numberOf(sf.quadriDelta,'°C');vars.deltaManual=variable(sf.quadriDelta);}else {
    if(sf.kind==='roof'&&sf.tilt.value!==0||sf.kind!=='roof'&&sf.tilt.value!==90)throw new EngineeringError('Tabla Δt equivalente: sólo muro vertical/cubierta horizontal. Ingresá Δt manual para otra inclinación.',sf.name);
    const orient=sf.kind==='roof'?'H':quadriOrientation(sf.azimuth.value),eq=quadriEquivalent(orient,k,hour,te-ti);dt=eq.value;vars.orientacion=calculated(orient,'1','Orientación más próxima a 45°');vars.Kfila=calculated(eq.row,'kcal/(h·m²·°C)','Fila tabulada más próxima · Cuadro 3-III');vars.deltaTabla=calculated(eq.base,'°C','Cuadro 3-III · 35°S / variación 11°C / Δt15=10°C');vars.deltaDiseno=calculated(te-ti,'°C','Te15−Ti');
    if(k<(sf.kind==='roof'?.8:.8)||k>(sf.kind==='roof'?4:3))warn('K_OUTSIDE_TABLE','K='+k+' fuera del intervalo de Cuadro 3-III; se adoptó fila K='+eq.row+'. Podés ingresar Δt manual verificado.',sf.name);
    if(q.dailyRange!=='11')warn('EQUIVALENT_DAILY_RANGE','Δt equivalente tabulado para variación 11 °C; no se corrige automáticamente por otra variación diaria.',sf.name);
   }
   vars.delta=calculated(dt,'°C',boundary==='exterior'?(summer?'Δt tabla +(Te15−Ti)−10':'Ti−Te'):boundary==='no-climatizado'?(summer?'Tadyacente=Te(h)−3':'Tadyacente=(Ti+Te)/2'):'Mismo Ti');const load=round(k*sf.area.value*dt);opaque+=load;
   add(sf.id+'-load-'+hour,sf.name,'q=K·A·Δt; '+(summer&&boundary==='exterior'?'Δteq=tabla+(Te15−Ti)−10':'temperatura de la cara adyacente según exposición'),vars,load,'kcal/h',summer?'Cuadro 3-III, pp.102–103 / pp.104–105':'pp.124–125');
  }
  for(const w of input.windows){const host=input.surfaces.find(s=>s.id===w.parentId),boundary=host?.quadriBoundary||'exterior',k=kOf(w),dt=boundary==='climatizado'?0:boundary==='no-climatizado'?(summer?t-3-ti:ti-(ti+te)/2):(summer?t-ti:ti-te),load=round(k*w.area.value*dt);glass+=load;add(w.id+'-trans-'+hour,w.name+' · transmisión','q=K·A·(Texterior−Ti) o pérdida Ti−Texterior',{K:calculated(k,'kcal/(h·m²·°C)',w.u.source),A:variable(w.area),delta:calculated(dt,'°C',boundary)},load,'kcal/h','pp.104/124');
   if(summer&&boundary==='exterior'){if(w.tilt.value!==0&&w.tilt.value!==90)throw new EngineeringError('Tabla solar: vidrio vertical u horizontal, revisá inclinación',w.name);const orient=w.tilt.value===0?'H':quadriOrientation(w.azimuth.value),irr=quadriSolar(orient,hour,numberOf(input.climate.location.latitude,'°'),q.solarBasis),I=irr.value,c=range(numberOf(w.quadriC||datum(1,'1','supuesto','Vidrio claro sin protección declarada'),'1'),0,1,w.name+'.c'),sun=range(numberOf(w.sunlitFraction[hour],'1'),0,1,w.name+'.soleada'),gain=round(w.area.value*sun*I*c);solar+=gain;
    add(w.id+'-solar-'+hour,w.name+' · radiación','qsolar=A·fracción_soleada·I·c; sin multiplicar SHGC',{A:variable(w.area),fraccion:variable(w.sunlitFraction[hour]),I:calculated(I,'kcal/(h·m²)',irr.source),c:variable(w.quadriC||datum(1,'1','supuesto','Vidrio claro pendiente de revisar'))},gain,'kcal/h','Cuadros 4/5-III, pp.106–108');
    if(!w.quadriC)warn('SHADING_PENDING','Elegí vidrio/protección de '+w.name+'. Se adoptó c=1, vidrio claro sin protección.',w.name);
   }
  }
  for(const link of links){const adjacent=numberOf(link.adjacentTemperature,'°C'),value=numberOf(link.u,'W/(m²·K)')*.86*link.area.value*(summer?adjacent-ti:ti-adjacent);partitions+=value;partValue.push(value/.86);}
  let Qo=opaque+glass+partitions;
  if(!summer&&q.floorMode==='terreno'){const floor=round(positive(numberOf(q.floorK,'kcal/(h·m²·°C)'))*input.geometry.length.value*input.geometry.width.value*(ti-numberOf(q.groundT,'°C')));Qo+=floor;soilLoss=floor;comp('piso',floor);add('floor-'+hour,'Piso sobre terreno','q=K·A·(Ti−Tterreno)',{K:variable(q.floorK),A:calculated(input.geometry.length.value*input.geometry.width.value,'m²','Geometría'),Ti:calculated(ti,'°C','Interior'),Tterreno:variable(q.groundT)},floor,'kcal/h','p.125');}
  const N=nonnegative(numberOf(input.internals.people.count,'1'),'Personas'),fraction=(x:Datum,label:string)=>range(numberOf(x,'1'),0,1,label),schedule=(arr:Datum[],label:string)=>{if(arr.length!==24)throw new EngineeringError('Se requieren 24 fracciones horarias',label);return fraction(arr[hour],label);};
  let peopleS=0,peopleL=0,lights=0,equipS=0,equipL=0;
  if(summer){peopleS=round(N*nonnegative(numberOf(input.internals.people.sensible,'W'))*.86*schedule(input.internals.people.schedule,'Personas'));peopleL=round(N*nonnegative(numberOf(input.internals.people.latent,'W'))*.86*schedule(input.internals.people.schedule,'Personas'));const lamp=input.internals.lights;lights=round(nonnegative(numberOf(lamp.installedPower,'W'))*.86*fraction(lamp.utilization,'Uso luces')*range(numberOf(lamp.allowance,'1'),1,1.2,'Factor lámpara')*fraction(lamp.spaceFraction,'Luces al local')*schedule(lamp.schedule,'Luces'));const eq=input.internals.equipment,sens=fraction(eq.sensibleFraction,'Sensible equipos'),lat=fraction(eq.latentFraction,'Latente equipos');if(sens+lat>1+1e-8)throw new EngineeringError('Fracciones sensible y latente de equipos >1');const pow=nonnegative(numberOf(eq.inputPower,'W'))*.86*fraction(eq.use,'Uso equipos')*fraction(eq.load,'Carga equipos')*fraction(eq.spaceFraction,'Equipos al ambiente')*schedule(eq.schedule,'Equipos');equipS=round(pow*sens);equipL=round(pow*lat);
   add('people-'+hour,'Personas','qs=N·qs/persona·horario; ql=N·ql/persona·horario',{N:variable(input.internals.people.count),qs:variable(input.internals.people.sensible),ql:variable(input.internals.people.latent),horario:variable(input.internals.people.schedule[hour])},peopleS+peopleL,'kcal/h','Cuadro 6-III, p.108');add('lights-'+hour,'Iluminación','q=.86·W·uso·balasto·fracción_local·horario',{W:variable(lamp.installedPower),uso:variable(lamp.utilization),balasto:variable(lamp.allowance),local:variable(lamp.spaceFraction),horario:variable(lamp.schedule[hour])},lights,'kcal/h','p.109');add('equipment-'+hour,'Equipos','q=.86·W·uso·carga·fracción_local·horario·(fs+fl)',{W:variable(eq.inputPower),uso:variable(eq.use),carga:variable(eq.load),local:variable(eq.spaceFraction),horario:variable(eq.schedule[hour]),fs:variable(eq.sensibleFraction),fl:variable(eq.latentFraction)},equipS+equipL,'kcal/h','p.109 · potencia declarada');}
  const we=q.humidityMode==='abaco'&&summer?nonnegative(numberOf(q.he,'g/kg')):out.w*1000,wi=q.humidityMode==='abaco'&&summer?nonnegative(numberOf(q.hi,'g/kg')):room.w*1000;
  const infil=nonnegative(numberOf(input.infiltrationACH,'ACH'))*input.geometry.length.value*input.geometry.width.value*input.geometry.height.value/60,infS=round(17*infil*(summer?t-ti:ti-te)),infL=summer?round(42*infil*(we-wi)):0;
  const duct=summer?round(Math.max(0,opaque+glass+solar)*dsummer):0;if(summer)add('quadri-duct-'+hour,'Calor de conductos','qconductos=max(0,qtrans_exterior+qsolar)·porcentaje',{base:calculated(opaque+glass+solar,'kcal/h','Envolvente y vidrios'),porcentaje:variable(q.ductSummer)},duct,'kcal/h','p.108 · porcentaje aplicado sólo a ganancia positiva');let QSi=summer?opaque+glass+solar+partitions+duct+peopleS+lights+equipS+infS:round(Qo*(1+zd+zh+zc))+infS;
  const QLi=summer?peopleL+equipL+infL:0,Qt=summer?0:QSi,QTi=QSi+QLi;
  const ts=summer?numberOf(input.climate.supplyTemperature,'°C'):numberOf(q.winterSupply,'°C'),delta=summer?ti-ts:ts-ti;positive(delta,'Diferencia de impulsión');let C=q.flowMode==='adoptado'?positive(numberOf(q.adoptedFlow,'m³/min'),'Caudal adoptado'):QSi>0?QSi/(17*delta):null;
  const effectiveTs=summer&&C?ti-QSi/(17*C):ts;
  if(QSi<=0)warn('NO_POSITIVE_SENSIBLE','No hay carga sensible positiva; no se dimensiona el caudal por enfriamiento/calefacción.',input.room);
  if(C&&q.flowMode==='adoptado'&&C+1e-8<QSi/(17*delta))warn('FLOW_INSUFFICIENT','El caudal adoptado no cubre la sensible con la temperatura de impulsión indicada.',input.room);
  const min=nonnegative(numberOf(q.minPerPerson,'m³/min'),'Aire por persona')*N,percent=range(numberOf(q.outsidePct,'1'),0,1,'Porcentaje aire exterior');
  const Ca=q.ventMode==='manual'?nonnegative(numberOf(input.outdoorFlow,'m³/min'),'Aire exterior'):Math.max((C||0)*percent,min);if(q.ventMode==='manual'&&Ca+1e-8<min)warn('AIR_BELOW_BOOK','Aire exterior por debajo del mínimo por persona elegido del manual.',input.room);
  if(C&&Ca>C)warn('OUTSIDE_EXCEEDS_FLOW','El aire exterior supera el circulatorio. Mezcla y puntos de serpentín no válidos; revisá caudales.',input.room);
  const Qse=round(17*Ca*(summer?t-ti:ti-te)),Qle=summer?round(42*Ca*(we-wi)):0,QTe=Qse+Qle,QT=QTi+QTe,QST=QSi+Qse,FCS=summer&&QTi>0?QSi/QTi:null;
  comp('envolvente',opaque);comp('ventanas',glass);comp('solar-vidrios',solar);comp('particiones',partitions);comp('conductos',summer?duct:Qt-Qo-infS);comp('personas',peopleS,peopleL);comp('iluminacion',lights);comp('equipos',equipS,equipL);comp('infiltracion',infS,infL);
  const vars=(vals:Record<string,number|null>)=>Object.fromEntries(Object.entries(vals).map(([key,value])=>[key,calculated(value===null?'No disponible':value,key==='C'||key==='Ca'?'m³/min':key==='FCS'?'1':'kcal/h','Balance Quadri · '+hour+'h')]));
  add('quadri-QSi-'+hour,summer?'QSi · sensible del local':'Qt · calefacción con suplementos',summer?'QSi=qtrans+qsolar+qconductos+qpersonas+qluces+qequipos+qinfiltración':'Qt=Qo·(1+Zd+Zh+Zc)+qinfiltración',summer?vars({opaque,glass,solar,partitions,duct,peopleS,lights,equipS,infS}):{...vars({Qo,infS}),Zd:variable(q.zd),Zh:calculated(zh*100,'%','winter-zh'),Zc:variable(q.zc)},QSi,'kcal/h',summer?'pp.108–119':'pp.126–131');
  add('quadri-QLi-'+hour,'QLi · latente del local','QLi=qlpersonas+qlequipos+qlinfiltración',vars({peopleL,equipL,infL}),QLi,'kcal/h','pp.108–113');add('quadri-Qo-'+hour,'Qo · pérdidas básicas','Qo=Σ K·A·(Ti−Tadyacente)',vars({opaque,glass,partitions,soilLoss}),Qo,'kcal/h','pp.124–125');
  add('quadri-QTi-'+hour,'QTi · local','QTi=QSi+QLi',vars({QSi,QLi}),QTi,'kcal/h','p.114');add('quadri-QTe-'+hour,'QTe · aire exterior',summer?'Qse=17·Ca·Δt; Qle=42·Ca·(he−hi); QTe=Qse+Qle':'Qse=17·Ca·(Ti−Te); QTe=Qse; sin humidificación',{...vars({Qse,Qle,Ca}),Te:calculated(t,'°C','Clima'),Ti:calculated(ti,'°C','Local'),he:calculated(we,'g/kg',q.humidityMode==='abaco'&&summer?q.he.source:'Estado exterior'),hi:calculated(wi,'g/kg',q.humidityMode==='abaco'&&summer?q.hi.source:'Estado interior')},QTe,'kcal/h','pp.113–119 / invierno p.129');
  add('quadri-QT-'+hour,'QT · demanda del equipo','QT=QTi+QTe',vars({QTi,QTe}),QT,'kcal/h',summer?'p.119':'p.131');add('quadri-QST-'+hour,'QST · sensible del equipo','QST=QSi+Qse',vars({QSi,Qse}),QST,'kcal/h','p.119');add('quadri-FCS-'+hour,'FCS · factor sensible del local','FCS=QSi/(QSi+QLi)',vars({QSi,QLi}),FCS,'1','p.74');
  add('quadri-C-'+hour,'C · caudal circulatorio',q.flowMode==='adoptado'?'C=caudal adoptado; comprobar QSi/(17·Δt)':'C=QSi/(17·Δt)',{...vars({QSi}),delta:calculated(delta,'°C','Interior / impulsión'),adoptado:variable(q.adoptedFlow),modo:calculated(q.flowMode,'1','Configuración')},C,'m³/min','p.77 / p.128');add('quadri-Ca-'+hour,'Ca · aire exterior',q.ventMode==='manual'?'Ca=caudal ingresado':'Ca=max(C·porcentaje, personas·mínimo)',{...vars({C}),porcentaje:variable(q.outsidePct),personas:variable(input.internals.people.count),minimo:variable(q.minPerPerson),ingresado:variable(input.outdoorFlow)},Ca,'m³/min','Cuadros 8/9-III, pp.111–112');
  let psych=summer&&C?quadriPsych(ti,wi,t,we,effectiveTs,C,Ca,QLi,pressure):{PRA:null,PRS:null,mix:null,supply:null,condensate:null,supplyW:null};let supplyT:number|null=summer?(C?effectiveTs:null):C?ti+Qt/(17*C):null;
  if(!summer&&C&&Ca<=C&&supplyT!==null){const a=Ca/C,wm=(1-a)*room.w+a*out.w,tm=(1-a)*ti+a*t;try{psych.mix=airState(datum(tm,'°C','calculado','Mezcla Quadri'),datum(rhFromHumidity(tm,wm,pressure)*100,'%','calculado','Mezcla'),p,'mix');psych.supply=airState(datum(supplyT,'°C','calculado','Qt /17C'),datum(rhFromHumidity(supplyT,wm,pressure)*100,'%','calculado','Sin humidificación'),p,'supply');psych.supplyW=wm*1000;}catch{}}
  if(psych.mix)td.push(quadriTrace('quadri-mix-'+hour,'Mezcla de aire','TM=(1−Ca/C)·Ti+(Ca/C)·Te; WM=(1−Ca/C)·hi+(Ca/C)·he; aproximación por caudales del manual',{C:calculated(C??'Sin caudal','m³/min','Balance'),Ca:calculated(Ca,'m³/min','Ventilación'),Ti:calculated(ti,'°C','Local'),Te:calculated(t,'°C','Exterior'),hi:calculated(summer?wi:room.w*1000,'g/kg','Humedad del local'),he:calculated(summer?we:out.w*1000,'g/kg','Humedad exterior')},[psych.mix.temperature.value,psych.mix.w*1000],'°C; g/kg','pp.70–73'));
  if(supplyT!==null&&supplyT>60)warn('HOT_SUPPLY','Impulsión de invierno supera 60 °C; revisar caudal.',input.room);
  if(C&&!psych.supply)warn('PSYCH_INFEASIBLE','Impulsión/mezcla no realizable con estos datos. Revisá caudal, temperatura y carga latente. PRA/PRS no se inventan.',input.room);
  add('quadri-PRA-'+hour,'PRA · rocío del aparato','Intersección recta FCS del local con Wsat(T); pendiente=(QLi/QSi)·17/42',{...vars({QSi,QLi}),Ti:calculated(ti,'°C','Local'),hi:calculated(wi,'g/kg','Local'),P:variable(p)},psych.PRA,'°C','pp.74–79 · resolución numérica de recta/curva');add('quadri-PRS-'+hour,'PRS · rocío del serpentín','Intersección prolongación de recta M→I con Wsat(T)',{TM:calculated(psych.mix?.temperature.value??'No válido','°C','Mezcla'),WM:calculated(psych.mix?psych.mix.w*1000:'No válido','g/kg','Mezcla'),TI:calculated(supplyT??'No válido','°C','Impulsión'),WI:calculated(psych.supplyW??'No válido','g/kg','Impulsión')},psych.PRS,'°C','pp.82–87 · resolución numérica de recta/curva');
  add('quadri-condensate-'+hour,'Condensado','V=C·60/vM·(WM−WI)/1000',{...vars({C}),vM:calculated(psych.mix?.v??'No válido','m³/kg_da','Estado mezcla'),deltaW:calculated(psych.mix&&psych.supply?(psych.mix.w-psych.supply.w)*1000:'No válido','g/kg','Estados mezcla e impulsión')},psych.condensate,'kg/h','pp.83–87');
  const selection=q.equipmentTotal.value>0?{checked:!!q.equipmentSource.trim()&&q.equipmentSensible.value>0&&q.equipmentFlow.value>0,total:numberOf(q.equipmentTotal,'kcal/h')>=QT,sensible:numberOf(q.equipmentSensible,'kcal/h')>=QST,flow:C!==null&&numberOf(q.equipmentFlow,'m³/h')>=C*60}:null;
  [q.equipmentTotal,q.equipmentSensible,q.equipmentFlow].forEach(v=>nonnegative(v.value,'Ficha equipo'));if(q.equipmentSensible.value>q.equipmentTotal.value)throw new EngineeringError('Capacidad sensible > total');
  details.push({hour,QSi,QLi,QTi,Qse,Qle,QTe,QT,QST,Qo,Qt,FCS,C,Ca,PRA:psych.PRA,PRS:psych.PRS,supplyT,supplyW:psych.supplyW,mix:psych.mix,supply:psych.supply,condensate:psych.condensate,psychValid:!!psych.supply,zh,selection});
  const ht:Trace[]=[];for(const [key,v] of Object.entries(components))ht.push(quadriTrace('component-'+key+'-'+hour,key,'Σ aportes de '+key,{},v.sensible+v.latent,'W','Capítulos II/III'));
  ht.push(quadriTrace('zone-'+hour,'Carga del local · '+hour+' h','QTi=(QSi+QLi)/.86; redondeo '+q.rounding,vars({QSi,QLi}),QTi/.86,'W','p.114'));td.push(...ht);hours.push({hour,sensible:QSi/.86,latent:QLi/.86,total:QTi/.86,systemSensible:QST/.86,systemLatent:(QLi+Qle)/.86,systemTotal:QT/.86,coilDemand:QT/.86,components,trace:ht});
  if(psych.supply){const states=psych.supply.trace.map(tr=>({...tr,id:tr.id.replace(/^(mix|supply)-/,'$1-'+hour+'-')}));td.push(...states);if(psych.mix)td.push(...psych.mix.trace.map(tr=>({...tr,id:tr.id.replace(/^(mix|supply)-/,'$1-'+hour+'-')})));}
 }
 const peak=hours.reduce((a,b)=>b.total>a.total?b:a),systemPeak=hours.reduce((a,b)=>b.systemTotal>a.systemTotal?b:a),detail=details.find(x=>x.hour===peak.hour)!;
 if(detail.psychValid){const atHour=outdoor[domain.indexOf(peak.hour)];if(summer){const psych=quadriPsych(ti,q.humidityMode==='abaco'?q.hi.value:room.w*1000,atHour.temperature.value,q.humidityMode==='abaco'?q.he.value:atHour.w*1000,detail.supplyT!,detail.C!,detail.Ca,detail.QLi,pressure);peakSupply=psych.supply!;}else peakSupply=airState(datum(detail.supplyT!,'°C','calculado','Impulsión calefacción'),datum(rhFromHumidity(detail.supplyT!,detail.supplyW!/1000,pressure)*100,'%','calculado','Sin humidificación'),p,'supply');}
 td.push(...peakSupply.trace);add('peak','Pico local',summer?'max_h QTi, h=06…18 solar':'Qt estacionario',{},peak.total,'W',summer?'pp.98–119':'pp.124–131');add('system-peak','Demanda máxima del equipo',summer?'max_h QT, h=06…18 solar':'QT estacionario',{},systemPeak.systemTotal,'W','pp.119/131');add('supply-flow','Circulación de aire','m³/s=C/60',{C:calculated(detail.C??'Sin dimensionar','m³/min','quadri-C-'+peak.hour)},detail.C===null?null:detail.C/60,'m³/s','pp.77/128');
 for(const link of links){const value=numberOf(link.u,'W/(m²·K)')*link.area.value*(summer?numberOf(link.adjacentTemperature,'°C')-ti:ti-numberOf(link.adjacentTemperature,'°C'));td.push(quadriTrace('partition-'+link.id,link.name,'q=U·A·ΔT; sentido según verano/invierno',{U:variable(link.u),A:variable(link.area),Ti:calculated(ti,'°C','Local'),Tadyacente:variable(link.adjacentTemperature)},domain.map(()=>value),'W','p.104/124'));}
 return {input,engineVersion:QUADRI_VERSION,mode:'Quadri',hours,peak,systemPeak,states:{outdoor,room,supply:peakSupply},supplyFlow:detail.C===null?null:detail.C/60,moistureRemoval:detail.condensate===null?null:detail.condensate/3600,latentCheck:summer?detail.psychValid:null,warnings:uniqueWarnings(warnings),trace:td.map(tr=>tr.source.includes('MOTOR_TERMICO_V2')?{...tr,source:'Auxiliar numérico de geometría / propiedades del aire · '+tr.source,engineVersion:QUADRI_VERSION}:tr),quadri:{season:q.season,hours:details,peak:detail}};
}
