import type {Location,Radiation,Result,Trace} from './types.ts';
import {finite,numberOf,hourly,range,nonnegative,positive,trace,variable,calculated,EngineeringError} from './core.ts';
const radians=(d:number)=>d*Math.PI/180,degrees=(r:number)=>r*180/Math.PI;
export function solarPosition(location:Location,hour:number):Result<{altitude:number;azimuth:number;e0:number;solarHour:number}> {if(!Number.isInteger(location.day)||!Number.isInteger(location.year))throw new EngineeringError('Fecha de diseño inválida','solar.fecha');const n=range(location.day,1,location.year%4===0&&(location.year%100!==0||location.year%400===0)?366:365,'día'),L=range(numberOf(location.latitude,'°'),-90,90,'latitud'),lon=range(numberOf(location.longitude,'°'),-180,180,'longitud'),tz=range(numberOf(location.timezone,'h'),-12,14,'zona horaria');range(hour,0,24,'hora');const delta=23.45*Math.sin(radians(360*(284+n)/365)),B=radians(360*(n-1)/365),et=229.18*(.000075+.001868*Math.cos(B)-.032077*Math.sin(B)-.014615*Math.cos(2*B)-.040849*Math.sin(2*B)),ast=hour+et/60+(lon-15*tz)/15,H=radians(15*(ast-12)),l=radians(L),d=radians(delta),alt=degrees(Math.asin(Math.max(-1,Math.min(1,Math.sin(l)*Math.sin(d)+Math.cos(l)*Math.cos(d)*Math.cos(H)))));
 // atan2 in the contract's south=0, west-positive convention; valid in both hemispheres.
 const az=degrees(Math.atan2(Math.cos(d)*Math.sin(H),Math.sin(l)*Math.cos(d)*Math.cos(H)-Math.cos(l)*Math.sin(d))),e0=1367*(1+.033*Math.cos(radians(360*n/365)));
 return {value:{altitude:alt,azimuth:az,e0,solarHour:ast},warnings:[],trace:[trace('solar-'+hour,'Posición solar','δ=23.45sin[360(284+n)/365]; AST=LST+ET/60+(LON−15TZ)/15; sinβ=sinL sinδ+cosL cosδ cosH; φ=atan2(cosδ sinH, sinL cosδ cosH−cosL sinδ)',{latitud:variable(location.latitude),longitud:variable(location.longitude),TZ:variable(location.timezone),n:calculated(n,'día','Fecha seleccionada'),LST:calculated(hour,'h','Hora civil sin horario de verano'),delta:calculated(delta,'°','§5.2'),ET:calculated(et,'min','§5.3'),H:calculated(degrees(H),'°','§5.5')},[alt,az,ast,e0],'°; °; h; W/m²','5.2–5.8')]};}
export function tauRadiation(altitude:number,e0:number,tauBeam:number,tauDiffuse:number):{dni:number;dhi:number} {range(altitude,-90,90,'altura solar');positive(e0,'E0');positive(tauBeam,'τb');positive(tauDiffuse,'τd');if(altitude<=0)return {dni:0,dhi:0};const m=1/(Math.sin(radians(altitude))+.50572*(6.07995+altitude)**-1.6364),ab=1.454-.406*tauBeam-.268*tauDiffuse+.021*tauBeam*tauDiffuse,ad=.507+.205*tauBeam-.080*tauDiffuse-.190*tauBeam*tauDiffuse;return {dni:e0*Math.exp(-tauBeam*m**ab),dhi:e0*Math.exp(-tauDiffuse*m**ad)};}
export function planeRadiation(location:Location,radiation:Radiation,tilt:number,azimuth:number,id='plane'):Result<{beam:number[];diffuse:number[];reflected:number[];total:number[]}> {if(!['manual','tau'].includes(radiation.mode)||!['isotropic','hay-davies'].includes(radiation.transposition))throw new EngineeringError('Modelo solar no válido','solar');range(tilt,0,180,id+'.inclinación');range(azimuth,-180,180,id+'.azimut');const albedo=range(numberOf(radiation.albedo,'1'),0,1,'albedo');const dni=radiation.mode==='manual'?hourly(radiation.dni,'W/m²','DNI'):[],dhi=radiation.mode==='manual'?hourly(radiation.dhi,'W/m²','DHI'):[];dni.concat(dhi).forEach(x=>nonnegative(x,'radiación'));if(radiation.mode==='tau'&&(!radiation.tauBeam||!radiation.tauDiffuse))throw new EngineeringError('Faltan τb/τd climáticos; no se generan valores universales','solar','MISSING_TAU');const beam:number[]=[],diffuse:number[]=[],reflected:number[]=[],td:Trace[]=[];
 for(let t=0;t<24;t++){const s=solarPosition(location,t);td.push(...s.trace);const sun=s.value;const r=radiation.mode==='manual'?{dni:dni[t],dhi:dhi[t]}:tauRadiation(sun.altitude,sun.e0,numberOf(radiation.tauBeam!,'1'),numberOf(radiation.tauDiffuse!,'1'));if(sun.altitude<=0&&(r.dni>0||r.dhi>0))throw new EngineeringError('Radiación positiva con sol bajo el horizonte; revisar hora civil/TZ/perfil','solar['+t+']','NIGHT_RADIATION');if(radiation.mode==='tau'){const tb=numberOf(radiation.tauBeam!,'1'),tdiff=numberOf(radiation.tauDiffuse!,'1'),m=sun.altitude>0?1/(Math.sin(radians(sun.altitude))+.50572*(6.07995+sun.altitude)**-1.6364):0,ab=1.454-.406*tb-.268*tdiff+.021*tb*tdiff,ad=.507+.205*tb-.080*tdiff-.190*tb*tdiff;td.push(trace(id+'-tau-'+t,'Radiación ASHRAE Tau','DNI=E0 exp(−τb m^ab); DHI=E0 exp(−τd m^ad); m=1/[sinβ+0.50572(6.07995+β)^−1.6364]; ab=1.454−0.406τb−0.268τd+0.021τbτd; ad=0.507+0.205τb−0.080τd−0.190τbτd',{tauBeam:variable(radiation.tauBeam!),tauDiffuse:variable(radiation.tauDiffuse!),m:calculated(m,'1','Masa óptica relativa; 0 indica noche'),ab:calculated(ab,'1','ASHRAE Tau · EnergyPlus Engineering Reference'),ad:calculated(ad,'1','ASHRAE Tau · EnergyPlus Engineering Reference'),E0:calculated(sun.e0,'W/m²','Posición solar'),beta:calculated(sun.altitude,'°','Posición solar')},[r.dni,r.dhi],'W/m²','5.10',sun.altitude<=0?['Sin sol: DNI y DHI iguales a cero']:[]));}const sin=Math.max(0,Math.sin(radians(sun.altitude))),cost=Math.sin(radians(sun.altitude))*Math.cos(radians(tilt))+Math.cos(radians(sun.altitude))*Math.sin(radians(tilt))*Math.cos(radians(sun.azimuth-azimuth)),inc=Math.max(0,cost),ghi=r.dni*sin+r.dhi;
 const b=r.dni*inc;let d=r.dhi*(1+Math.cos(radians(tilt)))/2;
 if(radiation.transposition==='hay-davies'&&sin>1e-6){const ai=range(r.dni/sun.e0,0,1,'índice anisotrópico');d=r.dhi*(ai*inc/sin+(1-ai)*(1+Math.cos(radians(tilt)))/2);}
 const rr=ghi*albedo*(1-Math.cos(radians(tilt)))/2;beam.push(b);diffuse.push(d);reflected.push(rr);
 td.push(trace(id+'-'+t,'Irradiancia sobre plano',radiation.transposition==='hay-davies'?'Et,b=DNI max(0,cosθ); Et,d=DHI[Ai Rb+(1−Ai)(1+cosΣ)/2]; Et,r=GHI ρg(1−cosΣ)/2':'Et,b=DNI max(0,cosθ); Et,d=DHI(1+cosΣ)/2; Et,r=GHI ρg(1−cosΣ)/2',{DNI:radiation.mode==='manual'?variable(radiation.dni[t]):calculated(r.dni,'W/m²','ASHRAE Tau §5.10'),DHI:radiation.mode==='manual'?variable(radiation.dhi[t]):calculated(r.dhi,'W/m²','ASHRAE Tau §5.10'),tauBeam:radiation.tauBeam?variable(radiation.tauBeam):calculated('No aplica','1','Perfil manual'),tauDiffuse:radiation.tauDiffuse?variable(radiation.tauDiffuse):calculated('No aplica','1','Perfil manual'),cosTheta:calculated(cost,'1','§5.11'),tilt:calculated(tilt,'°','Inclinación ingresada'),azimuth:calculated(azimuth,'°','Azimut de superficie ingresado'),albedo:variable(radiation.albedo),beam:calculated(b,'W/m²','Et,b'),diffuse:calculated(d,'W/m²','Et,d'),reflected:calculated(rr,'W/m²','Et,r')},b+d+rr,'W/m²','5.10–5.12'));
 }
 return {value:{beam,diffuse,reflected,total:beam.map((b,t)=>b+diffuse[t]+reflected[t])},trace:td,warnings:[]};}
