const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../engineering-core.js'),C=require('../suite-core.js');
const data=()=>({projects:[{id:'a',name:'Activo',status:'Activo',progress:60,nextAction:'Revisar',targetDate:'2026-10-01'},{id:'b',name:'Espera',status:'Esperando tercero',progress:20},{id:'c',name:'Finalizado',status:'Finalizado',progress:100}],milestones:[{id:'m',projectId:'a',status:'En curso',dueDate:'2026-10-06'},{id:'done',projectId:'a',status:'Cumplido',dueDate:'2026-10-01'},{id:'archived',projectId:'c',status:'Pendiente',dueDate:'2026-10-01'}],documents:[],equipment:[]});
test('Active progress, overdue and WIP exclude archived/completed tasks',()=>{const d=data(),m=E.metrics(d,C.tasks(d,'2026-10-04'),{},'2026-10-04');assert.equal(m.progress,40);assert.equal(m.pending,2);assert.equal(m.overdue,1);assert.equal(m.wip,1);assert.equal(m.ppc,null);assert.equal(m.waitAverage,null);assert.equal(m.health,'En riesgo');});
test('Wait average excludes absent, future and invalid dates; coverage is explicit',()=>{const d=data();d.projects.push({id:'x',status:'Esperando tercero'});for(const date of ['2026-99-99','2026-02-31','2026-10-05'])assert.equal(E.metrics(d,[],{b:{waitingSince:date}},'2026-10-04').waitAverage,null);const m=E.metrics(d,[],{b:{waitingSince:'2026-09-29'}},'2026-10-04');assert.equal(m.waitAverage,5);assert.equal(m.waitCoverage,1);assert.equal(m.waiting,2);});
test('Closed risks/constraints do not affect health; approved docs use explicit status',()=>{const d=data();d.projects[0].blocker='Interferencia';d.documents=[{projectId:'a',status:'Aprobado'},{projectId:'a',status:'Vigente'},{projectId:'a',status:'Reemplazado'}];const meta={a:{controls:[{kind:'Riesgo',severity:'Alta',status:'Cerrado'},{kind:'Restricción',status:'Abierto'},{kind:'Entregable',status:'Aprobado'},{kind:'Cambio',status:'Abierto'}]}};let m=E.metrics(d,[],meta,'2026-10-04');assert.equal(m.restrictions,2);assert.equal(m.risks,0);assert.equal(m.changes,1);assert.equal(m.approved,2);assert.equal(m.deliverables,3);meta.a.controls[0].status='Abierto';assert.equal(E.metrics(d,[],meta,'2026-10-04').health,'Crítica');});
test('PPC counts only explicit weekly commitments and on-time completion in Argentina',()=>{const d=data(),meta={a:{taskFacts:{one:{committedWeek:'2026-09-28',dueDate:'2026-10-02',completedAt:'2026-10-03T01:00:00Z'},two:{committedWeek:'2026-09-28',dueDate:'2026-10-01',completedAt:'2026-10-02T16:00:00Z'},three:{committedWeek:'2026-09-21',dueDate:'2026-09-23',completedAt:'2026-09-23T16:00:00Z'}}}};const m=E.metrics(d,[],meta,'2026-10-04');assert.equal(m.committed,2);assert.equal(m.fulfilled,1);assert.equal(m.ppc,50);});
test('Project scope never mixes another project controls, wait or deadlines',()=>{const d=data(),meta={b:{waitingSince:'2026-09-28',controls:[{kind:'Riesgo',severity:'Alta',status:'Abierto'}]}};const m=E.metrics(d,C.tasks(d,'2026-10-04'),meta,'2026-10-04','a');assert.equal(m.risks,0);assert.equal(m.waiting,0);assert.equal(m.active,1);assert.equal(m.progress,60);assert.equal(m.upcoming.length,1);assert.equal(m.upcoming[0].id,'m');});
test('No records produces missing indicators rather than invented averages',()=>{const m=E.metrics({projects:[],milestones:[],documents:[],equipment:[]},[],{},'2026-10-04');assert.equal(m.health,'Sin datos');assert.equal(m.progress,null);assert.equal(m.waitAverage,null);assert.equal(m.ppc,null);assert.equal(E.week('2026-10-04'),'2026-09-28');assert.equal(E.week('2026-10-05'),'2026-10-05');});
