import {g,read as readTracker} from './tracker-sync.js';



export const KEYS=['thermabot.tracker.v1','thermabot.suite.v1','thermabot.workspace.v1','thermabot.proyectos.v1','thermabot-building-v21-trial'];

const reply=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store'}});

export function validate(value){let count=0;function walk(x,depth=0){if(++count>300000||depth>50)throw Error('Datos demasiado complejos');if(x&&typeof x==='object')for(const [k,v]of Object.entries(x)){if(['__proto__','constructor','prototype'].includes(k))throw Error('Propiedad no permitida');walk(v,depth+1);}}walk(value);if(!value||value.format!=='thermabot-cloud-v1'||typeof value.revision!=='string'||!value.values||Array.isArray(value.values))throw Error('Base incompatible');for(const [k,v]of Object.entries(value.values)){if(!KEYS.includes(k)||typeof v!=='string')throw Error('Dato no permitido');walk(JSON.parse(v));}return value;}

async function current(env){const MASTER=env.THERMABOT_DRIVE_MASTER_ID;const meta=await(await g(env,`https://www.googleapis.com/drive/v2/files/${MASTER}?fields=id,etag`)).json();const data=validate(await(await g(env,`https://www.googleapis.com/drive/v3/files/${MASTER}?alt=media`)).json());if(!Object.keys(data.values).length){const tracker=await readTracker(env);data.values['thermabot.tracker.v1']=JSON.stringify(tracker);}return {data,etag:meta.etag};}

export async function onRequest(ctx){const req=ctx.request,MASTER=ctx.env.THERMABOT_DRIVE_MASTER_ID,PREVIOUS=ctx.env.THERMABOT_DRIVE_BACKUP_ID;try{if(!MASTER||!PREVIOUS||!ctx.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||!ctx.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY)return reply({error:'Drive pendiente: falta configurar la conexión privada de Google.'},503);if(req.method==='GET')return reply((await current(ctx.env)).data);if(req.method!=='PUT')return reply({error:'Método no permitido'},405);if(req.headers.get('Origin')!==new URL(req.url).origin||req.headers.get('X-THERMABOT-Save')!=='1')return reply({error:'Origen no permitido'},403);if(!req.headers.get('Content-Type')?.startsWith('application/json'))return reply({error:'Se requiere JSON'},415);const text=await req.text();if(new TextEncoder().encode(text).length>8*1024*1024)return reply({error:'Base demasiado grande; exportá los informes por separado.'},413);let next;try{next=validate(JSON.parse(text));}catch{return reply({error:'Datos inválidos'},400);}const {data,etag}=await current(ctx.env);if(next.revision!==data.revision)return reply({error:'Otro dispositivo cambió la base. Conservamos tu copia local; recargá después de exportarla.'},409);if(!etag)return reply({error:'Drive no entregó una versión verificable; no se sobrescribió la base.'},503);if(Object.keys(data.values).some(k=>!(k in next.values)))return reply({error:'No se permite eliminar colecciones completas'},409);const before=JSON.parse(data.values['thermabot.tracker.v1']||'{}'),after=JSON.parse(next.values['thermabot.tracker.v1']||'{}');if((before.projects||[]).length>=5&&(after.projects||[]).length<(before.projects||[]).length/2)return reply({error:'Protección activa: se rechazó una reducción masiva de proyectos.'},409);
const afterById=new Map((after.projects||[]).map(p=>[p.id,p])),critical=['installedTR','installedOn','completedOn'];const lost=[];for(const p of before.projects||[]){const q=afterById.get(p.id);if(!q)continue;for(const key of critical){const had=p[key]!==null&&p[key]!==undefined&&p[key]!=='';const has=q[key]!==null&&q[key]!==undefined&&q[key]!=='';if(had&&!has)lost.push(p.id+':'+key);}}if(lost.length)return reply({error:'Protección activa: se rechazó un guardado que eliminaba datos críticos de capacidad o fechas.',protected:lost.slice(0,20)},409);await g(ctx.env,`https://www.googleapis.com/upload/drive/v3/files/${PREVIOUS}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});next.revision=crypto.randomUUID();next.updatedAt=new Date().toISOString();const result=await g(ctx.env,`https://www.googleapis.com/upload/drive/v2/files/${MASTER}?uploadType=media`,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':etag},body:JSON.stringify(next)});await result.text();return reply({revision:next.revision,updatedAt:next.updatedAt});}catch(e){return reply({error:String(e.message).includes('412')?'La base cambió durante el guardado. Tu borrador se conserva.':'No se pudo verificar el guardado en Drive. Revisá la conexión y los permisos.'},String(e.message).includes('412')?409:502);}}

