import {calculateBuilding} from '../quadri/src/engine/edificio.ts';
import {enableQuadri} from '../quadri/src/engine/quadri.ts';
import {migrateEnvelope} from '../quadri/src/engine/geometria_edificio.ts';
import {roomReview} from '../quadri/src/engine/revision_carga.ts';
import {exportWaterLoads,WATER_LABELS,WATER_STEPS} from '../quadri/src/engine/integracion_agua.ts';
import {validateImportedData} from '../quadri/src/engine/seguridad_datos.ts';
import {calculateWater} from './motor_web.ts';
const KEY='thermabot-building-v21-trial',BAL='thermabot.proyectos.v1',app=document.getElementById('waterApp')!,dialog=document.getElementById('waterDialog') as HTMLDialogElement;
const read=(key:string,def:any)=>JSON.parse(localStorage.getItem(key)||JSON.stringify(def)),clone=(x:any)=>JSON.parse(JSON.stringify(x)),esc=(x:any)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const fmt=(x:any,d=2)=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString('es-AR',{maximumFractionDigits:d,minimumFractionDigits:d}):'—',btn=(t:string,a='',p=false)=>'<button type="button" '+a+' class="'+(p?'primary':'')+'">'+t+'</button>',fToC=(f:number)=>(f-32)/1.8,cToF=(c:number)=>c*1.8+32,GP=.227124707,KW=3412.141633127942;
const params=new URLSearchParams(location.search);let projectId=params.get('projectId')||'',sourceId='',base:'local'|'equipo'='local',tab='Diseño',loads:any=null,result:any=null,source:any=null,error='',dirty=false,savedId=params.get('waterId')||'',timer:any;
function blank(){return {material:'steel',tabla_leq:'table11',tuberias:{},exposiciones:{},layout:{tipo:'reverse_return',diversidad:'sin_diversidad',orden_exposiciones:[],secciones:[],circuitos:[]},catalogo_fcu:[],tanque:{volumen_equipos_gal:null,E:null,P_a:null,P_f:null,fuente:''},condiciones_diseno:{T_OA_verano_F:95,T_OA_invierno_F:35,T_interior_verano_F:75,T_interior_invierno_F:70,T_agua_frio_F:44.6,T_agua_caliente_F:140,delta_T_agua_F:9,delta_T_calef_F:18,horas_operacion_anual:6000,friction_rate_diseno:10,rugosidad_ft:null,viscosidad_frio_ft2_s:null,viscosidad_calef_ft2_s:null,fuente_fluido:'',fluido:'water'}};}
let config:any=blank();
function sources(){const store=read(KEY,{}),records=new Map();for(const b of read(BAL,[]))if(b.method==='quadri-v3'&&b.quadri?.building)records.set(b.id,{id:b.id,name:b.nombre,record:b.quadri});for(const r of store.saved||[])if(r.building&&!records.has(r.id))records.set(r.id,{id:r.id,name:r.building.name+' · '+new Date(r.date).toLocaleString('es-AR'),record:r});return [...records.values()];}
function importSource(id:string){
 const b=sources().find(b=>b.id===id);if(!b)throw Error('No se encontró un balance completo guardado.');const build=clone(b.record.building);build.rooms=build.rooms.map((r:any)=>enableQuadri(migrateEnvelope(r)));const summer=clone(build),winter=clone(build);summer.rooms.forEach((r:any)=>r.quadri.season='verano');winter.rooms.forEach((r:any)=>r.quadri.season='invierno');
 const reviewed=build.rooms.every((r:any)=>roomReview(r,b.record.reviews?.[r.id],(build.partitions||[]).filter((p:any)=>p.roomAId===r.id||p.roomBId===r.id)).every(x=>x.reviewed));
 const next=exportWaterLoads(calculateBuilding(summer),calculateBuilding(winter),base,{revisado:reviewed,balanceId:id,balanceFecha:b.record.date});next.revision.balanceId=id;
 sourceId=id;source=b;loads=next;projectId=build.projectId;
 const ids=new Set(loads.espacios.map((e:any)=>e.id));if(config.layout.secciones.some((r:any)=>(r.espacios_servidos||[]).some((x:string)=>!ids.has(x)))||config.layout.circuitos.some((r:any)=>!ids.has(r.espacio_id))){config.layout.secciones=[];config.layout.circuitos=[];config.exposiciones={};notify('Cambió la lista de ambientes: cargá el trazado correspondiente a este balance.');}
 recalc();
}
function recalc(){error='';result=null;if(loads)try{result=calculateWater(loads,config);}catch(e){error=(e as Error).message;}}
function notify(t:string){const el=document.getElementById('notice')!;el.textContent=t;el.hidden=false;clearTimeout(timer);timer=setTimeout(()=>el.hidden=true,5500);}
function writableStore(){const store=read(KEY,{});if(store.version!==3&&source?.record.building){const b=clone(source.record.building);Object.assign(store,{version:3,input:clone(source.record.input||b.rooms[0]),projectId:b.projectId,rooms:b.rooms,partitions:b.partitions||[],saved:sources().map(s=>s.record),projects:read('thermabot.tracker.v1',{projects:[]}).projects.map((p:any)=>({id:p.id,name:p.name,place:p.establishment||'',system:p.system||'',progress:p.progress||0,status:p.status||''}))});}return store;}
function storeDraft(){if(!projectId||!loads)return;try{const store=writableStore();store.waterDrafts??={};store.waterDrafts[projectId]={sourceId,base,config:clone(config),updatedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(store));dirty=false;}catch(e){notify('No se guardó el borrador: '+(e as Error).message);}}
function changed(){dirty=true;recalc();storeDraft();render();}
function persist(){
 if(!loads)throw Error('Elegí un balance térmico como punto de partida.');recalc();if(!result)throw Error(error||'No se pudo calcular.');
 const store=writableStore();store.waterCalculations??=[];const record={id:crypto.randomUUID(),name:'Agua · '+loads.proyecto.nombre,date:new Date().toISOString(),projectId,sourceId,base,config:clone(config),loads:clone(loads),output:clone(result)};store.waterCalculations.unshift(record);localStorage.setItem(KEY,JSON.stringify(store));savedId=record.id;storeDraft();parent.postMessage({type:'thermabot:water-saved',waterId:record.id,projectId,name:record.name},location.origin);notify(result.apto?'Cálculo de agua guardado y vinculado al proyecto.':'Versión preliminar guardada con sus datos pendientes.');render();
}
function download(name:string,data:any){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function jsonImport(callback:(x:any)=>void){const f=document.createElement('input');f.type='file';f.accept='.json,application/json';f.onchange=async()=>{try{if(!f.files?.[0])return;if(f.files[0].size>8e6)throw Error('Usá un archivo menor a 8 MB.');const data=JSON.parse(await f.files[0].text());validateImportedData(data);callback(data);}catch(e){notify((e as Error).message);}};f.click();}
function field(label:string,key:string,v:any,unit='',factor=1,offset=0){return '<label>'+esc(label)+(unit?' · '+esc(unit):'')+'<input type="number" step="any" data-field="'+key+'" data-factor="'+factor+'" data-offset="'+offset+'" value="'+(v==null?'':Number(((v-offset)/factor).toPrecision(10)))+'"></label>';}
const tfield=(label:string,key:string,v:any)=>'<label>'+label+'<input data-text="'+key+'" value="'+esc(v)+'"></label>';
const opts=(rows:any[],current:any)=>rows.map(([value,title])=>'<option value="'+esc(value)+'" '+(value===current?'selected':'')+'>'+esc(title)+'</option>').join('');
function design(){const c=config.condiciones_diseno;return '<h2>Condiciones de agua</h2><p class="subtle">Valores iniciales editables. Cargas y condiciones interiores vienen del balance; las fichas de fan-coils deben corresponder a estas condiciones.</p><div class="grid">'+field('Impulsión fría','c.T_agua_frio_F',c.T_agua_frio_F,'°C',1.8,32)+field('Impulsión caliente','c.T_agua_caliente_F',c.T_agua_caliente_F,'°C',1.8,32)+field('Salto térmico frío','c.delta_T_agua_F',c.delta_T_agua_F,'°C',1.8)+field('Salto térmico calor','c.delta_T_calef_F',c.delta_T_calef_F,'°C',1.8)+field('Operación anual','c.horas_operacion_anual',c.horas_operacion_anual,'h')+field('Pérdida unitaria máxima','c.friction_rate_diseno',c.friction_rate_diseno,'m.c.a. / 100 m')+'</div><h3>Propiedades para pérdidas reales</h3><p class="subtle">Ingresá datos documentados. El límite de diseño no reemplaza el cálculo de fricción.</p><div class="grid">'+field('Rugosidad absoluta','c.rugosidad_ft',c.rugosidad_ft,'mm',1/.3048/1000)+field('Viscosidad cinemática · frío','c.viscosidad_frio_ft2_s',c.viscosidad_frio_ft2_s,'mm²/s',1/.09290304/1e6)+field('Viscosidad cinemática · calor','c.viscosidad_calef_ft2_s',c.viscosidad_calef_ft2_s,'mm²/s',1/.09290304/1e6)+tfield('Fuente de fluido y rugosidad','c.fuente_fluido',c.fuente_fluido)+'</div><label>Material<select data-material>'+opts([['steel','Acero Schedule 40 · tablas suministradas'],['copper','Cobre · importar catálogo verificado']],config.material)+'</select></label><label>Diversidad<select data-diversity>'+opts([['sin_diversidad','Sin reducción · caudales nominales FCU'],['chart6','Chart 6 · orden de exposiciones'],['coincidente','Coincidencia · requiere catálogo a caudal térmico']],config.layout.diversidad)+'</select></label>'+(config.layout.diversidad==='chart6'?'<label>Orden hidráulico de exposiciones (separar con comas)<input data-order value="'+esc(config.layout.orden_exposiciones.join(', '))+'" placeholder="N, E, S, O"></label>'+loads?.espacios.map((e:any)=>'<label>'+esc(e.nombre)+' · exposición<input data-exposure="'+esc(e.id)+'" value="'+esc(config.exposiciones[e.id]||'')+'"></label>').join(''):'')+'<details><summary>Configuración avanzada / catálogo de cobre</summary><div class="actions" style="margin-top:10px">'+btn('Importar configuración JSON','data-import-config')+btn('Exportar configuración','data-export-config')+'</div><p class="subtle">Compatible con configuracion_agua del contrato Python. No importa cargas duplicadas.</p></details>';}
function fcu(){return '<div class="actions"><h2 style="flex:1">Catálogo de fan-coils</h2>'+btn('+ Modelo','data-add-fcu',true)+btn('Importar catálogo','data-import-fcu')+'</div><p class="subtle">El motor elige el menor modelo que cumple total, sensible, calefacción, caudal y condiciones verificadas. No se generan fichas ficticias.</p><div class="table"><table><thead><tr><th>Modelo</th><th>Frío / sensible</th><th>Calor</th><th>Caudal nominal</th><th></th></tr></thead><tbody>'+config.catalogo_fcu.map((m:any,i:number)=>'<tr><td>'+esc(m.codigo)+'<small>'+esc(m.fuente)+'</small></td><td>'+fmt(m.Q_tot_nom_btuh/KW)+' / '+fmt(m.Q_sens_nom_btuh/KW)+' kW</td><td>'+fmt(m.Q_calef_nom_btuh==null?null:m.Q_calef_nom_btuh/KW)+' kW</td><td>'+fmt(m.GPM_nom*GP)+' m³/h</td><td>'+btn('Editar','data-edit-fcu="'+i+'"')+' '+btn('×','aria-label="Eliminar modelo" data-delete-fcu="'+i+'"')+'</td></tr>').join('')+'</tbody></table></div>'+(!config.catalogo_fcu.length?'<p class="empty">Agregá la ficha de un fabricante para continuar la selección.</p>':'');}
function network(){const l=config.layout;return '<div class="actions"><h2 style="flex:1">Red de distribución</h2>'+btn('+ Tramo','data-add-section',true)+'</div><label>Retorno<select data-layout>'+opts([['reverse_return','Retorno invertido'],['direct_return','Retorno directo']],l.tipo)+'</select></label><div class="actions">'+btn('Crear ida y retorno por ambiente','data-room-network')+btn('+ Circuito de bomba','data-add-circuit')+'</div><p class="subtle">Asigná ambientes a cada tramo. Para bomba, cada circuito debe incluir toda su ida y retorno, pérdidas de equipos y su FCU terminal.</p><div class="table"><table><thead><tr><th>Tramo</th><th>Dirección</th><th>Longitud</th><th>Sirve a</th><th></th></tr></thead><tbody>'+l.secciones.map((s:any,i:number)=>'<tr><td>'+esc(s.id)+'</td><td>'+esc(s.direccion||'—')+'</td><td>'+fmt(s.L_recta_ft==null?null:s.L_recta_ft*.3048)+' m</td><td>'+esc(s.espacios_servidos?.length?s.espacios_servidos.map((id:string)=>loads?.espacios.find((e:any)=>e.id===id)?.nombre||id).join(', '):'Todos')+'</td><td>'+btn('Editar','data-edit-section="'+i+'"')+' '+btn('×','aria-label="Eliminar tramo" data-delete-section="'+i+'"')+'</td></tr>').join('')+'</tbody></table></div><h3>Circuitos completos</h3>'+l.circuitos.map((r:any,i:number)=>'<div class="source" style="margin:14px 0"><b>'+esc(r.id)+'</b><p class="subtle">'+esc(r.secciones.join(' → '))+' · '+esc(loads?.espacios.find((e:any)=>e.id===r.espacio_id)?.nombre||r.espacio_id)+'</p><div class="actions">'+btn('Editar pérdidas y ruta','data-edit-circuit="'+i+'"')+btn('Eliminar','data-delete-circuit="'+i+'"')+'</div></div>').join('')+(!l.secciones.length?'<p class="empty">No hay tramos cargados. Creá el trazado o importá una configuración.</p>':'');}
function tank(){const t=config.tanque;return '<h2>Tanque de expansión</h2><p class="warn">Pa y Pf son coeficientes adimensionales, no presiones en bar o psi. Su definición documental sigue pendiente de verificación. Ingresá coeficientes documentados por el fabricante.</p><div class="grid">'+field('Agua contenida en equipos','t.volumen_equipos_gal',t.volumen_equipos_gal,'L',1/3.785411784)+field('Expansión volumétrica neta E','t.E',t.E,'%',.01)+field('Coeficiente Pa','t.P_a',t.P_a)+field('Coeficiente Pf','t.P_f',t.P_f)+'</div>'+tfield('Fuente de coeficientes y volumen de equipos','t.fuente',t.fuente)+'<p class="subtle">El volumen de tuberías se calcula con el trazado y diámetros seleccionados. Incluí en el volumen de equipos baterías, chiller, caldera y accesorios.</p>';}
function loadTable(){return loads?'<div class="source"><b>'+esc(source?.name||loads.proyecto.nombre)+'</b><p class="subtle">Versión de origen: '+esc(source?.record.date?new Date(source.record.date).toLocaleString('es-AR'):loads.fecha)+' · '+loads.espacios.length+' ambientes</p></div><div class="table"><table><thead><tr><th>Ambiente</th><th>Total frío</th><th>Sensible</th><th>Calor</th></tr></thead><tbody>'+loads.espacios.map((e:any)=>'<tr><td>'+esc(e.nombre)+'<small>'+fmt(e.procedencia.condiciones_aire?.verano.temperatura_C,1)+' °C · '+fmt(e.procedencia.condiciones_aire?.verano.rh_pct,0)+'% HR</small></td><td>'+fmt(e.verano.total/1000)+' kW</td><td>'+fmt(e.verano.sensible/1000)+' kW</td><td>'+fmt(e.invierno.total/1000)+' kW</td></tr>').join('')+'</tbody></table></div><p class="subtle">Ambas estaciones se resuelven con el mismo motor Quadri y las entradas completas de esta versión. El cálculo de agua conserva el vínculo y las trazas térmicas.</p>':'<p class="empty">Guardá primero un balance térmico con ambientes y sus entradas. Después elegilo a la izquierda. No se usan los proyectos de demostración como cargas reales.</p>';}
function results(){const r=result?.resultado||{},flow=r.caudales_por_zona,pump=r.bomba,t=r.tanque_de_expansion;const metric=(l:string,v:string,key:string)=>'<div class="metric"><small>'+l+'</small><strong>'+v+'</strong>'+btn('Cómo se calculó','data-trace="'+key+'"')+'</div>';return '<section class="panel"><h2>Resultados en vivo</h2><span class="badge '+(result?.apto?'ok':'bloqueado')+'">'+(result?.apto?'Pipeline completo · revisar ingeniería':'Preliminar · completar datos')+'</span>'+metric('Planta · refrigeración',fmt(r.cargas_del_sistema?.Q_refrig_ton)+' TR','cargas_del_sistema')+metric('Caudal térmico · frío',fmt(flow?.gpm_total_sin_div==null?null:flow.gpm_total_sin_div*GP)+' m³/h','caudales_por_zona')+metric('Bomba · frío',fmt(pump?.frio?.Q_gpm==null?null:pump.frio.Q_gpm*GP)+' m³/h · '+fmt(pump?.frio?.H_ft==null?null:pump.frio.H_ft*.3048)+' m.c.a.','bomba')+metric('Bomba · calor',fmt(pump?.calef?.Q_gpm==null?null:pump.calef.Q_gpm*GP)+' m³/h · '+fmt(pump?.calef?.H_ft==null?null:pump.calef.H_ft*.3048)+' m.c.a.','bomba')+metric('Tanque requerido',fmt(t?.V_tanque_gal==null?null:t.V_tanque_gal*3.785411784)+' L','tanque_de_expansion')+'</section><section class="panel"><h3>Validaciones</h3>'+(error?'<p class="warn error-box">'+esc(error)+'</p>':'')+(result?.diagnostico.errores||[]).map((x:string)=>'<p class="warn error-box">'+esc(x)+'</p>').join('')+(result?.diagnostico.warnings||[]).map((x:string)=>'<p class="warn">'+esc(x)+'</p>').join('')+(!result?'<p class="subtle">Elegí un balance y completá los datos del sistema.</p>':'')+'</section>';}
function detailResults(){const r=result?.resultado||{};return '<h2>Resultados por ambiente y tramo</h2>'+(!result?'<p class="empty">No hay cálculo todavía.</p>':'')+'<div class="table"><table><thead><tr><th>Ambiente</th><th>FCU</th><th>Frío térmico</th><th>Calor térmico</th></tr></thead><tbody>'+(loads?.espacios||[]).map((e:any)=>'<tr><td>'+esc(e.nombre)+'</td><td>'+esc(r.seleccion_fcu?.selecciones?.[e.id]?.codigo||'Pendiente')+'</td><td>'+fmt(r.caudales_por_zona?.gpm_por_zona?.[e.id]==null?null:r.caudales_por_zona.gpm_por_zona[e.id]*GP)+' m³/h</td><td>'+fmt(r.caudales_por_zona?.gpm_calef_por_zona?.[e.id]==null?null:r.caudales_por_zona.gpm_calef_por_zona[e.id]*GP)+' m³/h</td></tr>').join('')+'</tbody></table></div><div class="table"><table><thead><tr><th>Tramo</th><th>NPS</th><th>Caudal</th><th>Velocidad</th><th>Pérdida</th><th>Soportes</th></tr></thead><tbody>'+(r.dimensionamiento?.secciones||[]).map((s:any)=>'<tr><td>'+esc(s.id)+'</td><td>'+esc(s.nps)+'″</td><td>'+fmt(s.gpm_diseno*GP)+' m³/h</td><td>'+fmt(s.v_fps*.3048)+' m/s</td><td>'+fmt(s.dh_ft*.3048)+' m.c.a.</td><td>'+esc(r.soportes?.soportes?.find((x:any)=>x.id===s.id)?.n_soportes??'—')+'</td></tr>').join('')+'</tbody></table></div><p class="subtle">El punto de bomba usa el circuito más desfavorable, sin sumar ramas paralelas ni factor de seguridad. Selección comercial de bomba requiere curva del fabricante.</p>'+btn('Descargar resultado JSON','data-export-result')+' '+btn('Informe / PDF','data-print');}
function render(){
 const all=sources(),preferred=all.filter(b=>b.record.building.projectId===projectId),others=all.filter(b=>b.record.building.projectId!==projectId),stages=result?.pasos||WATER_STEPS.map((key,i)=>({clave:key,nombre:WATER_LABELS[i],paso:i+1,estado:'bloqueado'}));
 app.innerHTML='<header><div><h1>Agua · dos caños</h1><p>'+esc(loads?.proyecto.nombre||'Sistema de agua enfriada / caliente')+' · Carrier Parts 3 & 12</p></div><div class="actions">'+btn('← Cálculos','data-back')+btn('Guardar versión','data-save',true)+'</div></header><div class="layout"><aside class="source-panel"><section class="panel"><h2>Punto de partida</h2><label>Balance térmico guardado<select data-source><option value="">Elegí un balance…</option>'+[...preferred,...others].map(b=>'<option value="'+esc(b.id)+'" '+(b.id===sourceId?'selected':'')+'>'+esc(b.name)+'</option>').join('')+'</select></label><label>Base de cargas<select data-base>'+opts([['local','Local · aire exterior aparte'],['equipo','Equipo · incluye aire exterior']],base)+'</select></label><p class="subtle">La base define dónde se trata el aire exterior para evitar contarlo dos veces.</p>'+btn('Ver balance de origen','data-open-source '+(!sourceId?'disabled':''))+(savedId?'<p class="subtle">Versión guardada · '+esc(savedId.slice(0,8))+'</p>':'')+'</section><section class="panel"><h3>Proceso de cálculo</h3><ol class="stages">'+stages.map((s:any)=>'<li>'+btn('<b>'+String(s.paso).padStart(2,'0')+'</b>'+esc(s.nombre),'data-trace="'+s.clave+'"')+'<span class="badge '+s.estado+'">'+(s.estado==='ok'?'Calculado':s.estado==='error'?'Revisar':'Pendiente')+'</span></li>').join('')+'</ol></section></aside><div class="center"><nav class="tabs" role="tablist">'+['Cargas','Diseño','Fan-coils','Red','Tanque','Resultados'].map(t=>btn(t,'role="tab" aria-selected="'+(tab===t)+'" data-tab="'+t+'"')).join('')+'</nav><section class="panel">'+(tab==='Cargas'?loadTable():tab==='Diseño'?design():tab==='Fan-coils'?fcu():tab==='Red'?network():tab==='Tanque'?tank():detailResults())+'</section></div><aside class="results sticky">'+results()+'</aside></div><footer>Motor de agua web · nueve pasos · configuración y trazas conservadas con cada versión. '+esc((window as any).TBCloud?.status()||'Borrador local')+'</footer>';
 bind();
}
function modal(title:string,html:string){dialog.innerHTML='<header><h2>'+esc(title)+'</h2>'+btn('×','data-close aria-label="Cerrar"')+'</header>'+html;dialog.querySelector('[data-close]')!.addEventListener('click',()=>dialog.close());if(!dialog.open)dialog.showModal();}
function assignment(label:string,rows:any[],current:string[],name:string){return '<fieldset class="wide"><legend>'+esc(label)+'</legend>'+rows.map(([id,title])=>'<label class="check"><input type="checkbox" name="'+name+'" value="'+esc(id)+'" '+(current.includes(id)?'checked':'')+'>'+esc(title)+'</label>').join('')+'</fieldset>';}
function edit(kind:string,index=-1){
 const rows=kind==='fcu'?config.catalogo_fcu:kind==='section'?config.layout.secciones:config.layout.circuitos,old=rows[index],v=clone(old||{}),c=config.condiciones_diseno,air=loads?.espacios[0]?.procedencia.condiciones_aire;
 let html='';
 if(kind==='fcu'){v.condiciones??={};html=tfield('Código / modelo','codigo',v.codigo)+tfield('Fuente de catálogo','fuente',v.fuente)+field('Capacidad total frío','Q_tot_nom_btuh',v.Q_tot_nom_btuh,'kW',KW)+field('Capacidad sensible frío','Q_sens_nom_btuh',v.Q_sens_nom_btuh,'kW',KW)+field('Capacidad calefacción','Q_calef_nom_btuh',v.Q_calef_nom_btuh,'kW',KW)+field('Caudal de aire nominal','CFM_nom',v.CFM_nom,'m³/h',1/1.69901079552)+field('Caudal agua nominal · frío','GPM_nom',v.GPM_nom,'m³/h',1/GP)+field('Caudal agua nominal · calor','GPM_calef_nom',v.GPM_calef_nom,'m³/h',1/GP)+field('Circuitos batería','N_circuitos',v.N_circuitos)+field('Diámetro exterior tubo batería','OD_tubo_in',v.OD_tubo_in,'pulgadas')+field('Caudal mínimo por circuito · opcional','gpm_min_circuito',v.gpm_min_circuito,'m³/h',1/GP)+field('Pérdida batería · frío','dP_agua_psi',v.dP_agua_psi,'m.c.a.',1/(2.31*.3048))+field('Pérdida batería · calor','dP_calef_psi',v.dP_calef_psi,'m.c.a.',1/(2.31*.3048))+field('Agua fría de la ficha','k.T_agua_frio_F',v.condiciones.T_agua_frio_F,'°C',1.8,32)+field('Agua caliente de la ficha','k.T_agua_caliente_F',v.condiciones.T_agua_caliente_F,'°C',1.8,32)+field('Aire interior verano · BS','k.T_interior_verano_F',v.condiciones.T_interior_verano_F,'°C',1.8,32)+field('Aire interior verano · BH','k.T_bh_interior_verano_F',v.condiciones.T_bh_interior_verano_F,'°C',1.8,32)+field('Aire interior invierno','k.T_interior_invierno_F',v.condiciones.T_interior_invierno_F,'°C',1.8,32)+tfield('Fuente de condiciones / selección','k.fuente_psicrometrica',v.condiciones.fuente_psicrometrica)+'<label class="check wide"><input data-verified type="checkbox" '+(v.condiciones_verificadas?'checked':'')+'> Verifiqué capacidades y caudales de la ficha a estas condiciones</label><p class="subtle wide">Balance: verano '+fmt(air?.verano.temperatura_C,1)+' °C BS / '+fmt(air?.verano.bulbo_humedo_C,1)+' °C BH; invierno '+fmt(air?.invierno.temperatura_C,1)+' °C. Agua: '+fmt(fToC(c.T_agua_frio_F),1)+' / '+fmt(fToC(c.T_agua_caliente_F),1)+' °C. No se corrigen prestaciones fuera de la ficha.</p>';}
 if(kind==='section'){html=tfield('Nombre / ID','id',v.id)+'<label>Dirección<select data-select="direccion">'+opts([['ida','Ida'],['retorno','Retorno']],v.direccion||'ida')+'</select></label>'+field('Longitud recta','L_recta_ft',v.L_recta_ft,'m',1/.3048)+'<label>Servicio<select data-select="tipo">'+opts([['general','Distribución general'],['header','Colector'],['riser','Montante'],['pump_discharge','Impulsión de bomba'],['pump_suction','Aspiración de bomba']],v.tipo||'general')+'</select></label>'+tfield('Diámetro NPS · auto para seleccionar','nps',v.nps||'auto')+field('Codos 90° R/D 1,5','f.ell90_RD1.5',v.fittings?.['ell90_RD1.5']??0)+field('Tees paso directo','f.tee_thru',v.fittings?.tee_thru??0)+field('Tees derivación','f.tee_branch',v.fittings?.tee_branch??0)+assignment('Ambientes servidos · vacío = todos',(loads?.espacios||[]).map((e:any)=>[e.id,e.nombre]),v.espacios_servidos||[],'served');}
 if(kind==='circuit'){html=tfield('Nombre / ID','id',v.id)+'<label>Ambiente terminal<select data-select="espacio_id">'+opts((loads?.espacios||[]).map((e:any)=>[e.id,e.nombre]),v.espacio_id||loads?.espacios[0]?.id)+'</select></label>'+field('Pérdidas equipos y válvulas · frío (sin FCU)','perdidas_equipo_ft',v.perdidas_equipo_ft,'m.c.a.',1/.3048)+field('Pérdidas equipos y válvulas · calor (sin FCU)','perdidas_equipo_calef_ft',v.perdidas_equipo_calef_ft,'m.c.a.',1/.3048)+tfield('Fuente de pérdidas','fuente_perdidas',v.fuente_perdidas)+assignment('Ruta completa ida + retorno',config.layout.secciones.map((s:any)=>[s.id,s.id+' · '+s.direccion]),v.secciones||[],'route');}
 modal(kind==='fcu'?'Ficha de fan-coil':kind==='section'?'Tramo de tubería':'Circuito de bomba','<form id="editForm"><div class="grid">'+html+'</div><div class="actions">'+btn('Guardar datos','data-commit',true)+'</div></form>');
 dialog.querySelector('[data-commit]')!.addEventListener('click',()=>{try{dialog.querySelectorAll('[data-field]').forEach(el=>{const a=el as HTMLInputElement;set(v,a.dataset.field!,a.value===''?null:Number(a.value)*Number(a.dataset.factor)+Number(a.dataset.offset));});dialog.querySelectorAll('[data-text]').forEach(el=>set(v,(el as HTMLElement).dataset.text!,(el as HTMLInputElement).value.trim()));dialog.querySelectorAll('[data-select]').forEach(el=>v[(el as HTMLElement).dataset.select!]=(el as HTMLSelectElement).value);
  if(kind==='fcu'){v.condiciones_verificadas=(dialog.querySelector('[data-verified]') as HTMLInputElement).checked;v.dP_aire_inH2O??=0;}
  if(kind==='section'){v.espacios_servidos=[...dialog.querySelectorAll('[name=served]:checked')].map(el=>(el as HTMLInputElement).value);v.exposiciones_servidas=[];v.gpm_diseno=0;}
  if(kind==='circuit')v.secciones=[...dialog.querySelectorAll('[name=route]:checked')].map(el=>(el as HTMLInputElement).value);
  if(!String(kind==='fcu'?v.codigo:v.id||'').trim())throw Error('Ingresá un nombre.');if(rows.some((x:any,i:number)=>i!==index&&(kind==='fcu'?x.codigo===v.codigo:x.id===v.id)))throw Error('Ese identificador ya existe.');
  if(kind==='section'&&old?.id!==v.id)config.layout.circuitos.forEach((r:any)=>r.secciones=r.secciones.map((id:string)=>id===old?.id?v.id:id));if(index<0)rows.push(v);else rows[index]=v;dialog.close();changed();}catch(e){notify((e as Error).message);}});
 (dialog.querySelector('form') as HTMLFormElement).onsubmit=e=>e.preventDefault();
}
function set(obj:any,key:string,value:any){const k=key.startsWith('c.')?obj.condiciones_diseno:key.startsWith('t.')?obj.tanque:key.startsWith('k.')?(obj.condiciones??={}):key.startsWith('f.')?(obj.fittings??={}):obj;const name=/^[ctkf]\./.test(key)?key.slice(2):key;k[name]=value;}
function bind(){
 app.querySelector('[data-source]')!.addEventListener('change',e=>{try{const id=(e.target as HTMLSelectElement).value;if(!id){loads=null;sourceId='';source=null;result=null;render();return;}importSource(id);savedId='';storeDraft();render();}catch(e){notify((e as Error).message);}});
 app.querySelector('[data-base]')!.addEventListener('change',e=>{base=(e.target as HTMLSelectElement).value as any;if(sourceId)try{importSource(sourceId);storeDraft();render();}catch(e){notify((e as Error).message);}});
 app.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>{tab=(el as HTMLElement).dataset.tab!;render();}));
 app.querySelectorAll('[data-field],[data-text]').forEach(el=>el.addEventListener('change',()=>{const x=el as HTMLInputElement;if(x.dataset.field)set(config,x.dataset.field,x.value===''?null:Number(x.value)*Number(x.dataset.factor)+Number(x.dataset.offset));else set(config,x.dataset.text!,x.value.trim());changed();}));
 const on=(selector:string,fn:(el:HTMLElement)=>void)=>app.querySelectorAll(selector).forEach(el=>el.addEventListener('click',()=>{try{fn(el as HTMLElement);}catch(e){notify((e as Error).message);}}));
 on('[data-save]',persist);on('[data-back]',()=>parent===window?location.assign('../tracker.html?view=balances'):parent.postMessage({type:'thermabot:navigate',view:'balances'},location.origin));
 on('[data-open-source]',()=>parent===window?location.assign('../tracker.html?view=calculator&balanceId='+encodeURIComponent(sourceId)+'&projectId='+encodeURIComponent(projectId)):parent.postMessage({type:'thermabot:open-balance',balanceId:sourceId,projectId},location.origin));
 on('[data-trace]',el=>{const k=el.dataset.trace!,s=result?.resultado[k];modal(WATER_LABELS[WATER_STEPS.indexOf(k)],'<p class="subtle">'+esc(s?.error||s?.trace?.ecuacion||'Pendiente de datos y dependencias.')+'</p><pre>'+esc(JSON.stringify(s||{},null,2))+'</pre>');});
 for(const kind of ['fcu','section','circuit']){on('[data-add-'+kind+']',()=>edit(kind));on('[data-edit-'+kind+']',el=>edit(kind,Number((el as any).dataset['edit'+kind[0].toUpperCase()+kind.slice(1)])));on('[data-delete-'+kind+']',el=>{const i=Number((el as any).dataset['delete'+kind[0].toUpperCase()+kind.slice(1)]),rows=kind==='fcu'?config.catalogo_fcu:kind==='section'?config.layout.secciones:config.layout.circuitos;if(!confirm('¿Eliminar '+(rows[i].codigo||rows[i].id)+'?'))return;rows.splice(i,1);changed();});}
 on('[data-room-network]',()=>{if(!loads)throw Error('Elegí un balance primero.');if(config.layout.secciones.length&&!confirm('¿Reemplazar el trazado actual por ramas de ida y retorno por ambiente?'))return;const rows:any[]=[],paths:any[]=[];loads.espacios.forEach((e:any,i:number)=>{const ids=['ida-'+(i+1),'retorno-'+(i+1)];ids.forEach((id,j)=>rows.push({id,nps:'auto',L_recta_ft:null,direccion:j?'retorno':'ida',tipo:'general',fittings:{},espacios_servidos:[e.id],exposiciones_servidas:[],gpm_diseno:0}));paths.push({id:'circuito-'+(i+1),espacio_id:e.id,secciones:ids,perdidas_equipo_ft:null,perdidas_equipo_calef_ft:null,fuente_perdidas:''});});config.layout.secciones=rows;config.layout.circuitos=paths;changed();notify('Ramas creadas. Completá longitudes y pérdidas reales.');});
 for(const [selector,update]of [['[data-material]',(v:string)=>config.material=v],['[data-diversity]',(v:string)=>config.layout.diversidad=v],['[data-layout]',(v:string)=>config.layout.tipo=v],['[data-order]',(v:string)=>config.layout.orden_exposiciones=v.split(',').map(x=>x.trim()).filter(Boolean)]] as any)app.querySelector(selector)?.addEventListener('change',(e:any)=>{update(e.target.value);changed();});
 app.querySelectorAll('[data-exposure]').forEach(el=>el.addEventListener('change',()=>{config.exposiciones[(el as HTMLElement).dataset.exposure!]=(el as HTMLInputElement).value.trim();changed();}));
 on('[data-import-config]',()=>jsonImport(data=>{const value=data.configuracion_agua||data;if(value.espacios||!value.condiciones_diseno||!value.layout||!Array.isArray(value.catalogo_fcu)||!value.tanque)throw Error('Configuración hidráulica incompatible; no importar cargas duplicadas.');config=clone(value);changed();}));
 on('[data-export-config]',()=>download('THERMABOT-configuracion-agua.json',config));on('[data-import-fcu]',()=>jsonImport(data=>{if(!Array.isArray(data))throw Error('El catálogo debe ser una lista JSON de modelos.');config.catalogo_fcu=clone(data);changed();}));
 on('[data-export-result]',()=>{if(!result)throw Error('No hay cálculo disponible.');download('THERMABOT-resultado-agua.json',result);});on('[data-print]',()=>{tab='Resultados';render();window.print();});
}
try{
 const store=read(KEY,{}),record=store.waterCalculations?.find((r:any)=>r.id===savedId),draft=store.waterDrafts?.[projectId];
 if(record){validateImportedData(record);config=clone(record.config);base=record.base;sourceId=record.sourceId;projectId=record.projectId;loads=clone(record.loads);source=sources().find(s=>s.id===sourceId);recalc();}
 else if(draft){validateImportedData(draft);config=clone(draft.config);base=draft.base;if(draft.sourceId)importSource(draft.sourceId);}
 else if(params.get('balanceId'))importSource(params.get('balanceId')!);
}catch(e){error=(e as Error).message;}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;try{if(e.data?.type==='thermabot:save'){if(e.data.projectId&&e.data.projectId!==projectId)throw Error('El cálculo de agua permanece vinculado al proyecto de su balance. Elegí un balance del proyecto destino.');persist();}if(e.data?.type==='thermabot:print'){tab='Resultados';render();window.print();}if(e.data?.type==='thermabot:theme')document.body.dataset.theme=e.data.theme==='light'?'light':'dark';}catch(e){notify((e as Error).message);}});
render();parent.postMessage({type:'thermabot:ready',balanceId:null},location.origin);
