// Browser implementation of carrier_water.py v1.1. Cross-checked against the Python CLI.
// Thermal loads come from the existing balance engine: no thermal equations here.
import {STEEL_SCH40,V_RECOMENDADA_FPS,EROSION_TABLA,TABLE_11_LEQ,EXAMPLE_LEQ,SUPPORT_SPACING_STEEL,CHART_6,GPM_MIN_TURBULENTO} from './tables.ts';
import {WATER_STEPS,WATER_LABELS} from '../quadri/src/engine/integracion_agua.ts';
import {validateImportedData} from '../quadri/src/engine/seguridad_datos.ts';
const copy=(v:any)=>JSON.parse(JSON.stringify(v)),sum=(v:number[])=>v.reduce((a,b)=>a+b,0);
const fail=(s:string):never=>{throw Error(s);};
const num=(v:any,p:string,positive=false)=>typeof v==='number'&&Number.isFinite(v)&&(positive?v>0:v>=0)?v:fail(p+': ingresá un número '+(positive?'positivo':'no negativo')+'.');
const text=(v:any,p:string)=>typeof v==='string'&&v.trim()&&!/[\x00-\x1f]/.test(v)?v.trim():fail('Falta '+p+'.');
const integer=(v:any,p:string,min=0)=>Number.isInteger(num(v,p))&&v>=min?v:fail(p+': entero inválido.');
const unique=(a:any[],p:string)=>Array.isArray(a)&&new Set(a).size===a.length?a:fail(p+': lista ausente o repetida.');
const close=(a:number,b:number)=>Math.abs(a-b)<=1e-8*Math.max(Math.abs(a),Math.abs(b));
const trace=(ecuacion:string,variables:any,resultado:any,unidad:string,fuente:string)=>({ecuacion,variables,resultado,unidad,fuente});
function finiteTree(v:any){if(typeof v==='number'&&!Number.isFinite(v))fail('NaN / Infinity no permitido.');if(v&&typeof v==='object')for(const x of Object.values(v))finiteTree(x);}
function interp(x:number,rows:number[][]){num(x,'Interpolación');if(x<rows[0][0]||x>rows.at(-1)![0])fail('Valor fuera del dominio tabulado.');for(let i=1;i<rows.length;i++){const [a,b]=rows[i-1],[c,d]=rows[i];if(x<=c)return b+(d-b)*(x-a)/(c-a);}return rows.at(-1)![1];}
const velocity=(g:number,d:number)=>g*231/60/(Math.PI*d*d/4)/12;
const power=(v:any,u:string)=>{const f=({'W':3.412141633127942,'kW':3412.141633127942,'kcal/h':3.968320719327,'BTU/h':1} as any)[u];return f?num(v,'Carga')*f:fail('Unidad de potencia inválida: '+u);};
export function adaptWaterBalance(balance:any,config:any){
 validateImportedData(balance);validateImportedData(config);finiteTree(balance);finiteTree(config);
 if(balance.schema!=='thermabot.water-loads.v1'||!['local','equipo'].includes(balance.base_carga))fail('Contrato de cargas incompatible.');
 if(config.espacios)fail('No duplicar las cargas en la configuración de agua.');
 const s=copy(config),ex=s.exposiciones||{};delete s.exposiciones;
 s.proyecto=copy(balance.proyecto);s.espacios=balance.espacios.map((r:any)=>{
  text(r.procedencia?.motor,'motor térmico');if(!r.procedencia?.trace_ids?.length)fail('Falta trazabilidad térmica.');
  return {id:r.id,nombre:r.nombre,exposicion:ex[r.id]||'SIN_ASIGNAR',Q_total_btuh:power(r.verano.total,r.verano.unidad),Q_sensible_btuh:power(r.verano.sensible,r.verano.unidad),Q_calef_btuh:power(r.invierno.total,r.invierno.unidad),perfil_frio:(r.verano.perfil||[]).map((h:any)=>({hour:h.hora,total_btuh:power(h.total,r.verano.unidad),sensible_btuh:power(h.sensible,r.verano.unidad)})),procedencia:r.procedencia};
 });
 if(Object.keys(ex).some(id=>!s.espacios.some((r:any)=>r.id===id)))fail('Exposición de un ambiente inexistente.');
 if(s.layout?.diversidad==='chart6'&&s.espacios.some((r:any)=>!ex[r.id]))fail('Chart 6 requiere exposición por ambiente.');
 s.procedencia={balance_schema:balance.schema,base_carga:balance.base_carga,proyecto_id:s.proyecto.id,motor:balance.motor,fecha:balance.fecha,revision:balance.revision,firma_entradas:balance.firma_entradas};return s;
}
function catalog(s:any){
 if(Object.keys(s.tuberias||{}).length){for(const p of Object.values(s.tuberias) as any[]){num(p.id_in,'ID',true);if(p.od_in!=null&&p.id_in>=num(p.od_in,'OD',true))fail('ID debe ser menor a OD.');num(p.wt_agua_lb_ft,'Peso agua',true);num(p.spacing_ft,'Separación',true);text(p.fuente,'fuente de tubería');}return s.tuberias;}
 if(s.material==='copper')fail('Cobre requiere catálogo de ID, OD, soportes y fittings verificados.');
 return Object.fromEntries(Object.entries(STEEL_SCH40).map(([id,row])=>[id,{id_in:row[0],wt_agua_lb_ft:row[1],spacing_ft:(SUPPORT_SPACING_STEEL as any)[id],fuente:'[P3-pág.4/8] · transcripción suministrada'}]));
}
function validate(s:any){
 validateImportedData(s);text(s.proyecto?.nombre,'nombre del proyecto');if(!s.espacios?.length)fail('No hay ambientes.');if(!['steel','copper'].includes(s.material))fail('Material no soportado.');catalog(s);
 const c=s.condiciones_diseno;for(const k of ['T_OA_verano_F','T_OA_invierno_F','T_interior_verano_F','T_interior_invierno_F','T_agua_frio_F','T_agua_caliente_F'])if(typeof c[k]!=='number'||!Number.isFinite(c[k])||c[k]<=-459.67)fail(k+': temperatura inválida.');
 if(c.fluido!=='water')fail('Factor 500 solo para agua; glicol no soportado.');num(c.delta_T_agua_F,'ΔT frío',true);if(c.delta_T_calef_F!=null)num(c.delta_T_calef_F,'ΔT calor',true);
 interp(integer(c.horas_operacion_anual,'Horas de operación',1),EROSION_TABLA);num(c.friction_rate_diseno,'Fricción máxima',true);for(const k of ['T_agua_frio_F','T_agua_caliente_F'])if(c[k]<=32||c[k]>=212)fail('Agua líquida 32…212 °F requerida.');
 unique(s.espacios.map((e:any)=>e.id),'Ambientes');
 for(const e of s.espacios){text(e.id,'ID ambiente');text(e.exposicion,'exposición');for(const k of ['Q_total_btuh','Q_sensible_btuh','Q_calef_btuh'])num(e[k],e.id+'.'+k);if(e.Q_sensible_btuh>e.Q_total_btuh+1e-8)fail(e.id+': sensible > total.');
  const p=e.perfil_frio;unique(p.map((h:any)=>h.hour),'Horas');for(const h of p){if(integer(h.hour,'Hora')>23)fail('Hora fuera de rango.');num(h.total_btuh,'Total horario');if(num(h.sensible_btuh,'Sensible horario')>h.total_btuh+1e-8)fail('Sensible horario > total.');}
  if(p.length&&(!close(Math.max(...p.map((h:any)=>h.total_btuh)),e.Q_total_btuh)||!close(Math.max(...p.map((h:any)=>h.sensible_btuh)),e.Q_sensible_btuh)))fail('Perfil y máximos no coinciden.');
  for(const a of Object.values(e.procedencia?.condiciones_aire||{}) as any[]){if(a.rh_pct!=null&&num(a.rh_pct,'RH')>100)fail('RH fuera de rango.');for(const k of ['temperatura_C','bulbo_humedo_C'])if(a[k]!=null&&(typeof a[k]!=='number'||!Number.isFinite(a[k])||a[k]<=-273.15))fail('Estado del aire inválido.');}
 }
}
// The browser permits partial work: missing catalog/network inputs block their own
// stage, while loads and water flows remain inspectable. CLI retains strict entry checks.
function validateNetwork(s:any){
 const l=s.layout;if(!['direct_return','reverse_return'].includes(l.tipo)||!['chart6','coincidente','sin_diversidad'].includes(l.diversidad))fail('Configuración de red inválida.');
 if(!l.secciones?.length)fail('Falta trazado de tuberías.');unique(l.secciones.map((r:any)=>r.id),'Tramos');
 for(const r of l.secciones){text(r.id,'ID tramo');num(r.L_recta_ft,'Longitud '+r.id,true);num(r.gpm_diseno??0,'Override caudal');if(!(V_RECOMENDADA_FPS as any)[r.tipo])fail('Tipo de tramo no tabulado.');if(r.espacios_servidos?.length&&r.exposiciones_servidas?.length)fail('Asigná ambientes o exposiciones, no ambos.');
  for(const id of unique(r.espacios_servidos||[],'Ambientes servidos'))if(!s.espacios.some((e:any)=>e.id===id))fail('Ambiente servido inexistente.');for(const x of unique(r.exposiciones_servidas||[],'Exposiciones servidas'))if(!s.espacios.some((e:any)=>e.exposicion===x))fail('Exposición inexistente.');for(const [k,v]of Object.entries(r.fittings||{})){text(k,'fitting');integer(v,'Cantidad fittings');}
 }
}
function validateFCU(s:any){
 unique(s.catalogo_fcu.map((m:any)=>m.codigo),'Modelos');for(const m of s.catalogo_fcu){text(m.codigo,'modelo');for(const k of ['Q_tot_nom_btuh','Q_sens_nom_btuh','CFM_nom','GPM_nom','OD_tubo_in'])num(m[k],m.codigo+'.'+k,true);if(m.Q_sens_nom_btuh>m.Q_tot_nom_btuh)fail('FCU sensible > total.');integer(m.N_circuitos,'Circuitos FCU',1);num(m.dP_agua_psi??0,'ΔP FCU');num(m.dP_aire_inH2O??0,'ΔP aire');for(const k of ['Q_calef_nom_btuh','GPM_calef_nom','gpm_min_circuito'])if(m[k]!=null)num(m[k],k,true);if(m.dP_calef_psi!=null)num(m.dP_calef_psi,'ΔP calor');if(typeof m.condiciones_verificadas!=='boolean'||!m.condiciones||typeof m.condiciones!=='object')fail('Condiciones FCU inválidas.');}
}
const served=(s:any,r:any)=>s.espacios.filter((e:any)=>r.espacios_servidos?.length?r.espacios_servidos.includes(e.id):r.exposiciones_servidas?.length?r.exposiciones_servidas.includes(e.exposicion):true);
function profilePeak(es:any[],factor=1){if(!es.length)fail('Tramo sin ambientes.');const domain=es[0].perfil_frio.map((h:any)=>h.hour).sort((a:number,b:number)=>a-b);if(!domain.length||es.some(e=>JSON.stringify(e.perfil_frio.map((h:any)=>h.hour).sort((a:number,b:number)=>a-b))!==JSON.stringify(domain)))fail('Perfiles horarios incompletos/incompatibles.');const vals=domain.map((h:number)=>sum(es.map(e=>e.perfil_frio.find((r:any)=>r.hour===h).total_btuh))/factor);const peak=Math.max(...vals);return {peak,hour:domain[vals.indexOf(peak)]};}
function friction(s:any,r:any,g:number,d:number,season:string){
 if(!g)return {rate:0,Re:0,f:null,fuente:'Sin circulación en esta estación'};
 const c=s.condiciones_diseno,hot=season==='calef',rate=hot?r.friction_rate_calef_verificado:r.friction_rate_verificado,ref=hot?r.referencia_calef_gpm:r.referencia_gpm;
 if(rate!=null){num(rate,'Fricción verificada',true);text(r.fuente_friccion,'Fuente fricción');if(r.referencia_nps!==r.nps||ref==null||!close(g,ref))fail('Fricción manual no corresponde a NPS/GPM.');return {rate,Re:null,f:null,fuente:r.fuente_friccion};}
 const nu=num(hot?c.viscosidad_calef_ft2_s:c.viscosidad_frio_ft2_s,'Viscosidad '+season,true),rough=num(c.rugosidad_ft,'Rugosidad');text(c.fuente_fluido,'fuente fluido/rugosidad');const D=d/12,v=velocity(g,d),Re=v*D/nu;
 if(Re>2000&&Re<4000)fail('Régimen transitorio: ingresá fricción verificada para NPS/GPM.');const f=Re<=2000?64/Re:.25/Math.log10(rough/(3.7*D)+5.74/Re**.9)**2;
 const value=f/D*v*v/(2*32.17)*100,source='Darcy–Weisbach · EPA EPANET 2.2 + propiedades ingresadas';return {rate:value,Re,f,fuente:source,trace:trace('h=f·L/D·v²/(2g)',{D_ft:D,nu,rough,v_fps:v},value,'ft/100 ft',source)};
}
export function calculateWater(balance:any,config:any){
 const s=adaptWaterBalance(balance,config),d={errores:[] as string[],warnings:[] as string[],notas:[] as string[]},r:any={},pasos:any[]=[];const warn=(m:string)=>d.warnings.push(m);
 let valid=true;try{validate(s);}catch(e){valid=false;d.errores.push('Entrada: '+(e as Error).message);}
 const c=s.condiciones_diseno,l=s.layout,functions=[
 ()=>{const es=s.espacios,total=sum(es.map((e:any)=>e.Q_total_btuh));if(s.catalogo_fcu.some((m:any)=>/DEMO|SINTÉTIC/i.test(m.fuente)))warn('DATOS SINTÉTICOS: prueba de software, no selección comercial.');if(s.procedencia.revision?.revisado===false)warn('Balance preliminar: entradas térmicas sin revisar.');let peak=total,hour=null;if(es.every((e:any)=>e.perfil_frio.length)){const p=profilePeak(es);peak=p.peak;hour=p.hour;}else if(es.some((e:any)=>e.perfil_frio.length))fail('Perfiles incompletos.');else warn('Sin perfiles: carga conservadora = suma de máximos.');if(peak<=0)fail('No hay carga de refrigeración positiva.');return {Q_bloque_btuh:peak,Q_refrig_btuh:1.05*peak,Q_refrig_ton:1.05*peak/12000,Q_calef_btuh:sum(es.map((e:any)=>e.Q_calef_btuh)),n_espacios:es.length,suma_maximos_btuh:total,hora_bloque:hour,trace:trace('Q_refrig=1.05·Q_bloque',{Q_bloque:peak},1.05*peak,'BTU/h','[P12-pág.6]')};},
 ()=>{const cold=c.delta_T_agua_F,hot=c.delta_T_calef_F??cold,cf:any={},hf:any={};if(c.delta_T_calef_F==null&&r.cargas_del_sistema.Q_calef_btuh)warn('ΔT caliente usa ΔT legado; confirmar.');for(const e of s.espacios){cf[e.id]=e.Q_total_btuh/(500*cold);hf[e.id]=e.Q_calef_btuh/(500*hot);}return {gpm_por_zona:cf,gpm_calef_por_zona:hf,gpm_total_sin_div:sum(Object.values(cf)),gpm_total_calef:sum(Object.values(hf)),delta_T_F:cold,delta_T_calef_F:hot,trace:trace('GPM=Q/(500·ΔT)',{cold,hot,cargas:s.espacios},{frio:cf,calef:hf},'gpm','[P12-pág.5]')};},
 ()=>{validateFCU(s);if(!s.catalogo_fcu.length)fail('Agregá un catálogo de fan-coils verificado.');const selected:any={},oper:any={},hot:any={},checks:any={},flow=r.caudales_por_zona;
  for(const e of s.espacios){const a=e.procedencia?.condiciones_aire||{},air=a.verano||{},winter=a.invierno||{},ti=air.temperatura_C!=null?air.temperatura_C*1.8+32:c.T_interior_verano_F,tw=winter.temperatura_C!=null?winter.temperatura_C*1.8+32:c.T_interior_invierno_F;if(!Object.keys(a).length)warn(e.id+': corroborar condiciones de aire con la ficha.');
   const m=[...s.catalogo_fcu].sort((a:any,b:any)=>a.Q_tot_nom_btuh-b.Q_tot_nom_btuh).find((m:any)=>{const k=m.condiciones,min=m.gpm_min_circuito??(GPM_MIN_TURBULENTO as any)[m.OD_tubo_in],match=(v:any,t:number)=>typeof v==='number'&&Math.abs(v-t)<=.1;return m.condiciones_verificadas&&m.fuente?.trim()&&k.fuente_psicrometrica&&close(k.T_agua_frio_F,c.T_agua_frio_F)&&match(k.T_interior_verano_F,ti)&&(air.bulbo_humedo_C==null||match(k.T_bh_interior_verano_F,air.bulbo_humedo_C*1.8+32))&&min!=null&&m.Q_tot_nom_btuh>=e.Q_total_btuh&&m.Q_sens_nom_btuh>=e.Q_sensible_btuh&&m.GPM_nom>=flow.gpm_por_zona[e.id]&&m.GPM_nom/m.N_circuitos>=min&&(!e.Q_calef_btuh||(m.Q_calef_nom_btuh>=e.Q_calef_btuh&&m.GPM_calef_nom>=flow.gpm_calef_por_zona[e.id]&&m.dP_calef_psi!=null&&m.GPM_calef_nom/m.N_circuitos>=min&&close(k.T_agua_caliente_F,c.T_agua_caliente_F)&&match(k.T_interior_invierno_F,tw)));});
   selected[e.id]=m||null;if(!m){d.errores.push(e.nombre+': ningún FCU cumple capacidades, caudal, turbulencia y condiciones.');continue;}oper[e.id]=m.GPM_nom;hot[e.id]=e.Q_calef_btuh?m.GPM_calef_nom:0;checks[e.id]={gpm_por_circuito:m.GPM_nom/m.N_circuitos,fuente:m.fuente,condiciones:m.condiciones};}
  return {selecciones:selected,sin_catalogo:false,gpm_operacion:oper,gpm_calef_operacion:hot,verificacion:checks,trace:trace('Qcat≥Q; GPMnom/N≥GPMmín',{cargas:s.espacios,catalogo:s.catalogo_fcu},checks,'BTU/h; gpm','[P12-pág.4/5]')};},
 ()=>{if(!['sin_diversidad','coincidente','chart6'].includes(l.diversidad))fail('Diversidad inválida.');unique(l.orden_exposiciones,'Orden de exposiciones');if(l.diversidad==='chart6'&&JSON.stringify([...new Set(s.espacios.map((e:any)=>e.exposicion))].sort())!==JSON.stringify([...l.orden_exposiciones].sort()))fail('El orden debe incluir todas las exposiciones.');const f=r.seleccion_fcu,cf={...r.caudales_por_zona.gpm_por_zona,...f.gpm_operacion},hf={...r.caudales_por_zona.gpm_calef_por_zona,...f.gpm_calef_operacion},total=sum(Object.values(cf)),factors=Object.fromEntries(s.espacios.map((e:any)=>[e.exposicion,1])),rows:any[]=[];let pump=total;
  if(l.diversidad==='coincidente'){if(s.espacios.some((e:any)=>!close(cf[e.id],r.caudales_por_zona.gpm_por_zona[e.id])))fail('Coincidencia exige ficha FCU a caudal térmico; no se reduce caudal nominal fijo.');pump=profilePeak(s.espacios,500*c.delta_T_agua_F).peak;}
  else if(l.diversidad==='chart6'&&l.orden_exposiciones.length>1){let acc=0;for(const [i,x]of l.orden_exposiciones.entries()){const g=sum(s.espacios.filter((e:any)=>e.exposicion===x).map((e:any)=>cf[e.id]));acc+=g;const factor=i===l.orden_exposiciones.length-1?1:interp(acc/total,CHART_6);factors[x]=factor;rows.push({idx:i,exposicion:x,gpm_max:g,gpm_acum:acc,ratio:acc/total,F_div:factor,'gpm_diseño':g*factor});}pump=sum(rows.map(x=>x['gpm_diseño']));}else d.notas.push('Sin reducción por diversidad: caudales completos.');
  const heat=sum(Object.values(hf));return {exposiciones:rows,gpm_bomba:Math.max(pump,heat),gpm_bomba_frio:pump,gpm_bomba_calef:heat,gpm_total_sin_div:total,reduccion_pct:100*(1-pump/total),factores:factors,gpm_zona_por_id:cf,gpm_calef_zona_por_id:hf,modo:l.diversidad,trace:trace('Σ GPM_exposición·F; Fúltima=1',{},rows,'gpm','[P3-pág.27/30]')};},
 ()=>{validateNetwork(s);const cat=catalog(s),div=r.diversidad,sections=l.secciones.map((x:any)=>{const sec=copy(x),es=served(s,sec);const cold=l.diversidad==='coincidente'?profilePeak(es,500*c.delta_T_agua_F).peak:sum(es.map((e:any)=>div.gpm_zona_por_id[e.id]*(es.length===1?1:div.factores[e.exposicion]))),hot=sum(es.map((e:any)=>div.gpm_calef_zona_por_id[e.id])),g=Math.max(cold,hot);
  if(sec.gpm_diseno&&!close(sec.gpm_diseno,g))fail(sec.id+': override no coincide con caudal de la red.');if(!g)fail(sec.id+': tramo sin caudal.');const candidates=sec.nps&&!['auto',''].includes(sec.nps)?[sec.nps]:Object.keys(cat).sort((a,b)=>cat[a].id_in-cat[b].id_in),limit=Math.min((V_RECOMENDADA_FPS as any)[sec.tipo][1],interp(c.horas_operacion_anual,EROSION_TABLA));let accepted=false,last='';
  for(const nps of candidates){if(!cat[nps])fail('Diámetro no disponible.');sec.nps=nps;const D=cat[nps].id_in;if(velocity(g,D)>limit){last='Velocidad supera criterio';continue;}let cf,hf;try{cf=friction(s,sec,cold,D,'frio');hf=friction(s,sec,hot,D,'calef');}catch(e){last=(e as Error).message;if(/transitorio/i.test(last))continue;throw e;}if(Math.max(cf.rate,hf.rate)>c.friction_rate_diseno){last='Fricción supera criterio';continue;}sec.friccion_frio=cf;sec.friccion_calef=hf;accepted=true;break;}
  if(!accepted)fail(sec.id+': ningún diámetro válido. '+last);const v=velocity(g,cat[sec.nps].id_in);if(v<(V_RECOMENDADA_FPS as any)[sec.tipo][0])warn(sec.id+': velocidad menor a recomendación Tabla 13.');let leq=sec.L_recta_ft;for(const [k,count]of Object.entries(sec.fittings||{}) as [string,number][]){if(!count)continue;const table=s.material==='copper'?cat[sec.nps].leq_fittings_ft:s.tabla_leq==='example'?(EXAMPLE_LEQ as any)[sec.nps]:s.tabla_leq==='table11'?(TABLE_11_LEQ as any)[sec.nps]:fail('Tabla fittings inválida');const value=table?.[k];if(value==null)fail('Falta Leq '+sec.nps+'/'+k);leq+=num(value,'Leq fitting',true)*count;}
  return {...sec,nps_sugerido:candidates.length>1?sec.nps:null,gpm_frio:cold,gpm_calef:hot,gpm_diseno:g,v_fps:v,L_eq_ft:leq,dh_frio_ft:leq*sec.friccion_frio.rate/100,dh_calef_ft:leq*sec.friccion_calef.rate/100,dh_ft:leq*Math.max(sec.friccion_frio.rate,sec.friccion_calef.rate)/100};});return {secciones:sections,trace:trace('Leq=L+Σ n·Leq_fitting; Δh=Leq·J/100',{},sections,'ft; gpm; fps','[P3-pág.19/23] + Darcy')};},
 ()=>{if(!l.circuitos?.length)fail('Definí circuitos completos de ida y retorno.');unique(l.circuitos.map((x:any)=>x.id),'Circuitos');const sec=Object.fromEntries(r.dimensionamiento.secciones.map((x:any)=>[x.id,x])),covered=new Set(),paths=l.circuitos.map((p:any)=>{text(p.id,'ID circuito');const ids=unique(p.secciones,'Tramos de circuito');if(!ids.length||ids.some((id:string)=>!sec[id]))fail('Circuito incompleto.');if(JSON.stringify([...new Set(ids.map((id:string)=>sec[id].direccion))].sort())!==JSON.stringify(['ida','retorno']))fail(p.id+': debe incluir ida y retorno.');ids.forEach((id:string)=>covered.add(id));const m=r.seleccion_fcu.selecciones[p.espacio_id];if(!m||ids.some((id:string)=>!served(s,sec[id]).some((e:any)=>e.id===p.espacio_id)))fail('Circuito no sirve al terminal.');const extra=num(p.perdidas_equipo_ft,'Pérdidas equipos frío'),exhot=num(p.perdidas_equipo_calef_ft,'Pérdidas equipos calor');text(p.fuente_perdidas,'fuente pérdidas equipos');const cold=sum(ids.map((id:string)=>sec[id].dh_frio_ft))+extra+(m.dP_agua_psi||0)*2.31,hot=s.espacios.find((e:any)=>e.id===p.espacio_id).Q_calef_btuh?sum(ids.map((id:string)=>sec[id].dh_calef_ft))+exhot+(m.dP_calef_psi||0)*2.31:0;return {id:p.id,espacio_id:p.espacio_id,H_frio_ft:cold,H_calef_ft:hot,secciones:ids};});
  if(covered.size!==Object.keys(sec).length||s.espacios.some((e:any)=>!paths.some((p:any)=>p.espacio_id===e.id)))fail('Hay tramos o ambientes sin circuito.');const cold=Math.max(...paths.map((p:any)=>p.H_frio_ft)),hot=Math.max(...paths.map((p:any)=>p.H_calef_ft)),H=Math.max(cold,hot);return {Q_gpm:r.diversidad.gpm_bomba,H_ft:H,H_psi:H/2.31,frio:{Q_gpm:r.diversidad.gpm_bomba_frio,H_ft:cold},calef:{Q_gpm:r.diversidad.gpm_bomba_calef,H_ft:hot},detalle:paths,nota:'Sin factor de seguridad. Selección comercial requiere curva.',trace:trace('H=max_circuito(Σh_ida+retorno+h_equipos+h_FCU)',{circuitos:l.circuitos},paths,'ft agua','[P3-pág.33]')};},
 ()=>{const t=s.tanque,cat=catalog(s),pipes=sum(r.dimensionamiento.secciones.map((x:any)=>x.L_recta_ft*cat[x.nps].wt_agua_lb_ft/8.34)),eq=num(t.volumen_equipos_gal,'Volumen equipos'),E=num(t.E,'E',true),a=num(t.P_a,'Pa',true),f=num(t.P_f,'Pf');if(E>=1||f>=a||a>1)fail('Tanque requiere 0<E<1 y 0≤Pf<Pa≤1; no son presiones en psi.');text(t.fuente,'fuente de coeficientes/volumen');warn('Tanque: verificar definición de coeficientes Pa/Pf con documento o fabricante.');const V=E*(pipes+eq)/(a-f);return {V_sist_tuberia_gal:pipes,V_equipos_gal:eq,V_sist_total_gal:pipes+eq,V_tanque_gal:V,P_a:a,P_f:f,E_pct:E*100,T_op_F:c.T_agua_caliente_F,trace:trace('Vt=E·Vs/(Pa−Pf)',{E,Vs_gal:pipes+eq,Pa:a,Pf:f},V,'gal','[P3-pág.34] · '+t.fuente)};},
 ()=>{const cat=catalog(s),rows=r.dimensionamiento.secciones.map((x:any)=>{const spacing=cat[x.nps].spacing_ft,N=Math.ceil(x.L_recta_ft/spacing);return {id:x.id,nps:x.nps,L_ft:x.L_recta_ft,spacing_ft:spacing,n_intervalos:N,n_soportes:N+1,fuente:cat[x.nps].fuente};});d.notas.push('Soportes por tramo con extremos; revisar encuentros compartidos.');return {soportes:rows,total_soportes:sum(rows.map((x:any)=>x.n_soportes)),trace:trace('N=ceil(L/separación)+1',{},rows,'unidades','[P3-pág.8]')};},
 ()=>{if(c.delta_T_agua_F<8||c.delta_T_agua_F>16)warn('ΔT frío fuera de intervalo [8,16] °F del código suministrado.');if(c.T_agua_frio_F<45||c.T_agua_frio_F>50)warn('Agua fría fuera de [45,50] °F.');const checks=WATER_STEPS.slice(0,8).map(key=>({nombre:key,estado:r[key]?.error?'error':'ok',valor:r[key]?.error?'No válido':'Calculado'}));return {checks,apto:!d.errores.length,errores:d.errores.length,trace:trace('Todos los pasos y dependencias válidos',{},checks,'estado','Contrato THERMABOT v1')};}
 ];
 const deps=[[],[0],[1],[1,2],[3],[2,3,4],[4],[4],[]];
 for(let i=0;i<9;i++){let status='ok',value:any;const before=d.errores.length;if(i!==8&&(!valid||deps[i].some(j=>pasos[j].estado!=='ok'))){status='bloqueado';value={error:'Dependencia o entrada inválida.'};}else try{value=functions[i]();finiteTree(value);if(d.errores.length>before||i===8&&d.errores.length)status='error';}catch(e){status='error';value={error:(e as Error).message};d.errores.push(WATER_LABELS[i]+': '+value.error);}r[WATER_STEPS[i]]=value;pasos.push({paso:i+1,nombre:WATER_LABELS[i],clave:WATER_STEPS[i],estado:status});}
 return {schema:'thermabot.carrier-water.v1',version:'1.1.0-web',proyecto:s.proyecto,input:s,resultado:r,diagnostico:d,pasos,apto:valid&&!d.errores.length&&pasos.every(p=>p.estado==='ok'),validacion_documental:'Pendiente: tablas suministradas; verificar tanque y catálogo antes de usar en obra.'};
}
